        // Kelime havuzu
        const wordPool = [
    { main: "ÖRGÜ", forbidden: ["KAZAK", "ATKI", "ŞİŞ", "YÜN", "NİNE"] },
    { main: "GEBE", forbidden: ["HAMİLE", "BEBEK", "DOĞURMAK", "EBE", "BORÇLU KALMAK"] },
    { main: "HAC", forbidden: ["HRİSTİYAN", "ÇAĞLA ŞİKEL", "ARTI İŞARETİ", "İSA", "ÇARMIH"] },
    { main: "KALEMLİK", forbidden: ["KALEM", "OKUL", "ÖĞRENCİ", "YAZI", "MASA ÜZERİ"] },
    { main: "ŞEMSİYE", forbidden: ["YAĞMUR", "EŞANTİYON", "GÖK GÜRÜLTÜSÜ", "YAZ", "YAĞMURLUK"] },
    { main: "KLOZET", forbidden: ["TUVALET", "ALAFRANGA", "SİFON", "ÇİŞ", "KAKA"] },
    { main: "CAMİ", forbidden: ["İMAM", "MÜSLÜMAN", "KİLİSE", "İBADET", "NAMAZ"] },
    { main: "FOTOKOPİ", forbidden: ["KOPYA", "MAKİNE", "FAX", "SCANNER", "KIRTASİYE"] },
    { main: "VAZO", forbidden: ["ÇİÇEK", "SU", "HEDİYE", "BUKET", "ÇİÇEKÇİ"] },
    { main: "MODEM", forbidden: ["İNTERNET", "ADSL", "WIRELESS", "FAX", "BİLGİSAYAR"] },
    { main: "UD", forbidden: ["FASIL", "SANAT MÜZİĞİ", "MÜZİK ALETİ", "SAZ", "GİTAR"] },
    { main: "BAĞLAMA", forbidden: ["TÜRKÜ", "ALEVİ", "CEM EVİ", "MÜZİK ALETİ", "SAZ"] },
    { main: "RANZA", forbidden: ["YATAK", "ALT ÜST", "ASKERİYE", "ODA", "MOBİLYA"] },
    { main: "REKTÖR", forbidden: ["ÜNİVERSİTE", "DEKAN", "KAMPÜS", "PROFESÖR", "YÖK"] },
    { main: "DIŞ TİCARET", forbidden: ["İTHALAT", "İHRACAT", "YABANCI", "SATMAK", "ÜRÜN"] },
    { main: "AB", forbidden: ["GİRMEK", "UYUM", "YASA", "KIBRIS", "KOPENHAG"] },
    { main: "KLAVYE", forbidden: ["MOUSE", "PC", "TUŞ", "KABLO", "HARF"] },
    { main: "YUMURTA", forbidden: ["KAHVALTI", "TAVUK", "CİVCİV", "KULUÇKA", "SAHAN"] },
    { main: "HÜLYA AVŞAR", forbidden: ["SİNEMA", "SANATÇI", "MAVİ GÖZ", "HELİN", "KAYA"] },
    { main: "SANDAL", forbidden: ["SEFA", "DENİZ", "KÜREK", "BALIKÇI", "MOTOR"] },
    { main: "CESET", forbidden: ["ÖLÜ", "CİNAYET", "KATİL", "OTOPSİ", "ADLİ TABİP"] },
    { main: "TİYATRO", forbidden: ["OYUNCU", "SAHNE", "PERDE", "YÖNETMEN", "OYUN"] },
    { main: "DENİZ", forbidden: ["TUZLU SU", "YAZ", "TATİL", "GEMİ", "MAYO"] },
    { main: "ZARF", forbidden: ["MEKTUP", "FATURA", "POSTAHANE", "POSTACI", "SINAV SONUÇ"] },
    { main: "MAKAS", forbidden: ["KAĞIT", "KESMEK", "KUMAŞ", "TERZİ", "NİŞAN"] },
    { main: "FATURA", forbidden: ["FİŞ", "FİRMA", "KDV", "EMEKLİ", "İRSALİYE"] },
    { main: "HAMAM BÖCEĞİ", forbidden: ["BANYO", "YIKANMAK", "HAŞERE", "KARAFATMA", "KUMPAKI"] },
    { main: "ARI", forbidden: ["BAL", "PETEK", "BALPARMAK", "AYI", "MAYA"] },
    { main: "HAKİM", forbidden: ["AVUKAT", "MAHKEME", "SUÇLU", "OLAY", "KONTROL ALTINA ALMAK"] },
    { main: "SONBAHAR", forbidden: ["MEVSİM", "YAPRAK", "AYLAR", "BAHAR", "HÜZÜN"] },
    { main: "MALA", forbidden: ["İNŞAAT", "DUVAR", "SIVA", "USTA", "ÇİMENTO"] },
    { main: "HİPODROM", forbidden: ["VELİ EFENDİ", "AT", "YARIŞ", "KOŞU", "JOKEY"] },
    { main: "PANTOLON", forbidden: ["AYAK", "JEANS", "KUMAŞ", "FERMUAR", "DÜĞME"] },
    { main: "TEHLİKE", forbidden: ["UYARI", "İKAZ", "ALARM", "YASAK", "ÖLÜM"] },
    { main: "PALET", forbidden: ["DENİZ", "BALIK", "DALGIÇ", "RESİM", "FIRÇA"] },
    { main: "TAVŞAN", forbidden: ["HAVUÇ", "UZUN KULAK", "BUGS BUNNY", "ÇİZGİ FİLM", "DİŞLEK"] },
    { main: "SİGARA", forbidden: ["TÜTÜN", "İÇİNE ÇEKMEK", "ÇAKMAK", "PAKET", "KÜL TABLASI"] },
    { main: "AĞDA", forbidden: ["KİL", "BACAK", "KADIN", "KUAFÖR", "SESU"] },
    { main: "ETEK", forbidden: ["KUMAŞ", "DİKİŞ", "TERZİ", "İSKOÇ", "GİYİSİ"] },
    { main: "MICHAEL JACKSON", forbidden: ["ZENCİ", "ŞARKICI", "TACİZ", "RENK DEĞİŞTİRMEK", "JANET JACKSON"] },
    { main: "AJANDA", forbidden: ["TAKVİM", "EŞANTİYON", "TARİH", "TELEFON REHBERİ", "YILBAŞI"] },
    { main: "SAÇ", forbidden: ["KUAFÖR", "ERKEK", "FÖN", "KESTİRMEK", "BOYATMAK"] },
    { main: "HOPARLÖR", forbidden: ["BİLGİSAYAR", "SES", "MÜZİK", "TV", "RADYO"] },
    { main: "KIRBAÇ", forbidden: ["KOVBOY", "AT ARABASI", "FANTEZİ", "DERİ", "İŞKENCE"] },
    { main: "NOSTRADAMUS", forbidden: ["KAHİN", "KEHANET", "FRANSA", "MÜNECCİM", "KİTAP"] },
    { main: "ŞAMDAN", forbidden: ["MUM", "ATEŞ", "IŞIK", "METAL", "YAKMAK"] },
    { main: "AMBULANS", forbidden: ["HASTANE", "ACİL", "ARAÇ", "HASTA", "SİREN"] },
    { main: "JÜPİTER", forbidden: ["ZEUS", "GEZEGEN", "DÜNYA", "KUYRUKLU YILDIZ", "BÜYÜK"] },
    { main: "AKVARYUM", forbidden: ["BALIK", "CAM", "FİLTRE", "SU", "DENİZ"] },
    { main: "ÖRÜMCEK", forbidden: ["AĞ", "SİNEK", "ADAM", "TARANTULA", "BACAK"] },
    { main: "KÜPE", forbidden: ["KULAK", "AKSESUAR", "HALKA", "DELİ", "DELİK"] },
    { main: "MUSLUK", forbidden: ["SU", "LAVABO", "BANYO", "MUTFAK", "BULAŞIK"] },
    { main: "RADYO", forbidden: ["MÜZİK", "İSTASYON", "FREKANS", "DJ", "CANLI YAYIN"] },
    { main: "OJE", forbidden: ["ASETON", "TIRNAK", "MANİKÜR", "TÖRPÜ", "EL"] },
    { main: "KABUS", forbidden: ["UYUMAK", "YATAK", "DÜŞ", "RÜYA", "KORKU"] },
    { main: "DOĞUMGÜNÜ", forbidden: ["PASTA", "MUM", "HEDİYE", "YAŞ", "PARTİ"] },
    { main: "İLAÇ", forbidden: ["PROSPEKTÜS", "SAĞLIK", "ECZANE", "DOKTOR", "REÇETE"] },
    { main: "SAAT", forbidden: ["YELKOVAN", "AKREP", "ZAMAN", "GÜN", "ALARM"] },
    { main: "KİTAP", forbidden: ["SAYFA", "ROMAN", "HİKÂYE", "AYRAÇ", "ŞİİR"] },
    { main: "İT", forbidden: ["KÖPEK", "KÜFÜR", "KOVALAMAK", "ISIRMAK", "TASMA"] },
    { main: "BEBEK", forbidden: ["DOĞUM", "ÇOCUK", "UFAK", "AĞLAMAK", "ZIBIN"] },
    { main: "MAIL", forbidden: ["MEKTUP", "İNTERNET", "YOLLAMAK", "BİLGİSAYAR", "İLETMEK"] },
    { main: "SIR", forbidden: ["YASAK", "ANLATMAMAK", "GİZLİ", "PAYLAŞMAMAK", "SAKLAMAK"] },
    { main: "KOZA", forbidden: ["KELEBEK", "UÇMAK", "BÖCEK", "TIRTIL", "KANAT"] },
    { main: "BABAFİNGO", forbidden: ["BABA", "GEMİ", "KALYON", "DİREK", "YELKEN"] },
    { main: "EXCEL", forbidden: ["HÜCRE", "TABLO", "MS OFFICE", "FILE", "WORD"] },
    { main: "TANGO", forbidden: ["ARJANTİN", "DANS", "LATİN", "AL PACINO", "TUTKU"] },
    { main: "ABAJUR", forbidden: ["LAMBA", "IŞIK", "AMPUL", "ELEKTRİK", "YASAK"] },
    { main: "AYI", forbidden: ["YOGİ", "KUTUP", "BOZ", "ARMUT", "HAYVAN"] },
    { main: "SİFONYER", forbidden: ["ÇEKMECE", "YASAK", "DOLAP", "GİYSİ", "ODA"] },
    { main: "FATİH SULTAN MEHMET", forbidden: ["İSTANBUL", "PADİŞAH", "OSMANLI", "GEMİ", "FETİH"] },
    { main: "HOLLANDA", forbidden: ["LALE", "TAHTA", "DEĞİRMEN", "AMSTERDAM", "ÜLKE"] },
    { main: "BALİNA", forbidden: ["MAVİ", "HAYVAN", "DENİZ", "MEMELİ", "SU"] },
    { main: "POKER", forbidden: ["KUMAR", "BAHİS", "TEXAS", "KART", "İSKAMBİL"] },
    { main: "MP3", forbidden: ["BİLGİSAYAR", "ŞARKI", "MÜZİK", "İNDİRMEK", "PROGRAM"] },
    { main: "AŞK", forbidden: ["SEVMEK", "SEVGİLİ", "FLÖRT", "HİS", "İLİŞKİ"] },
    { main: "KAVGA", forbidden: ["BAĞIRMAK", "TARTIŞMAK", "KIZMAK", "SİNİRLENMEK", "KÜSMEK"] },
    { main: "NEVRESİM", forbidden: ["ÇARŞAF", "YATAK", "UYKU", "TAKIM", "ÖRTMEK"] },
    { main: "ÇAKMAK", forbidden: ["SİGARA", "ATEŞ", "YAKMAK", "ZİPPO", "KİBRİT"] },
    { main: "YELKOVAN", forbidden: ["SAAT", "ZAMAN", "SÜRE", "AKREP", "DAKİKA"] },
    { main: "PERDE", forbidden: ["CAM", "TÜL", "PENCERE", "GECE", "KORNİŞ"] },
    { main: "ZIMBA", forbidden: ["KAĞIT", "TEL", "BİRLEŞTİRMEK", "DELGEÇ", "KIRTASİYE"] },
    { main: "DELGEÇ", forbidden: ["KAĞIT", "DELMEK", "ZIMBA", "KIRTASİYE", "DELİK"] },
    { main: "ZARF", forbidden: ["MEKTUP", "POSTA", "MAİL", "YAZMAK", "ASKER"] },
    { main: "KARTAL", forbidden: ["KUŞ", "FUTBOL TAKIMI", "KAFES", "YIRTICI", "KARA"] },
    { main: "MUTFAK", forbidden: ["YEMEK", "SOFRA", "HAZIRLAMAK", "FIRIN", "PİŞİRMEK"] },
    { main: "PRİZ", forbidden: ["ELEKTRİK", "FİŞ", "KABLO", "KONTROL KALEMİ", "TAMİRCİ"] },
    { main: "HALI", forbidden: ["EV", "YÜRÜMEK", "AYAK", "AYAKKABI", "YER"] },
    { main: "ÖDEV", forbidden: ["DERS", "ÇALIŞMAK", "OKUL", "ÖĞRETMEN", "EV"] },
    { main: "YÜZÜK", forbidden: ["PARMAK", "TAKI", "EVLİLİK", "NİKÂH", "NİŞAN"] },
    { main: "KALEMLİK", forbidden: ["KALEM", "SİLGİ", "KALEMTIRAŞ", "ATAÇ", "KALEM UCU"] },
    { main: "TEKERLEK", forbidden: ["TAŞIT", "YUVARLAK", "LASTİK", "SİBOP", "YASAK"] },
    { main: "KOLTUK", forbidden: ["OTURMAK", "ODA", "MİNDER", "DERİ", "SANDALYE"] },
    { main: "MASA", forbidden: ["YEMEK", "AYAK", "ÖRTÜ", "MUTFAK", "SALON"] },
    { main: "ANNE", forbidden: ["SEVEN", "KORUYAN", "DÜNYADA BİR TANE", "ÇOCUK", "BABA"] },
    { main: "YAZI", forbidden: ["KALEM", "KAĞIT", "HARF", "RAKAM", "KELİME"] },
    { main: "KRAL", forbidden: ["KRALİÇE", "TAHT", "ASKER", "CARİYE", "ŞATO"] },
    { main: "AĞAÇ", forbidden: ["DAL", "YAPRAK", "TIRTIL", "MEYVE", "YEŞİL"] },
    { main: "BEBEK", forbidden: ["ANNE", "BEZ", "EMZİK", "KOKU", "ANKA"] },
    { main: "ŞİMŞEK", forbidden: ["ÇAKMAK", "GÖK GÜRÜLTÜSÜ", "BULUT", "IŞIK", "YAĞMUR"] },
    { main: "MONTA", forbidden: ["SOĞUK", "KIŞ", "KAR", "YAĞMUR", "ÜŞÜMEK"] },
    { main: "EBE", forbidden: ["HASTA", "BEBEK", "DOĞUM", "DÜNYA", "KÖR"] },
    { main: "KIRMIZI", forbidden: ["DOMATES", "BOĞA", "RENK", "AL", "UTANMAK"] },
    { main: "SİGARA", forbidden: ["İÇMEK", "ZARAR", "KANSER", "CİĞER", "DUMAN"] },
    { main: "ORUÇ", forbidden: ["RAMAZAN", "BAYRAM", "ŞEKER", "KURBAN", "MÜSLÜMAN"] },
    { main: "KLİMA", forbidden: ["SOBA", "KALORİFER", "DUVAR", "YAZ", "SICAK"] },
    { main: "PLAY STATION", forbidden: ["BİLGİSAYAR", "OYUN", "JOY STICK", "TELEVİZYON", "ATARİ"] },
    { main: "DİGİTÜRK", forbidden: ["PARALI", "KABLO TV", "ÜYELİK", "PAKET", "TELEVİZYON"] },
    { main: "TAKVİM", forbidden: ["GÜN", "AY", "YIL", "YAPRAK", "SAYI"] },
    { main: "DİŞ", forbidden: ["ISIRMAK", "DOLGU", "AĞRI", "DİŞLEMEK", "AĞIZ"] },
    { main: "GELİNLİK", forbidden: ["DAMAT", "DÜĞÜN", "DANTEL", "BEYAZ", "TÜL"] },
    { main: "RAKI", forbidden: ["ASLAN SÜTÜ", "ANASON", "ALKOL", "BUZ", "MEZE"] },
    { main: "LİKİT FON", forbidden: ["PARA", "BANKA", "SIVI", "HESAP", "YATIRIM"] },
    { main: "CUMHURİYET", forbidden: ["GAZETE", "ATATÜRK", "YÖNETİM", "29 EKİM", "DEVLET"] },
    { main: "GÜNEŞ", forbidden: ["AY", "DOKTOR", "GECE", "DÜNYA", "YILDIZ"] },
    { main: "OKUL", forbidden: ["SIRA", "ÖĞRETMEN", "HADEME", "SINIF", "ÖĞRENCİ"] },
    { main: "APARTMAN", forbidden: ["DAİRE", "KAPICI", "ASANSÖR", "OTOMATİK", "KİRACI"] },
    { main: "OKEY", forbidden: ["TAŞ", "ZAR", "İSTAKA", "DÖNMEK", "GÖSTERGE"] },
    { main: "MUTFAK", forbidden: ["TENCERE", "ÇAYDANLIK", "YEMEK", "OCAK", "KAŞIK"] },
    { main: "SUCUK", forbidden: ["ET", "BAHARAT", "SALAM", "SOSİS", "PASTIRMA"] },
    { main: "KANAT", forbidden: ["UÇMAK", "MELEK", "UÇAK", "KUŞ", "TAVUK"] },
    { main: "BARON", forbidden: ["KONT", "ASİL", "SOYLU", "POLAT", "KURTLAR VADİSİ"] },
    { main: "BAMYA", forbidden: ["SEBZE", "YEŞİL", "TÜYLÜ", "KÜÇÜK", "SALYA"] },
    { main: "NASIR", forbidden: ["AYAK", "YARA", "SERTLEŞMEK", "KALP", "AYAKKABI"] },
    { main: "AYŞEKADIN", forbidden: ["FASULYE", "SEBZE", "YEŞİL", "İSİM", "ERKEK"] },
    { main: "DİPSİZ KUYU", forbidden: ["MUAMMA", "BİLİNMEYEN", "KARANLIK", "FİLM", "THE RING"] },
    { main: "KÖLE", forbidden: ["ISAURA", "ESİR", "HAPİSHANE", "PRANGA", "TUTSAK"] },
    { main: "FERMUAR", forbidden: ["PANTOLON", "MONT", "GİYSİ", "KIYAFET", "KOT"] },
    { main: "ARI", forbidden: ["SAF", "HALİS", "KATIŞIKSIZ", "YALIN", "HAYVAN"] },
    { main: "KELEBEK", forbidden: ["RENKLİ", "UÇMAK", "TIRTIL", "KOZA", "HAYVAN"] },
    { main: "UĞUR BÖCEĞİ", forbidden: ["HAYVAN", "UÇMAK", "BENEK", "KIRMIZI", "KANAT"] },
    { main: "TABU", forbidden: ["YASAK", "OYUN", "CİNSELLİK", "SEKS", "AŞMAK"] },
    { main: "MİKRO DALGA", forbidden: ["ALET", "DENİZ", "MUTFAK", "FIRIN", "ISITMAK"] },
    { main: "CÜPPE", forbidden: ["AVUKAT", "KIYAFET", "MEZUNİYET", "KEP", "TÖREN"] },
    { main: "DONDURMA", forbidden: ["SOĞUK", "YAZ", "SÜT", "K.MARAŞ", "KÜLAH"] },
    { main: "KÜNEFE", forbidden: ["PEYNİR", "KADAYIF", "ŞERBET", "KAYMAK", "SICAK"] },
    { main: "ATA DEMİRER", forbidden: ["KOMEDYEN", "ŞİŞMAN", "AVRUPA YAKASI", "STAND-UP", "KORSAN TV"] },
    { main: "LATİFE", forbidden: ["ATATÜRK", "FIRST LADY", "İNKILAP", "KADIN HAKLARI", "HANIM"] },
    { main: "VİAGRA", forbidden: ["KULLANMAK", "İLAÇ", "İKTİDARSIZLIK", "ANDROPOZ", "YAŞLI"] },
    { main: "FRANBOAZ", forbidden: ["PASTA", "PASTANE", "MEYVE", "PEMBE", "BOĞAZ"] },
    { main: "DUMUR", forbidden: ["KÖRELMEK", "APTALLAŞMAK", "ŞOK OLMAK", "ŞAŞIRMAK", "ŞAŞKINA DÖNMEK"] },
    { main: "KİBRİT", forbidden: ["VASATİ 40 ÇÖP", "ÇAKMAK", "ATEŞ", "SİGARA", "YAKMAK"] },
    { main: "UZLAŞMAK", forbidden: ["ANLAŞMAK", "İŞBİRLİĞİ", "İTTİFAK", "MUTABAKAT", "UYUŞMA"] },
    { main: "ŞEKERLEME", forbidden: ["ŞEKER", "BONBON", "TATLI", "LOKUM", "UYUKLAMAK"] },
    { main: "KASET", forbidden: ["VİDEO", "MÜZİK", "ŞARKI", "TEEP", "BANT"] },
    { main: "AVOKADO", forbidden: ["AMERİKA", "ARMUT", "TROPİK", "MEYVE", "ANANAS"] },
    { main: "BALON", forbidden: ["UYDURMA HABER", "PALAVRA", "UÇMAK", "ÇOCUK", "HELYUM"] },
    { main: "SIFIR", forbidden: ["YOK", "BAŞARISIZ", "EN KÜÇÜK SAYI", "TÜKENMEK", "VERİMSİZ"] },
    { main: "PARAŞÜT", forbidden: ["UÇAK", "ATLAMAK", "UÇMAK", "HAVADA SÜZÜLMEK", "BALON"] },
    { main: "MAYO", forbidden: ["BİKİNİ", "ŞORT", "TANGA", "DENİZ", "HAVUZ"] },
    { main: "ORTALAMA", forbidden: ["İKİSİ ARASINDA", "ORTASINDA", "YARISI", "ORTA KARAR", "VASAT"] },
    { main: "KARA KUTU", forbidden: ["UÇAK", "PİLOT", "HAVA", "SES KAYDI", "ENKAZ"] },
    { main: "PARAZİT", forbidden: ["CIZIRTI", "ASALAK", "TENYA", "AMİP", "KÖPEK BALIĞI"] },
    { main: "ŞEMPANZE", forbidden: ["MAYMUN", "AYI", "TIRMANMAK", "AĞAÇ", "İNSAN"] },
    { main: "EVLİLİK", forbidden: ["NİKAH", "DÜĞÜN", "GELİNLİK", "KARI-KOCA", "HALAY"] },
    { main: "VENEDİK", forbidden: ["GONDOL", "SU", "ÜLKE", "BALAYI", "İTALYA"] },
    { main: "KEK", forbidden: ["PASTA", "KALIP", "TOP", "HAMUR", "YEMEK"] },
    { main: "MUM", forbidden: ["IŞIK", "ROMANTİZM", "YEMEK", "ERİMEK", "KOKULU"] },
    { main: "BARDAK", forbidden: ["SU", "İÇMEK", "CAM", "İNCE BELLİ", "KADEH"] },
    { main: "KAHVE", forbidden: ["TÜRK", "FİNCAN", "FAL", "CEZVE", "SOHBET"] },
    { main: "BIYIK", forbidden: ["SAKAL", "TRAŞ", "PALA", "TÜKÜRMEK", "KAYTAN"] },
    { main: "ÇERÇEVE", forbidden: ["RESİM", "CAM", "FOTOĞRAF", "DUVAR", "GÖZLÜK"] },
    { main: "ÇORAP", forbidden: ["AYAK", "ÜŞÜMEK", "KOKMAK", "GİYMEK", "TERLEMEK"] },
    { main: "DAKTİLO", forbidden: ["HARF", "TUŞ", "STİLO", "KAĞIT", "YAZMAK"] },
    { main: "FOTOĞRAF", forbidden: ["POZ", "RESİM", "ÇEKMEK", "DEKLANŞÖR", "FLASH"] },
    { main: "KOLYE", forbidden: ["TAKI", "BONCUK", "ZİNCİR", "BİJUTERİ", "KUYUMCU"] },
    { main: "DOKTOR", forbidden: ["MESLEK", "HASTA", "REÇETE", "TIP", "SAĞLIK"] },
    { main: "KÜLLÜK", forbidden: ["SİGARA", "ÇAKMAK", "ATEŞ", "ÇÖP", "MASA"] },
    { main: "KÜF", forbidden: ["MANTAR", "BAKTERİ", "EKMEK", "YEŞİL", "KURT"] },
    { main: "NEDİME", forbidden: ["GELİN", "GELİNLİK", "DÜĞÜN", "DAMAT", "ÇİÇEK"] },
    { main: "BANKA", forbidden: ["PARA", "ÇEK", "SENET", "HAVALE", "SOYGUN"] },
    { main: "KRAVAT", forbidden: ["BOYUN", "YAKA", "GÖMLEK", "TAKIM ELBİSE", "MEDENİYET"] },
    { main: "ŞİFRE", forbidden: ["PAROLA", "KASA", "HIRSIZ", "KART", "BİLGİSAYAR"] },
    { main: "FOTOKOPİ", forbidden: ["KOPYA", "FOTO", "BASIM", "ÇOĞALTMA", "SURET"] },
    { main: "ALTIN", forbidden: ["KUYUMCU", "SARRAF", "KIYMET", "ÇEYREK", "TAKMAK"] },
    { main: "HARDAL", forbidden: ["BİTKİ", "HAMBURGER", "SOS", "SARI", "RENK"] },
    { main: "CETVEL", forbidden: ["OKUL", "DÜZGÜN", "UZUN", "ÖLÇME", "ÇİZGİ"] },
    { main: "SATRANÇ", forbidden: ["ŞAH-MAT", "KALE", "VEZİR", "PİYON", "FİL"] },
    { main: "SİVRİSİNEK", forbidden: ["HAYVAN", "UÇMAK", "KAN EMMEK", "İSKAMBİL", "GECE"] },
    { main: "ORUÇ", forbidden: ["İFTAR", "SAHUR", "RAMAZAN", "AÇLIK", "TERAVİH"] },
    { main: "KUMANDA", forbidden: ["UZAK", "TV", "TUŞ", "ZAP", "KANAL"] },
    { main: "FİLOLOJİ", forbidden: ["DİL BİLİM", "LİSAN", "İNGİLİZCE", "DİL VE EDEBİYAT", "ÜNİVERSİTE"] },
    { main: "NİLÜFER", forbidden: ["GÖL", "DERE", "ÇİÇEK", "KURBAĞA", "KAYHAN"] },
    { main: "NAFAKA", forbidden: ["BOŞANMAK", "GEÇİM", "PARA", "AYLIK", "AYRILMAK"] },
    { main: "MİKROBİK", forbidden: ["MİKROP", "VİRÜS", "BULAŞICI", "HASTALIK", "MİKROSKOP"] },
    { main: "İMLA KILAVUZU", forbidden: ["KELİME", "DOĞRU", "YANLIŞ", "REHBER", "KONTROL"] },
    { main: "PANİK ATAK", forbidden: ["HASTALIK", "ÖLÜM KORKUSU", "DEPRESYON", "PSİKOLOJİK", "TELAŞ"] },
    { main: "ANTİFRİZ", forbidden: ["KIŞ", "MOTOR", "DONMAK", "ÖNLEMEK", "SU"] },
    { main: "SODA", forbidden: ["MADEN SUYU", "İÇECEK", "GAZLI", "KAYNAK", "YER ALTI"] },
    { main: "ADEM ELMASI", forbidden: ["ERKEK", "GIRTLAK", "ÇIKINTI", "MEYVE", "HAVVA"] },
    { main: "ALAFRANGA", forbidden: ["TUVALET", "AVRUPAÎ", "GELENEK", "ÖRF", "ADET"] },
    { main: "MEGALOMAN", forbidden: ["KENDİNİ BEĞENMEK", "KASINTI", "BURNUNU HAVADA", "KİBİR", "ÖVÜNMEK"] },
    { main: "MANTAR", forbidden: ["BEYAZ SEBZE", "KÜF", "NEM", "ŞARAP", "ŞİŞE"] },
    { main: "RAFTİNG", forbidden: ["AKINTI", "DERE", "BOT", "KÜREK", "SU SPORU"] },
    { main: "BALDIR", forbidden: ["BACAK", "UYLUK", "VÜCUT", "AYAK", "DİZ"] },
    { main: "MENTOL", forbidden: ["NANE", "FERAH", "ŞEKER", "SAKIZ", "VİCKS"] },
    { main: "MİNYATÜR", forbidden: ["KÜÇÜK", "PROTOTİP", "UFAK", "MİNİK", "MİNYATÜRK"] },
    { main: "KEŞ", forbidden: ["ZOM", "ALKOLİK", "İÇKİCİ", "İÇKİ", "AKŞAMDAN KALMA"] },
    { main: "JAPON BALIĞI", forbidden: ["AKVARYUM", "FANUS", "TURUNCU", "TATLI SU", "GÖL"] },
    { main: "ŞEHVET", forbidden: ["ARZU", "İSTEK", "TUTKU", "CAZİBE", "KADIN"] },
    { main: "ZİNA", forbidden: ["İHANET", "ALDATMAK", "BİRLİKTE OLMAK", "SADAKAT", "KANDIRMAK"] },
    { main: "KETÇAP", forbidden: ["DOMATES SOSU", "MAKARNA", "PATATES", "MAYONEZ", "DÖK DÖK YE"] },
    { main: "SARMAŞIK", forbidden: ["BİTKİ", "YAPRAK", "TIRMANAN BİTKİ", "SARMAK", "SARILMAK"] },
    { main: "AYRILMAK", forbidden: ["TERK ETMEK", "İSTİFA ETMEK", "BIRAKMAK", "GİTMEK", "UZAKLAŞMAK"] },
    { main: "TERAZİ", forbidden: ["TARTI", "BASKÜL", "KANTAR", "KEFE", "TARTMAK"] },
    { main: "KUPA PAPAZI", forbidden: ["RIFKI", "KİNG", "İSKAMBİL", "KÂĞIT", "OYUN"] },
    { main: "GÖBEK BAĞI", forbidden: ["KORDON", "KESMEK", "DELİK", "ÇUKUR", "BEBEK"] },
    { main: "YUMUŞAK", forbidden: ["SERT", "GEVŞEK", "ESNEK", "LASTİK", "DOKUNMAK"] },
    { main: "CANKURTARAN", forbidden: ["BOĞULMAK", "DENİZ", "SAHİL", "AMBULANS", "KURTARMAK"] },
    { main: "ANTİKA", forbidden: ["DEĞERLİ", "ESKİ", "TİP", "CİNS", "MÜCEVHER"] },
    { main: "APSE", forbidden: ["İLTİHAP", "DİŞ", "SİVİLCE", "ERGENLİK", "AŞIRMAK"] },
    { main: "KÖYLÜ", forbidden: ["İN", "MAĞARA", "OYUK", "BARINAK", "HAYVAN"] },
    { main: "HEYKEL", forbidden: ["SANAT", "RESİM", "DÜŞÜNEN ADAM", "BÜST", "YONTMAK"] },
    { main: "SABAHLIK", forbidden: ["SABAH", "ROP DÖŞAMBR", "GİYİNMEK", "GİYSİ", "KAHVALTI"] },
    { main: "KAZIK", forbidden: ["ODUN", "SOPA", "PAHALI", "YÜKSEK FİYATLI", "ZOR"] },
    { main: "ŞEYTAN", forbidden: ["CEHENNEM", "ZEBANİ", "MELEK", "GÜNAH", "SEVAP"] },
    { main: "KİVİ", forbidden: ["PATATES", "MEYVE", "YEŞİL", "TROPİK", "ÇEKİRDEK"] },
    { main: "KAZULET", forbidden: ["AZMAN", "KOCAMAN", "UZUN", "KOSKOCA", "DEV"] },
    { main: "EBE", forbidden: ["JİNEKOLOG", "DOĞUM", "KADIN DOKTORU", "OYUN", "SAKLAMBAÇ"] },
    { main: "JÖLE", forbidden: ["SAÇ", "SÜRMEK", "TİTREMEK", "SALLANMAK", "ISLAK"] },
    { main: "HÖRGÜÇ", forbidden: ["DEVE", "KAMBUR", "ŞİŞKİNLİK", "SU", "BİNMEK"] },
    { main: "İKTİDAR", forbidden: ["OTORİTE", "MUHALEFET", "YETKİ", "KUVVET", "PARTİ"] },
    { main: "BÖRÜLCE", forbidden: ["SEBZE", "BAKLA", "FASULYE", "FAVA", "GÖRÜMCE"] },
    { main: "MASKARA", forbidden: ["SOYTARI", "RİMEL", "ŞAKLABAN", "GÖZ", "KİRPİK"] },
    { main: "NOTA", forbidden: ["SOL ANAHTARI", "DİYEZ", "BEMOL", "ES", "BESTE"] },
    { main: "KULUÇKA", forbidden: ["TAVUK", "HOROZ", "YUMURTA", "CİVCİV", "KÜMES"] },
    { main: "DEMİRBAŞ", forbidden: ["OFİS", "BÜRO EŞYASI", "DEĞİŞMEZ", "ESKİ", "MALZEME"] },
    { main: "RAKI", forbidden: ["MEZE", "BOĞMA", "MASTİKA", "ASLAN SÜTÜ", "ANASON"] },
    { main: "GÖKTAŞI", forbidden: ["UZAY", "ALEV TOPU", "ÇARPMak", "KRATER", "METEOR"] },
    { main: "KIRMIZI GÜL", forbidden: ["AŞK", "SEVGİ", "ÇİÇEK", "YILDÖNÜMÜ", "BUKET"] },
    { main: "CINGIRAK", forbidden: ["YILAN", "BEBEK", "ÇAN", "ZİL", "SÜRÜNGEN"] },
    { main: "SİLİKON", forbidden: ["DUDAK", "GÖĞÜS", "KADIN", "PATLAMAK", "ŞİŞMEK"] },
    { main: "HOKKABAZ", forbidden: ["SİHİRBAZ", "İLLÜZYONİST", "MANDRAKE", "HİLEBAZ", "CEM YILMAZ"] },
    { main: "ÇELENK", forbidden: ["CENAZE", "DÜĞÜN", "ÇİÇEK", "BUKET", "İSMİ"] },
    { main: "ELMA", forbidden: ["YASAK", "MEYVE", "ARMUT", "KIRMIZI", "ADEM HAVVA"] },
    { main: "HEYELAN", forbidden: ["TOPRAK KAYMASI", "AĞAÇ", "YAĞMUR", "STEP", "ÇAMUR"] },
    { main: "KOBRA", forbidden: ["YILAN", "SÜRÜNGEN", "HAYVAN", "ÇINGIRAKLI YILAN", "PİTON"] },
    { main: "GÖZYAŞI", forbidden: ["AĞLAMAK", "GÖZ", "SU", "SİLMEK", "NEMLİ"] },
    { main: "GİRDAP", forbidden: ["ANAFOR", "BURGAÇ", "DÖNMEK", "SU", "DENİZ"] },
    { main: "KAYMAK", forbidden: ["SÜT", "SKİ", "KAYDIRAK", "BAL", "TATLI"] },
    { main: "DÜĞÜN", forbidden: ["GELİN", "DAMAT", "PASTA", "YÜZÜK", "NİKÂH MEMURU"] },
    { main: "ABAJUR", forbidden: ["LAMBA", "AVİZE", "IŞIK", "APLİK", "KİTAP OKUMAK"] },
    { main: "KULAK MEMESİ", forbidden: ["ORGAN", "DUYU", "SES", "GÖĞÜS", "KEPÇE"] },
    { main: "BOYNUZ", forbidden: ["KULAK", "ALDATMAK", "BOĞA", "KEÇİ", "GEYİK"] },
    { main: "GERDEK GECESİ", forbidden: ["GELİN GÜVEY", "DÜĞÜN", "EVLENMEK", "YATAK", "BEKÂRET"] },
    { main: "SÖZLÜK", forbidden: ["KELİME", "TANIM", "CÜMLE", "DİL", "ANLAM"] },
    { main: "NAZAR BONCUĞU", forbidden: ["GÖZ", "MAVİ", "ÇOCUK", "ÇENGELLİ İĞNE", "TAKMAK"] },
    { main: "BABAM VE OĞLUM", forbidden: ["SİNEMA FİLMİ", "ÇAĞAN IRMAK", "DEDE", "AĞLAMAK", "HÜMEYRA"] },
    { main: "TANRI", forbidden: ["İNANMAK", "ALLAH", "ELÇİ", "PEYGAMBER", "DİN"] },
    { main: "PENGUEN", forbidden: ["KARİKATÜR", "KUTUPLAR", "HAYVAN", "YİĞİT ÖZGÜR", "ERDAL YAŞAROĞLU"] },
    { main: "ANAHTAR", forbidden: ["ÇİLİNGİR", "KAPI", "KİLİT", "UNUTMAK", "AÇMAK"] },
    { main: "NEW YORK", forbidden: ["A.B.D.", "GEORGE BUSH", "METRO", "ÖZGÜRLÜK ANITI", "CENTRAL PARK"] },
    { main: "ORGANİZE İŞLER", forbidden: ["YILMAZ ERDOĞAN", "HIRSIZLIK", "SİNEMA FİLMİ", "SÜPERMEN", "NİL KARAİBRAHİMGİL"] },
    { main: "PANSİYON", forbidden: ["YATAK", "TATİL", "KLİMA", "BOŞ ODA", "SAHİL"] },
    { main: "AVRUPA YAKASI", forbidden: ["İSTANBUL", "DİZİ", "GÜLSE BİRSEL", "ATV", "ÇARŞAMBA"] },
    { main: "İNTERNET", forbidden: ["MAİL", "MODEM", "ADSL", "CHAT", "CAFE"] },
    { main: "HAMAM", forbidden: ["SAUNA", "MASAJ", "TELLAK", "TAKUNYA", "KESE"] },
    { main: "KAPADOKYA", forbidden: ["GÖREME", "ÜRGÜP", "ŞARAP", "YERALTI ŞEHRİ", "TATİL"] },
    { main: "GÖNÜL YARASI", forbidden: ["SİNEMA FİLMİ", "ŞENER ŞEN", "MELTEM CUMBUL", "NAZIM", "SAMATYA"] },
    { main: "SAĞDIÇ", forbidden: ["DAMAT", "DÜĞÜN", "GELİN", "GÜVEY", "SIRTINA VURMAK"] },
    { main: "ECZANE", forbidden: ["ECZACI", "İLAÇ", "REÇETE", "KALFA", "HASTA"] },
    { main: "BABA", forbidden: ["MAFYA", "ÇOCUK", "ERKEK", "ANNE", "AİLE"] },
    { main: "ZEUS", forbidden: ["ESKİ YUNAN", "MİTOLOJİ", "ANTİK ŞEHİR TANRISI", "OLİMPOS DAĞI", "HEYKEL"] },
    { main: "PUZZLE", forbidden: ["YAP BOZ", "RESİM", "BULMACA", "KARTON", "OYUN"] },
    { main: "GÖZLÜK", forbidden: ["GÖRMEK", "GÖZ", "ÇERÇEVE", "ORGANİK CAM", "GÜNEŞ"] },
    { main: "ITUNES", forbidden: ["MÜZİK", "WINAMP", "MP3", "LİSTE", "ŞARKI"] },
    { main: "KALP", forbidden: ["ORGAN", "YAŞAM", "KRİZ", "AŞK", "KAN KIRMIZI"] },
    { main: "GÜNEŞ", forbidden: ["SARI", "YUVARLAK", "SİSTEM", "DOĞMAK", "DÜNYA"] },
    { main: "ŞENER ŞEN", forbidden: ["YEŞİLÇAM", "EŞKIYA", "İKİNCİ BAHAR", "AKTÖR", "BADİ EKREM"] },
    { main: "HİNDİSTAN", forbidden: ["BAHARAT", "GÜNEY ASYA", "GHANDI", "İPEK YOLU", "ÜLKE"] },
    { main: "BULUT", forbidden: ["GÖKYÜZÜ", "MAVİ", "GÜNEŞ", "YAĞMUR", "HAVA"] },
    { main: "SEVGİLİLER GÜNÜ", forbidden: ["14 ŞUBAT", "AŞK", "HEDİYE", "KIRMIZI GÜL", "ÇİÇEK"] },
    { main: "ÜNİVERSİTE", forbidden: ["EĞİTİM", "OKUL", "ÖSS", "ÖĞRENCİ", "FAKÜLTE"] },
    { main: "METEOROLOJİ", forbidden: ["HAVA DURUMU", "YAĞMUR", "FIRTINA", "BARAJ", "DERE TAŞMASI"] },
    { main: "İKİZ TORNADO", forbidden: ["HORTUM", "FIRTINA", "KASIRGA", "DOLU", "METEOROLOJİ"] },
    { main: "SEL", forbidden: ["YAĞMUR", "TAŞKIN", "FELAKET", "SU BASKINI", "AFET"] },
    { main: "LADY GAGA", forbidden: ["ŞARKICI", "GİYİM", "TESETTÜR", "POKER FACE", "POP"] },
    { main: "SURVIVOR", forbidden: ["ACUN", "TV PROGRAMI", "YARIŞMA", "ADA", "SMS"] },
    { main: "LEYLEK", forbidden: ["KUŞ", "BEYAZ", "KIRMIZI GAGA", "GÖÇ", "YAZ"] },
    { main: "POKER", forbidden: ["KAĞIT", "KUMAR", "İSKAMBİL", "OYUN", "BLÖF"] },
    { main: "SÜPERMAN", forbidden: ["KAH­RAMAN", "UÇMAK", "METROPOLİS", "PENCERE", "GÖMLEK"] },
    { main: "RÖNTGEN", forbidden: ["GİZLİCE BAKMAK", "PENCERE", "SEYRETMEK", "GİZLENMEK", "İZLEMEK"] },
    { main: "HARRY POTTER", forbidden: ["SİHİR", "BÜYÜCÜ", "ASA", "FİLM", "KİTAP"] },
    { main: "ŞİFONYER", forbidden: ["ÇEKMECE", "DOLAP", "GİYSİ", "EŞYA", "ODA"] },
    { main: "ANTİBİYOTİK", forbidden: ["İLAÇ", "HASTALIK", "ECZANE", "BÖLMEK", "MİKROP"] },
    { main: "DAVUL", forbidden: ["TOKMAK", "MÜZİK", "ZURNA", "CÜMBÜŞ", "TEF"] },
    { main: "SESLİK", forbidden: ["MİKROFON", "SES", "KONUŞMAK", "KAYIT", "HOPARLÖR"] },
    { main: "TENİS", forbidden: ["RAKET", "TOP", "SERVİS", "ÇİM", "WIMBLEDON"] },
    { main: "NARGİLE", forbidden: ["TÖMBEKİ", "DUMAN", "KÖMÜR", "KAFE", "İÇMEK"] },
    { main: "ÖZGÜRLÜK HEYKELİ", forbidden: ["NEW YORK", "ABD", "ANIT", "MEŞALE", "ADA"] },
    { main: "KIZ KULESİ", forbidden: ["İSTANBUL", "ÜSKÜDAR", "DENİZ", "EFSANE", "BOĞAZ"] },
    { main: "PAPYON", forbidden: ["BALO", "ERKEK", "KRAVAT", "SMOKİN", "GÖMLEK"] },
    { main: "YALAKA", forbidden: ["YAĞCI", "RİYAKAR", "PATRON", "İŞYERİ", "İLTİFAT"] },
    { main: "ÇALMAK", forbidden: ["ARAKLAMAK", "HIRSIZ", "EV", "İZİN", "POLİS"] },
    { main: "DVD", forbidden: ["CD", "PLAYER", "FİLM", "KALİTE", "GÖRÜNTÜ"] },
    { main: "KAHVE", forbidden: ["ZEYK", "KAFEİN", "SİGARA", "SÜT TOZU", "FİNCAN"] },
    { main: "ASETON", forbidden: ["PARMAK", "OJE", "SÜRMEK", "MANİKÜR", "SİLMEK"] },
    { main: "ORMANCI", forbidden: ["MÜZEYYEN SENAR", "BALTA", "AĞAÇ", "YÜRÜYÜŞ", "KULUBE"] },
    { main: "NEVŞEHİR", forbidden: ["İL", "KAPADOKYA", "ÜRGÜP", "PERİ BACASI", "GÖREME"] },
    { main: "MOUSE", forbidden: ["BİLGİSAYAR", "TIKLAMA", "İNTERNET", "PARMAK", "FARE"] },
    { main: "KALDIRIM", forbidden: ["YAYA", "ARABA", "GEÇİT", "KAZA", "YÜRÜMEK"] },
    { main: "TABUT", forbidden: ["ÖLÜ", "CENAZE", "MORG", "NAMAZ", "MEZARLIK"] },
    { main: "MEHMET ALİ ERBİL", forbidden: ["ŞEBEK", "SOYTARI", "ÇARKIFELEK", "KAHPE BİZANS", "YARIŞMA"] },
    { main: "PET ŞİŞE", forbidden: ["SU", "ÇÖP TENEKEESİ", "ATIK", "NAYLON", "İÇMEK"] },
    { main: "ÖKÜZ", forbidden: ["BÜYÜKBAŞ HAYVAN", "BOYNUZ", "TREN", "İNEK", "ET"] },
    { main: "YÜRÜYEN MERDİVEN", forbidden: ["ALIŞVERİŞ MERKEZİ", "BASAMAK", "ELEKTRİK", "ÇIKMAK", "YAŞLI"] },
    { main: "PROJE", forbidden: ["İNŞAAT", "MİMAR", "MÜHENDİS", "CETVEL", "ÇİZİM"] },
    { main: "GÖZLÜK", forbidden: ["MİYOP", "RENKLİ", "TAKMAK", "GÜNEŞ", "GÖRMEK"] },
    { main: "KUMBARA", forbidden: ["PARA", "BİRİKTİRMEK", "YATIRIM", "BANKA", "SAKLAMAK"] },
    { main: "BANKA", forbidden: ["YATIRIM", "PARA", "SAKLAMAK", "FİNANS", "KREDİ"] },
    { main: "TELEFON", forbidden: ["ŞEBEKE", "GSM", "KONTÖR", "HAT", "AHİZE"] },
    { main: "SİNEMA", forbidden: ["BİLET", "BAHŞİŞ", "FİLM", "KARANLIK", "PATLAMIŞ MISIR"] },
    { main: "ÇANTA", forbidden: ["KAPKAÇÇI", "CÜZDAN", "KADIN", "EŞYA", "KOLA TAKMAK"] },
    { main: "GÖZLÜK", forbidden: ["GÖZ", "CAM", "ÇERÇEVE", "TEKMAK", "BAKMAK"] },
    { main: "MAYMUN", forbidden: ["HAYVAN", "MUZ", "ŞEBEKLİK", "EVRİM", "ÇİKİTA"] },
    { main: "REPO", forbidden: ["MENKUL KIYMET", "BANKA", "LİKİT", "FON", "GECE"] },
    { main: "EMZİK", forbidden: ["EMMEK", "BEBEK", "NAYLON", "AĞLAMAK", "MEME"] },
    { main: "GEMİ", forbidden: ["DENİZ", "FİLİKA", "YOLCU", "KAPTAN", "PALAMAR"] },
    { main: "KREM", forbidden: ["VÜCUT", "SIVI", "EL", "KOZMETİK", "İLAÇ"] },
    { main: "FİNCAN", forbidden: ["ÇAY", "KAHVE", "SICAK", "KULP", "İÇMEK"] },
    { main: "PARFÜM", forbidden: ["KOKU", "GÜZEL", "MİS GİBİ", "SIKMAK", "TERLEMEK"] },
    { main: "OTOMOBİL", forbidden: ["TEKERLEK", "DİREKSİYON", "MOTOR YAĞI", "KORNA", "EMNİYET KEMERİ"] },
    { main: "ANTİKA", forbidden: ["MÜZAYEDE", "ZENGİN", "ESKİ", "TABLO", "PARA"] },
    { main: "AŞÇI", forbidden: ["YEMEK", "MESLEK", "ÖNLÜK", "MUTFAK", "YİYECEK"] },
    { main: "İLAÇ", forbidden: ["HASTA", "ATEŞ", "HAP", "İYİLEŞMEK", "YATAK"] },
    { main: "KEDİ", forbidden: ["SARMAN", "PAMUK", "TÜY", "KUYRUK", "ŞIMARIK"] },
    { main: "OKUL", forbidden: ["ÖĞRENCİ", "ÖĞRETMEN", "DEFTER", "KALEM", "ZİL"] },
    { main: "SÜRAHİ", forbidden: ["SU", "BARDAK", "DÖKMEK", "MUTFAK", "HANIM"] },
    { main: "FOTOĞRAF MAKİNESİ", forbidden: ["FLAŞ", "TAB", "RESİM", "ÇEKİM", "POZ"] },
    { main: "TURİZM", forbidden: ["TATİL", "GEZMEK", "OTEL", "ŞİRKET", "TUR"] },
    { main: "BANKA", forbidden: ["PARA", "HESAP", "MEMUR", "MÜDÜR", "MÜŞTERİ"] },
    { main: "YASTIK", forbidden: ["UYKU", "YUMUŞAK", "TÜY", "BAŞ", "ORTOPEDİK"] },
    { main: "DOLAP", forbidden: ["RAF", "KAPI", "ASKI", "TABAK", "ELBİSE"] },
    { main: "AĞLAMAK", forbidden: ["YAŞ", "GÖZ", "AKMAK", "SOĞAN", "ÜZÜLMEK"] },
    { main: "MASA", forbidden: ["YEMEK", "BACAK", "SANDALYE", "ÖRTÜ", "MOBİLYA"] },
    { main: "TELEFON", forbidden: ["ALO", "AHİZE", "CEP", "KONUŞMAK", "TELSİZ"] },
    { main: "TÜRBAN", forbidden: ["BAŞ", "SAÇ", "ÖRTMEK", "DİN", "KADIN"] },
    { main: "SAAT", forbidden: ["KOL", "DUVAR", "ZAMAN", "SAYI", "24"] },
    { main: "ANAHTAR", forbidden: ["KİLİT", "METAL", "KASA", "KAPI", "ÇİLİNGİR"] },
    { main: "MASA", forbidden: ["ÇEKMECE", "BİLGİSAYAR", "YEMEK", "KALEM", "DOSYA"] },
    { main: "KAZAK", forbidden: ["YÜN", "İPLİK", "SICAK", "ORME", "YASAK"] },
    { main: "EXCEL", forbidden: ["OFFİCE", "BİLGİSAYAR", "TABLO", "FORMÜL", "WORD"] },
    { main: "KARYOLA", forbidden: ["YATAK", "RANZA", "YASTIK", "AHŞAP", "KAT"] },
    { main: "BİLGİSAYAR", forbidden: ["FARE", "EKRAN", "WINDOWS", "EXCEL", "WORD"] },
    { main: "BALIK", forbidden: ["FIRIN", "TAVA", "ROKA", "HELMİ", "OLTA"] },
    { main: "KALECİ", forbidden: ["FUTBOL", "TOP", "GOL", "ELDİVEN", "PENALTI"] },
    { main: "BANKA", forbidden: ["PARA", "FAİZ", "ZENGİN", "HIRSIZ", "SOYGUN"] },
    { main: "PARA", forbidden: ["EV", "ARABA", "GAYRIMENKUL", "MENKUL", "BONO"] },
    { main: "SİLAH", forbidden: ["SAVUNMA", "SALDIRI", "MERMİ", "NAMLU", "ATEŞ ETMEK"] },
    { main: "YENİÇERİ", forbidden: ["OSMANLI", "TÜRK", "ASKER", "ASAKİR-İ MUHAMMED", "KAZAN KALDIRMAK"] },
    { main: "BÖCEK", forbidden: ["ZEHİR", "HAYVAN", "YARATIK", "SİNEK", "HAŞERE"] },
    { main: "BORSA", forbidden: ["İNİŞ", "ÇIKIŞ", "HİSSE", "SÜPEKÜLASYON", "BROKER"] },
    { main: "TÜRKİYE", forbidden: ["ATATÜRK", "CENNET", "BÜYÜK", "İSTANBUL", "ÜLKE"] },
    { main: "BİSİKLET", forbidden: ["TEKERLEK", "DİREKSİYON", "PEDAL", "FREN", "ÇOCUK"] },
    { main: "FATURA", forbidden: ["BORÇ", "KAĞIT", "POSTACI", "PARA", "FİŞ"] },
    { main: "KAFATASI", forbidden: ["BEYİN", "SAÇ", "KEMİK", "ARKEOLOJİ", "KAZI"] },
    { main: "REÇETE", forbidden: ["DOKTOR", "İLAÇ", "İMZA", "HASTANE", "ECZANE"] },
    { main: "BANKA", forbidden: ["MÜŞTERİ", "PARA", "HESAP", "ÇEK", "KREDİ KARTI"] },
    { main: "EV", forbidden: ["ODA", "SALON", "WC", "YAŞAMAK", "YUVA"] },
    { main: "GAGA", forbidden: ["KUŞ", "YEMEK", "YAVRU", "SOLUCAN", "AĞAÇKAKAN"] },
    { main: "AKREP", forbidden: ["BURÇ", "SAAT", "YELKOVAN", "ZAMAN", "TÖRE"] },
    { main: "DÜĞÜN", forbidden: ["GELİN", "DAMAT", "MİSAFİR", "YÜZÜK", "EVLENMEK"] },
    { main: "OFİS", forbidden: ["ÇALIŞMAK", "PARA", "FOTOKOPİ", "FAKS", "TELEFON"] },
    { main: "AHİZE", forbidden: ["TELEFON", "SES", "ALO", "TUŞ", "KABİN"] },
    { main: "APLİK", forbidden: ["DUVAR", "IŞIK", "LAMBA", "AYDINLIK", "SÜS"] },
    { main: "ARABA", forbidden: ["ULAŞIM", "ARAÇ", "HIZ", "FREN", "GAZ"] },
    { main: "OTEL", forbidden: ["UYUMAK", "TATİL", "HİZMET", "PALAS", "MASAJ"] },
    { main: "ÇERÇEVE", forbidden: ["CAM", "RESİM", "PİMAPEN", "AHŞAP", "GÖZLÜK"] },
    { main: "FUTBOL", forbidden: ["TOP", "İDDAA", "KALE", "MAÇ", "STADYUM"] },
    { main: "UÇAK", forbidden: ["UÇMAK", "HAVA", "HIZ", "HOSTES", "PİLOT"] },
    { main: "DOST", forbidden: ["GÜVEN", "SAMİMİ", "DÜRÜST", "NAMUSLU", "AHLÂKLI"] },
    { main: "TAVLA", forbidden: ["ZAR", "OYUN", "YENMEK", "MARS", "KAPI"] },
    { main: "PARA", forbidden: ["KAĞIT", "DOLAR", "SATIN ALMA", "ÜLKE", "KAZANMAK"] },
    { main: "MOUSE", forbidden: ["FARE", "BİLGİSAYAR", "KLAVYE", "TUŞ", "KLİK"] },
    { main: "OJE", forbidden: ["TIRNAK", "RENK", "SÜRMEK", "ASETON", "MANİKÜR"] },
    { main: "GOOGLE", forbidden: ["ARAMA MOTORU", "BİLGİSAYAR", "İNTERNET", "SİTE", "SAYFA"] },
    { main: "ÇORAP", forbidden: ["İNCE", "KAÇMAK", "TEN RENGİ", "PARİZYEN", "AYAK"] },
    { main: "TAKVİM", forbidden: ["YIL", "AY", "HAFTA", "GÜN", "SAYI"] },
    { main: "ŞİMŞEK", forbidden: ["GÖKYÜZÜ", "YAĞMUR", "IŞIK", "KALP KRİZİ", "KORKU"] },
    { main: "BILL GATES", forbidden: ["ZENGİN", "MICROSOFT", "PARA", "PC", "WINDOWS"] },
    { main: "KALEM", forbidden: ["KURŞUN", "TÜKENMEZ", "DOLMA", "KAĞIT", "ÇİZGİ"] },
    { main: "TELEFON", forbidden: ["ALO", "AHİZE", "TUŞ", "SES", "NUMARA"] },
    { main: "STETESKOP", forbidden: ["SES", "KALP", "DOKTOR", "BOYUN", "KULAK"] },
    { main: "OKEY", forbidden: ["ZAR", "ISTAKA", "TAŞ", "4 KİŞİ", "OYUN"] },
    { main: "AŞK", forbidden: ["KALP", "BAYAN & ERKEK", "TUTKU", "KIRMIZI", "SEKS"] },
    { main: "MÜCEVHER", forbidden: ["KADIN", "TAKI", "ALTIN", "BİLEZİK", "KOLYE"] },
    { main: "HASTALIK", forbidden: ["HASTANE", "HASTA", "DOKTOR", "HEMŞİRE", "İLAÇ"] },
	{ main: "ASTRONOT", forbidden: ["UZAY KIYAFETİ", "AY YÜRÜYÜŞÜ", "KAPSÜL KAPISI", "YER ÇEKİMSİZ ORTAM", "EĞİTİM MERKEZİ"] },
{ main: "ROBOT", forbidden: ["METAL KOL", "PROGRAMLAMA PANELİ", "ENDÜSTRİ HATTI", "OTOMASYON SİSTEMİ", "YAPAY MOTOR"] },
{ main: "PİKNİK SEPETİ", forbidden: ["KIR GEZİNTİSİ", "KARELİ ÖRTÜ", "TERMO ÇANTA", "TERMOS BARINDIRMAK", "PLASTİK TABAKLAR"] },
{ main: "ŞÖMİNE", forbidden: ["ODUN ALEVİ", "KÖŞE KÖŞKÜ", "ISITMA NİŞİ", "KIVILCIM KORUYUCU", "KOR HALİ"] },
{ main: "SERA", forbidden: ["CAM YAPILANMA", "NEMLİ ORTAM", "BİTKİ YETİŞTİRME ALANI", "ISITMA BORUSU", "FİDAN SIRASI"] },
{ main: "TRAFİK IŞIĞI", forbidden: ["KAVŞAK DÜZENLEYİCİ", "KIRMIZI SİNYAL", "YEŞİL SİNYAL", "SARI UYARI", "YAYA BEKLEME NOKTASI"] },
{ main: "UYDU", forbidden: ["YÖRÜNGE HATTI", "SİNYAL GÖNDERİCİ", "KUMANDA MERKEZİ", "UZAY ANTENİ", "HARİTA KONUMU"] },
{ main: "PATEN PİSTİ", forbidden: ["KAYGAN ZEMİN", "KORUYUCU DİZLİK", "DENGELİ KAYMA", "MÜZİKLİ ALAN", "DÖNÜŞ FİGÜRÜ"] },
{ main: "PİRAMİT", forbidden: ["TAŞ BLOK", "ESKİ ANIT", "ÜÇGEN YÜZ", "GİZLİ GEÇİT", "TEPE NOKTASI"] },
{ main: "ÇİZGİ ROMAN", forbidden: ["KARE KARE ANLATIM", "BALONLU KONUŞMA", "SÜPER KAHRAMAN", "KOLEKSİYON SAYISI", "RENKLİ KAPAK"] },
{ main: "LUNAPARK", forbidden: ["DÖNEN KULE", "ÇARPIŞAN ARAÇ", "BİLET KONTROLÜ", "RENKLİ IŞIKLAR", "PAMUK ŞEKER"] },
{ main: "GALAKSİ", forbidden: ["YILDIZ KÜMESİ", "SPİRAL YAPI", "SAMANYOLU BENZERİ", "KOZMİK TOZ", "MERKEZİ ÇEKİRDEK"] },
{ main: "KUM SAATİ", forbidden: ["CAM REZERVUAR", "AKAN TANECİKLER", "SÜRE ÖLÇÜMÜ", "TERS ÇEVİRMEK", "SAND TANESİ"] },
{ main: "VİTRİN MANKENİ", forbidden: ["SERT POZ", "GİYSİ SERGİSİ", "CAM ARKASI", "İNDİRİM ETİKETİ", "DEKOR DİZGİSİ"] },
{ main: "PODYUM", forbidden: ["YÜRÜYÜŞ HATTI", "SPOT IŞIĞI", "DEFİLE SONU", "ARKA PLAN MÜZİĞİ", "MODEL SIRASI"] },
{ main: "TERMOS", forbidden: ["SICAK İÇECEK KABI", "İZOLASYON TABAKASI", "ÇİFT DUVAR YAPI", "SIZDIRMAZ KAPAK", "YANINDA TAŞIMA SAPI"] },
{ main: "VİTRAY CAM", forbidden: ["RENKLİ PARÇA", "KURŞUN ÇERÇEVE", "GÜNEŞ GEÇİŞİ", "DESENLİ PENCERE", "MOTİFLİ PANELLER"] },
{ main: "RESİM SERGİSİ", forbidden: ["AÇILIŞ KOKTEYLİ", "KÜLTÜR MERKEZİ", "TABLO ASKI SİSTEMİ", "SANATÇI İMZASI", "KÜRATÖR METNİ"] },
{ main: "SERUM ASKISI", forbidden: ["TEKERLEKLİ AYAK", "ŞEFFAF POŞET", "DAMLA AYARI", "İNCE HORTUM", "YATAK YANI"] },
{ main: "ROKET", forbidden: ["FIRLATMA RAMPA", "YAKIT TANKI", "AYRILAN KATMAN", "BURUN KONİSİ", "İTİCİ GÜÇ"] },
{ main: "LABORATUVAR ÖNLÜĞÜ", forbidden: ["KORUYUCU KUMAŞ", "CEPLİ TASARIM", "DENEY ORTAMI", "KİMYASAL SIÇRAMA", "GÖZLÜKLE BERABER"] },
{ main: "KONSER BİLETİ", forbidden: ["SIRA NUMARASI", "KAPI GİRİŞİ", "BİLEKLİK DEĞİŞİMİ", "KULİS ALANI", "SAHNE ÖNÜ"] },
{ main: "METRO İSTASYONU", forbidden: ["YERALTI PERONU", "TURNİKE GİRİŞİ", "HAT HARİTASI", "BEKLEME BANKOSU", "ANONS SİSTEMİ"] },
{ main: "BARBEKÜ", forbidden: ["IZGARA TELİ", "KÖMÜR KOVASI", "MARİNE EDİLMİŞ ET", "DUMAN KOKUSU", "BAHÇE TOPLANTISI"] },
{ main: "AKORDİYON", forbidden: ["KATLANIR GÖVDE", "TUŞ SIRASI", "HAVA ODASI", "RİTİM EZGİSİ", "SOKAK MÜZİSYENİ"] },
{ main: "SAKIZ MAKİNESİ", forbidden: ["RENKLİ KAPSÜL", "ŞEFFAF KÜRE", "MADENİ PARA YUVASI", "DÖNER KOL", "ŞEKER TOPU"] },
{ main: "KAYIKHANE", forbidden: ["KIYI BİNASI", "SUYA İNİŞ RAMPASI", "KÜREK DİZİLİMİ", "CAN YELEĞİ ASKISI", "YAZ SEZONU HAZIRLIĞI"] },
{ main: "HAVAALANI", forbidden: ["KALKIŞ PİSTİ", "BAVUL BANDI", "PASAPORT KONTROLÜ", "GÜVENLİK KAPISI", "KULE İLETİŞİMİ"] },
{ main: "PASAPORT", forbidden: ["VİZE SAYFASI", "BİYOMETRİK FOTOĞRAF", "GİRİŞ DAMGASI", "KAPAK RENGİ", "YURTDIŞI GEÇİŞİ"] },
{ main: "PUSULA", forbidden: ["MANYETİK İBRE", "KUZEY GÖSTERGESİ", "DAİRE KADRAN", "YÖN BULMAK", "HARİTA ÜSTÜ"] },
{ main: "TREN RAYI", forbidden: ["ÇELİK ÇİZGİ", "TRAVERS DİZİLİMİ", "İSTASYON GİRİŞİ", "DÜDÜK SESİ", "SEFER HATTI"] },
{ main: "DÜRBÜN", forbidden: ["UZAK BÜYÜTME", "MERCEK AYARI", "BOYUN ASKISI", "YABANİ HAYAT GÖZLEMİ", "GÖKYÜZÜ İNCELEMESİ"] },
{ main: "ASTRONOMİ KULÜBÜ", forbidden: ["GECE GÖZLEMİ", "TELESKOP PAYLAŞIMI", "YILDIZ HARİTASI", "TAKVİM PLANLAMASI", "ETKİNLİK TOPLANTISI"] },
{ main: "MOTOSİKLET KASKI", forbidden: ["ÇENE KORUMASI", "VİZÖR KALKIŞI", "ÇENE KAYIŞI", "DARBE EMME PEDİ", "BAŞ ÖLÇÜSÜ"] },
{ main: "KANO", forbidden: ["DAR GÖVDE", "ÇİFT TARAFLI KÜREK", "AKINTI HATTI", "CAN YELEĞİ ZORUNLULUĞU", "NEHİR PARKURU"] },
{ main: "TUZLUK", forbidden: ["DELİKLİ KAPAK", "YEMEK MASASI ORTASI", "İKİLİ TAKIM", "BİBERLİK EŞLİĞİ", "CAM GÖVDE"] },
{ main: "GÖRSEL SANATLAR ATÖLYESİ", forbidden: ["BOYA PALETİ", "EASEL DURAĞI", "KURUTMA RAFI", "KARMA TEKNİK", "ATÖLYE ÖĞRENCİSİ"] },
{ main: "TRAMBOLİN", forbidden: ["GERGİN BEZ YÜZEY", "KORUYUCU KENAR", "ZIPLAMA HALKASI", "DENGE KAYBI", "EĞLENCE PARKI"] },
{ main: "GÖKDELEN", forbidden: ["ÇELİK İSKELET", "ASANSÖR KOVUĞU", "PANORAMİK CAM", "ÇATI TERASI", "OFİS KATMANI"] },
{ main: "ŞELALE", forbidden: ["YÜKSEKTEN DÜŞÜŞ", "KÖPÜKLÜ SU PERDESİ", "SEYİR TERASI", "NEMLİ KAYALIK", "DOĞAL HAVUZ"] },
{ main: "YOGA MİNDERI", forbidden: ["KAYMAZ TABAN", "RAHAT POZİSYON", "ESNEME SEANSI", "NEFES ÇALIŞMASI", "HAFİF MALZEME"] },
{ main: "PİLATES TOPU", forbidden: ["DENGE HAREKETİ", "MERKEZ KASLAR", "EVDEN ÇALIŞMA SETİ", "ESNEME ÇALIŞMASI", "LASTİK POMPASI"] },
{ main: "PİKAP", forbidden: ["DÖNER TABLA", "İĞNE KOLU", "PLAĞIN ORTASI", "ANALOG SES", "KAPAK KORUMASI"] },
{ main: "UYKU TULUMU", forbidden: ["FERMUARLI KAPANIŞ", "ISI YALITIMI", "KAMP ZEMİNİ", "BAŞLIK KISMI", "TAŞIMA KILIFI"] },
{ main: "ÇADIR", forbidden: ["GERGİN İSKELET", "TENTE KUMAŞI", "KAZIK SABİTLEME", "GİRİŞ FERMUARI", "YATAK MATI"] },
{ main: "AKILLI TAHTA", forbidden: ["DOKUNMATİK YÜZEY", "PROJEKSİYON GÖRÜNTÜSÜ", "DERS NOTU KAYDI", "KALEM SENSÖRÜ", "USB BAĞLANTISI"] },
{ main: "PROJEKSİYON CİHAZI", forbidden: ["LENS ODAĞI", "PERDE YANSIMASI", "KARANLIK ODA", "GİRİŞ KAYNAĞI", "UZAKTAN KUMANDA"] },
{ main: "SANDVİÇ", forbidden: ["DİLİMLİ EKMEK", "ARASI MALZEME", "SABAH MOLASI", "PRATİK ÖĞÜN", "SALATA YAPRAĞI"] },
{ main: "MAKARON", forbidden: ["RENKLİ KABUK", "KREM DOLGU", "ŞIK KUTU", "PASTANE VİTRİNİ", "MİNİ TATLI"] },
{ main: "DRONE", forbidden: ["HAVA ÇEKİMİ", "UZAKTAN KONTROL", "PERVANE SESİ", "BATARYA YÜZDESİ", "UÇUŞ ROTASI"] },
{ main: "SELFIE ÇUBUĞU", forbidden: ["UZAYAN METAL KOL", "TELEFON SABİTLEME", "GRUP FOTOĞRAFI", "BLUETOOTH TETİĞİ", "GEZİ ANISI"] },
{ main: "PODCAST", forbidden: ["SES YAYINI", "BÖLÜM LİSTESİ", "ABONELİK TUŞU", "KULAKLIKLA DİNLEME", "SUNUCU SOHBETİ"] },
{ main: "BLOG", forbidden: ["GÜNLÜK YAZISI", "YORUM BÖLÜMÜ", "OKUR KİTLESİ", "BAŞLIK ŞABLONU", "İÇERİK ÜRETİCİSİ"] },
{ main: "ÇİZİM TABLETİ", forbidden: ["DİJİTAL KALEM", "BASINÇ HASSASİYETİ", "GRAFİK PROGRAMI", "USB BAĞLANTISI", "KISA YOL TUŞU"] },
{ main: "KARE KOD", forbidden: ["KARELİ DESEN", "TELEFON KAMERASI", "HIZLI ERİŞİM LİNKİ", "MENÜ OKUTMA", "BİLGİ BLOĞU"] },
{ main: "KARGO ŞUBESİ", forbidden: ["TAKİP NUMARASI", "TESLİM İMZASI", "KOLİ İSTİFİ", "DAĞITIM ARACI", "ŞUBE SIRASI"] },
{ main: "DÜNYA TURU", forbidden: ["UZUN SEYAHAT PLANI", "FARKLI KITA DURAĞI", "UÇUŞ AKIŞI", "VALİZ ETİKETİ", "KONAKLAMA DEFTERİ"] },
{ main: "YELKENLİ", forbidden: ["RÜZGAR YÖNÜ", "BAYRAK DİREĞİ", "GÜVERTE HALATI", "DENEYİMLİ KAPTAN", "LİMAN ÇIKIŞI"] },
{ main: "UÇURTMA", forbidden: ["İP SARMA MAKARASI", "RÜZGARLI TEPE", "RENKLİ KUYRUK", "GÖKYÜZÜNDE SALINMA", "KOŞARAK YÜKSELME"] },
{ main: "KORİDOR", forbidden: ["DAR GEÇİT", "ODA KAPILARI", "DUVAR AYDINLATMASI", "ZEMİN ÇİZGİSİ", "KOŞMA YASAĞI"] },
{ main: "ASANSÖR", forbidden: ["KABİN KAPISI", "KAT GÖSTERGESİ", "BUTON PANELİ", "AĞIRLIK DENGESİ", "ACİL DURDURMA"] },
{ main: "PERGOLA", forbidden: ["BAHÇE GÖLGELİĞİ", "AHŞAP KİRİŞ", "SARMAŞIK SÜSÜ", "TERAS DÜZENİ", "AÇIK HAVA OTURUŞU"] },
{ main: "TERARYUM", forbidden: ["MİNİ BİTKİ DÜNYASI", "CAM KAP ORTAMI", "TOPRAK KATLARI", "DEKORATİF TAŞLAR", "KAKTÜS YERLEŞİMİ"] },
{ main: "ZAMAN KAPSÜLÜ", forbidden: ["GELECEĞE MESAJ", "TOPRAĞA GÖMME", "TARİH NOTU", "HATIRA NESNELERİ", "AÇMA TARİHİ"] },
{ main: "İSKELE", forbidden: ["DENİZ KENARI TAHTASI", "TEKNELERE RÖMORKAJ", "BAĞLAMA HALATI", "KORKULUK ÇİZGİSİ", "YÜRÜME YOLU"] },
{ main: "AKROBAT", forbidden: ["HAVA NUMARASI", "ESNEKLİK GÖSTERİSİ", "SİRKE PLATFORMU", "DENGE HALATI", "SEYİRCİ ALKIŞI"] },
{ main: "KUKLA", forbidden: ["İPLİ MEKANİZMA", "PARAVAN ARKASI", "SAHNE OYUNU", "ANLATAN SES", "ÇOCUK SEANSI"] },
{ main: "MASAL KASETİ", forbidden: ["SES KAYDI HİKAYESİ", "GECE DİNLEME", "ANLATAN ANİMASYON", "KAPAK RESMİ", "ODAKLANMA ZAMANI"] },
{ main: "PİZZERİA", forbidden: ["TAŞ FIRIN TEZGAHI", "MENÜ LİSTESİ", "TESLİMAT KUTUSU", "PAYLAŞIM DİLİMİ", "SALON MASASI"] },
{ main: "SÜRDÜRÜLEBİLİRLİK RAPORU", forbidden: ["KARBON AYAK İZİ", "ENERJİ TABLOSU", "GERİ DÖNÜŞÜM HEDEFİ", "YILLIK BİLDİRİM", "İZLEME GÖSTERGESİ"] },
{ main: "GÖZ BANDI", forbidden: ["KARANLIK ORTAM", "UYKU YARDIMCISI", "ESNEK LASTİK", "GECE UÇUŞU", "IŞIK ENGELLEYİCİ"] },
{ main: "PERGEL", forbidden: ["DAİRE ÇİZİM ARACI", "UÇ METAL UÇLAR", "AÇI AYARI", "DEFTER ÜSTÜNDE", "TEKNİK RESİM"] },
{ main: "KARTPOSTAL", forbidden: ["ARKA YÜZ YAZISI", "PUL ALANI", "ŞEHİR MANZARASI", "HATIRA GÖNDERİSİ", "KISA NOT"] },
{ main: "ŞARAP MAHZENİ", forbidden: ["SERİN ORTAM", "RAF DİZİLİMİ", "ŞİŞE ETİKETİ", "KAPALI KAPI", "TADIM NOTU"] },
{ main: "BUHARLI ÜTÜ", forbidden: ["SU HAZNESİ", "TABAN PLAKASI", "KABLO SARIMI", "KIRIIŞIK GİDERME", "ISINMA GÖSTERGESİ"] },
{ main: "KRONOMETRE", forbidden: ["BAŞLAT TUŞU", "DURDUR KAYDI", "SÜRE TUTMA", "SPOR YARIŞI", "ELDE TAŞIMA"] },
{ main: "PİYANO", forbidden: ["TUŞ DİZİLİMİ", "PEDAL KULLANIMI", "NOTA DEFTERİ", "KAPAK AÇILIŞI", "SALON ÇALIŞMASI"] },
{ main: "BATERİ", forbidden: ["TRAMPET SESİ", "ZİL VURUŞU", "PEDAL BASIŞI", "RİTİM EGZERSİZİ", "SAHNE ARKASI"] },
{ main: "BLENDER", forbidden: ["BİÇAK MEKANİZMASI", "KAPAK KİLİDİ", "KARIŞTIRMA KABI", "PRİZ BAĞLANTISI", "MUTFAK TEZGAHI"] },
{ main: "TERMOMETRE", forbidden: ["ISI GÖSTERGESİ", "KIRMIZI ÇUBUK", "KADAR ÖLÇÜMÜ", "DUVAR ASKISI", "GÖSTERGE SKALASI"] },
{ main: "TUVAL", forbidden: ["GERİLMİŞ BEZ", "AHŞAP ŞASE", "AKRİLİK BOYA", "ÇERÇEVE HAZIRLIĞI", "FIRÇA İZİ"] },
{ main: "REÇEL KAVANOZU", forbidden: ["CAM HAZNE", "ETİKET TARİHİ", "METAL KAPAK", "KAHVALTI RAFLARI", "MEYVE PARÇALARI"] },
{ main: "SPREY BOYA", forbidden: ["BASINÇLI KUTU", "GRAFİK ÇALIŞMASI", "MASKE KULLANIMI", "DUVAR YÜZEYİ", "KISA PÜSKÜRTME"] },
{ main: "BAVUL", forbidden: ["ÇEKÇEK KOLU", "TEKERLİ TABAN", "ETİKET SAPI", "BÖLMELİ İÇ KISIM", "KİLİT MEKANİZMASI"] },
{ main: "EKSEN EĞİKLİĞİ", forbidden: ["GECE GÜNDÜZ FARKI", "MEVSİM DEĞİŞİMİ", "DÜNYA MODELİ", "GÖLGE UZUNLUĞU", "EĞRİLİK AÇISI"] },
{ main: "UZAY GEMİSİ", forbidden: ["KUMANDA KOKPİTİ", "HAVA KİLİDİ", "YILDIZLAR ARASI YOL", "İTİCİ MOTORLAR", "GÖREV EKİBİ"] },
{ main: "KAYDIRAK", forbidden: ["MERDİVEN ÇIKIŞI", "PARLAK YÜZEY", "ÇOCUK PARKI", "HIZLI İNİŞ", "YER MATI"] },
{ main: "OYUN PARKI", forbidden: ["SALINCAK SIRASI", "TIRMANMA DEMİRİ", "KUM HAVUZU", "BANK OTURUMU", "AÇIK HAVA ALANI"] },
{ main: "GÜNEŞ PANELİ", forbidden: ["FOTOVOLTAİK HÜCRE", "ÇATI KURULUMU", "ENERJİ DÖNÜŞÜMÜ", "İNVERTÖR CİHAZI", "GÜÇ TABLOSU"] },
{ main: "RÜZGAR TÜRBİNİ", forbidden: ["DÖNEN KANAT", "KULE YÜKSEKLİĞİ", "ELEKTRİK ÜRETİMİ", "SAHA YERLEŞİMİ", "SES SEVİYESİ"] },
{ main: "ELEKTRİKLİ SKUTER", forbidden: ["ŞARJ SOKETİ", "KATLANIR GÖVDE", "HIZ SEVİYESİ", "EL FRENİ", "ŞEHİR İÇİ ULAŞIM"] },
{ main: "AKILLI SAAT", forbidden: ["BİLEK BANTI", "ADIM SAYACI", "NABIZ TAKİBİ", "BİLDİRİM UYARISI", "ŞARJ MANYETİĞİ"] },
{ main: "GÖRSEL ROMAN", forbidden: ["İLÜSTRASYON SAYFASI", "KARAKTER TASARIMI", "SAYFA GEÇİŞİ", "DİYALOG PANELİ", "SANATSAL ANLATIM"] },
{ main: "BULUT DEPOLAMA", forbidden: ["ÇEVRİMİÇİ DOSYA", "SENKRONİZASYON KLASÖRÜ", "PAYLAŞIM LİNKİ", "YEDEKLEME PLANI", "HESAP KOTASI"] },
{ main: "SANAL GERÇEKLİK GÖZLÜĞÜ", forbidden: ["3B ORTAM", "BAŞ HAREKETİ TAKİBİ", "KONTROL CİHAZLARI", "OYUN DENEYİMİ", "MERCEK AYARI"] },
{ main: "UZAKTAN EĞİTİM PLATFORMU", forbidden: ["CANLI DERS EKRANI", "KATILIM KAMERASI", "DİJİTAL ÖDEV TESLİMİ", "KURS LİSTESİ", "KAYITLI VİDEO"] },
{ main: "ŞİFRE YÖNETİCİSİ", forbidden: ["GÜVENLİ KASA", "TEK TIK GİRİŞİ", "ANA PAROLA", "RASGELE OLUŞTURUCU", "CİHAZ SENKRONU"] },
{ main: "VERİTABANI SUNUCUSU", forbidden: ["TABLO SORUSU", "SORGULAMA DİZGESİ", "YEDEKLEME STRATEJİSİ", "ERİŞİM YETKİSİ", "KAYIT BÜTÜNLÜĞÜ"] },
{ main: "YAPAY ZEKA ASİSTANI", forbidden: ["DİL MODELİ", "SORU CEVAP ARAYÜZÜ", "ÖĞRENME VERİSİ", "KOMUT YORUMLAMA", "SOHBET PENCERESİ"] },
{ main: "KRİPTO CÜZDANI", forbidden: ["DİJİTAL ANAHTAR", "BLOK ZİNCİR AĞI", "TRANSFER ADRESİ", "GÜVENLİ SAKLAMA", "QR KOD EKRANI"] },
{ main: "UZAY İSTASYONU", forbidden: ["YÖRÜNGE MODÜLÜ", "ASTRONOT EKİBİ", "GÜNEŞ PANELİ", "HAVALANDIRMA SİSTEMİ", "DENEY BÖLÜMÜ"] },
{ main: "DROĞERİ", forbidden: ["KOZMETİK REYONU", "KİŞİSEL BAKIM", "KASA SIRASI", "PARFÜM TESTERİ", "İNDİRİM ETİKETİ"] },
{ main: "BİYOMETRİK OKUYUCU", forbidden: ["PARMAK İZİ", "YÜZ TARAMA", "GÜVENLİK GİRİŞİ", "KİMLİK DOĞRULAMA", "KAPI KİLİDİ"] },
{ main: "SES YALITIMI", forbidden: ["KALIN SÜNGER", "DOLGU MALZEMESİ", "EKO AZALTMA", "STÜDYO DUVARI", "PENCERE İZOLASYONU"] },
{ main: "YANGIN MERDİVENİ", forbidden: ["ACİL ÇIKIŞ", "METAL BASAMAK", "BİNA DIŞ CEPHESİ", "KAÇIŞ ROTASI", "GÜVENLİK PLANI"] },
{ main: "TAŞ FIRIN", forbidden: ["YÜKSEK ISI", "PİŞİRME YÜZEYİ", "ODUN HAZNESİ", "KÖY KOKUSU", "KABARAN HAMUR"] },
{ main: "BİYOLOJİ LABORATUVARI", forbidden: ["MİKROSKOP MASASI", "HÜCRE PREPARATI", "DENEY DÜZENEĞİ", "SOĞUK DOLAP", "KORUYUCU ELDİVEN"] },
{ main: "KARDEŞ PAYI", forbidden: ["EŞİT BÖLÜŞME", "KÜÇÜK PARÇA", "TABAK ARASINDA", "GÖNÜL ALMAK", "SIRAYLA DAĞITMA"] },
{ main: "FİLM ARŞİVİ", forbidden: ["DVD RAFI", "AFİŞ KAPAĞI", "TÜR SINIFLAMASI", "NUMARALI KUTU", "KATALOG LİSTESİ"] },
{ main: "KAYIT CİHAZI", forbidden: ["MİKROFON GİRİŞİ", "HAFIZA BİRİMİ", "KAYDET TUŞU", "GERİ DİNLEME", "ZAMAN KODU"] },
{ main: "GECE LAMBASI", forbidden: ["LOŞ AYDINLATMA", "PRİZ BAĞLANTISI", "ÇOCUK ODASI", "YUMUŞAK IŞIK", "UYKU ÖNCESİ"] },
{ main: "KAMPÜS KARTI", forbidden: ["KİMLİK FOTOĞRAFI", "GİRİŞ TURNİKESİ", "YEMEKHANE SIRASI", "KÜTÜPHANE KAYDI", "BAKİYE YÜKLEME"] },
{ main: "HEDİYE PAKETİ", forbidden: ["RENKLİ KÂĞIT", "KURDELE BAĞI", "SÜRPRİZ İÇERİK", "ETİKET NOTU", "ÖZEL GÜN"] },
{ main: "BULUŞ NOKTASI", forbidden: ["RANDEVU SAATİ", "ORTAK ADIM", "HARİTA İŞARETİ", "MESAJLAŞMA", "BEKLEME ALANI"] },
{ main: "BUHAR MAKİNESİ", forbidden: ["SU DEPOSU", "YOĞUNLAŞAN TANE", "KUMAŞ AÇMAK", "ORTAM NEMİ", "KAPAĞI AÇMAK"] },
{ main: "KUMANDA KOLTUĞU", forbidden: ["TEK KİŞİLİK OTURMA", "YAN CEP", "KUMANDA SAKLAMA", "TV KARŞISI", "RAHAT KUMAŞ"] },
{ main: "AKUSTİK GİTAR", forbidden: ["TELLİ GÖVDE", "SES DELİĞİ", "PERDE ARASI", "AKORT KOLU", "RİTİM VURUŞU"] },
{ main: "BULUŞMA UYGULAMASI", forbidden: ["PROFİL FOTOĞRAFI", "EŞLEŞME EKRANI", "MESAJ GÖNDERME", "BİLDİRİM SESİ", "KONUM FİLTRESİ"] },
{ main: "GÜNEŞ GÖZLÜĞÜ", forbidden: ["KARARTILMIŞ CAM", "ULTRAVİYOLE FİLTRESİ", "METAL SAP", "YAZ AKSESUARI", "GÖZ KORUMAK"] },
{ main: "ELEKTRONİK İMZA", forbidden: ["SERTİFİKA DOSYASI", "DİJİTAL ONAY", "GÜVENLİ GİRİŞ", "ŞİFRELİ ANAHTAR", "RESMİ BELGE"] },
{ main: "YÜK ASANSÖRÜ", forbidden: ["GENİŞ KABİN", "TAŞIMA PLATFORMU", "AĞIR MALZEME", "SANAYİ BİNASI", "KAPASİTE PLAKASI"] },
{ main: "MEŞALE", forbidden: ["TUTMA SAPI", "ALEV BAŞI", "GECE YÜRÜYÜŞÜ", "TÖREN YÜRÜYÜŞÜ", "ATEŞ TAŞIMAK"] },
{ main: "SÜTLAÇ", forbidden: ["TOPRAK KASE", "ÜSTÜ KIZARMIŞ", "TARÇIN SERPİNTİSİ", "SÜTLÜ TATLI", "FIRIN TEPSİSİ"] },
{ main: "EKMEK MAKİNESİ", forbidden: ["PROGRAM SEÇİMİ", "HAMUR KANCASI", "PİŞİRME KABI", "KAPAĞI ŞEFFAF", "KOKU YAYILMASI"] },
{ main: "OZON TABAKASI", forbidden: ["ATMOSFER TABAKASI", "GÜNEŞ RADYASYONU", "KORUYUCU BALON", "DELİK OLUŞUMU", "İKLİM ETKİSİ"] },
{ main: "GÖL EVİ", forbidden: ["SU KIYISI", "AHŞAP İSKELE", "SALINCAK SANDALYE", "HAFTA SONU KAÇAMAĞI", "GÜNEŞ BATIMI"] },
{ main: "MÜLAKAT ODASI", forbidden: ["MASA KARŞILIĞI", "SORU CEVAP", "ÖZGEÇMİŞ DOSYASI", "RESMİ GÖRÜŞME", "NOT ALMAK"] },
{ main: "KİŞİSEL AJANS", forbidden: ["CAST KAYDI", "PORTFÖY DOSYASI", "BAŞVURU FORMU", "SEÇME GÖRÜŞMESİ", "REFERANS MEKTUBU"] },
{ main: "KARANLIK ODA", forbidden: ["FOTOĞRAF BANYOSU", "KIRMIZI LAMBA", "KİMYASAL TEPSİ", "NEGATİF ŞERİT", "KURUTMA TELİ"] },
{ main: "SİSTEM ODASI", forbidden: ["SUNUCU DOLABI", "SOĞUTMA CİHAZI", "KABLO DEMETİ", "ERİŞİM KISITI", "YEDEK GÜÇ"] },
{ main: "AKUSTİK PANEL", forbidden: ["DUVAR KAPLAMASI", "SES EMİCİ", "STÜDYO DÜZENİ", "VİDALAMA YÖNTEMİ", "KUMAŞ YÜZEY"] },
{ main: "KAYNAK MAKİNESİ", forbidden: ["KORUYUCU MASKE", "KIVILCIM YAĞMURU", "METAL BİRLEŞTİRME", "TOPRAKLAMA KABLOSU", "AKIM AYARI"] },
{ main: "SERVİS ARACI", forbidden: ["BELİRLİ GÜZERGÂH", "TOPLAMA NOKTASI", "KART OKUTMA", "VARIŞ SAATİ", "ÇIKIŞ KAPLARI"] },
{ main: "KONTEYNER LİMANI", forbidden: ["VİNÇ OPERASYONU", "YÜK İSTİFİ", "GEMİ RAMPASI", "GÜMRÜK ALANI", "TAKİP NUMARASI"] },
{ main: "DİJİTAL PANİK BUTONU", forbidden: ["ACİL UYARI", "SİNYAL GÖNDERİMİ", "MOBİL BİLDİRİM", "GÜVENLİK MERKEZİ", "TEK DOKUNUŞ"] },
{ main: "GÖZ HASSASİYETİ", forbidden: ["PARLAK EKRAN", "KURULUK HİSSİ", "UZUN SÜRE BAKMAK", "DAMLA KULLANMAK", "GÖRÜŞ YORGUNLUĞU"] },
{ main: "ŞARJ İSTASYONU", forbidden: ["KABLO GİRİŞİ", "PRİZ BLOĞU", "AYAKTA BEKLEMEK", "AKILLI CİHAZ", "YÜZDE TAKİBİ"] },
{ main: "MASAÜSTÜ ORGANİZER", forbidden: ["KALEM GÖZÜ", "NOT KAĞIDI BÖLMESİ", "KLİPS ALANI", "DÜZENLİ GÖRÜNTÜ", "OFİS EŞYASI"] },
{ main: "AKUSTİK KONSER", forbidden: ["SADE DÜZEN", "DOĞAL SES", "KÜÇÜK SAHNE", "DİNLEYİCİ YAKINLIĞI", "ENSTRÜMAN ÇIPLAKLIĞI"] },
{ main: "SERA GAZI", forbidden: ["ATMOSFER ETKİSİ", "ISINMA SÜRECİ", "SANAYİ KAYNAĞI", "YOĞUŞMA DENGESİ", "İKLİM RAPORU"] },
{ main: "BİSİKLET YOLU", forbidden: ["BOYALI ŞERİT", "KALDIRIM KENARI", "ÖZEL İŞARET", "PEDAL HATTI", "ŞEHİR İÇİ ROTA"] },
{ main: "AKILLI TAHTA KALEMİ", forbidden: ["SENSÖR UCU", "DOKUNMA TEPKİSİ", "EKRAN YAZISI", "RENK SEÇİMİ", "SİLME FONKSİYONU"] },
{ main: "KİTAP KULÜBÜ", forbidden: ["ORTAK OKUMA", "AYLIK LİSTE", "TARTIŞMA TOPLANTISI", "YAZAR ÖNERİSİ", "NOTLAR PAYLAŞMA"] },
{ main: "DİZİ ÜYELİĞİ", forbidden: ["AYLIK ÖDEME", "BÖLÜM MARATONU", "LİSTEYE EKLEME", "ALT YAZI SEÇENEKLERİ", "HESAP PAYLAŞIMI"] },
{ main: "TARİHİ HAN", forbidden: ["KEMERLİ GİRİŞ", "AVLU ORTASI", "ESNAF DÜKKÂNI", "TAŞ DUVAR", "GÖLGE OTURMA"] },
{ main: "MÜZAYEDE SALONU", forbidden: ["SIRAYLA TEKLİF", "ÇEKİÇ VURUŞU", "ESER TANITIMI", "NUMARA LEVHASI", "KATALOG SAYFASI"] },
{ main: "KİŞİSEL GELİŞİM KİTABI", forbidden: ["MOTİVASYON BAŞLIĞI", "ALINTI CÜMLELER", "HEDEF LİSTESİ", "ALIŞKANLIK ÖNERİSİ", "OKUR NOTLARI"] },
{ main: "GÖNÜLLÜ KULÜP", forbidden: ["ETKİNLİK PLANLAMASI", "YARDIM TOPLANTISI", "ÜYE LİSTESİ", "AFİŞ HAZIRLAMAK", "BİLGİLENDİRME MASASI"] },
{ main: "SES MİKSERİ", forbidden: ["KANAL AYARI", "SEVİYE ÇUBUĞU", "KULAKLIK ÇIKIŞI", "EFECT EKLEME", "KAYIT MASASI"] },
{ main: "AÇIK OFİS", forbidden: ["BÖLÜCÜ PANEL", "ORTAK MASA", "TOPLANTI KÖŞESİ", "SES DÜZEYİ", "ORTAK MUTFAK"] },
{ main: "KABLO KANALI", forbidden: ["ZEMİN ŞERİDİ", "GİZLİ GEÇİŞ", "TOPLU TAŞIMA", "TAKVİYE KAPAĞI", "KARIŞIKLIĞI AZALTMA"] },
{ main: "YÜRÜYÜŞ PARKURU", forbidden: ["UZUN HAT", "YOL ÇİZGİSİ", "MESAFE TABELASI", "AĞAÇ GÖLGESİ", "SAĞLIK HEDEFİ"] },
{ main: "ÜRETİM BANDI", forbidden: ["SIRALI İSTASYON", "KONVEYÖR HATTI", "KONTROL NOKTASI", "KOLİLEME BÖLÜMÜ", "VARDİYA DEĞİŞİMİ"] },
{ main: "DİL LABORATUVARI", forbidden: ["KULAKLIK SIRASI", "SES KAYDI", "ÖRNEK METİN", "TEKRAR ÇALIŞMASI", "ÖĞRENCİ KABİNİ"] },
{ main: "KAPI ZİLİ", forbidden: ["BASMA DÜĞMESİ", "SES TONU", "HOL YANKISI", "MİSAFİR GELİŞİ", "GÖRÜNTÜLÜ SİSTEM"] },
{ main: "BİLGİ PANOSU", forbidden: ["DUVAR İLANI", "NOT KAĞIDI", "DUYURU SAYFASI", "TOPLANTI SAATİ", "ŞEMA ASMAK"] },
{ main: "GECE NÖBETİ", forbidden: ["VARDİYA ÇİZELGESİ", "UYGULAMA SIRASI", "UYKUSUZLUK HİSSİ", "SABAH TESLİMİ", "GÖZ DEVİRMEK"] },
{ main: "ÖZGEÇMİŞ", forbidden: ["KİŞİSEL BİLGİLER", "DENEYİM LİSTESİ", "EĞİTİM BAŞLIĞI", "REFERANS KISMI", "İLETİŞİM SATIRI"] },
{ main: "MÜHENDİSLİK PROJESİ", forbidden: ["ÇİZİM DOSYASI", "HESAP TABLOSU", "MALZEME LİSTESİ", "BÜTÇE PLANI", "ONAY İMZASI"] },
{ main: "GÖZ TAKİP SİSTEMİ", forbidden: ["KAMERA SENSÖRÜ", "BAKIŞ ANALİZİ", "EKRAN HAREKETİ", "HARİTA ÇIKTISI", "DENEY KATILIMCISI"] },
{ main: "YÜKSEK LİSANS", forbidden: ["DERS PROGRAMI", "TEZ KONUSU", "DANIŞMAN GÖRÜŞMESİ", "SUNUM HAZIRLIĞI", "JÜRİ TOPLANTISI"] },
{ main: "İZLEME LİSTESİ", forbidden: ["FİLM BAŞLIĞI", "SEYRETME SIRASI", "NOT DÜŞMEK", "ARŞİVLEMEK", "KATEGORİLERE AYIRMAK"] },
{ main: "VAGON", forbidden: ["RAY ÜZERİ", "KAPI TUTACAĞI", "CAM KENARI", "BİLET NUMARASI", "YOLCU KISMI"] },
{ main: "KULİS", forbidden: ["SAHNE ARKASI", "MAKYAJ MASASI", "DEKOR PARÇALARI", "HAZIRLANMA ALANI", "MİKROFON KONTROLÜ"] },
{ main: "SOKAK LAMBASI", forbidden: ["YOL AYDINLATMA", "YÜKSEK DİREK", "GECE GÜVENLİĞİ", "ZAMAN SAATİ", "LED ARMATÜR"] },
{ main: "ÇEVRE RAPORU", forbidden: ["ATIK ANALİZİ", "EMİSYON TABLOSU", "GÖZLEM NOTU", "İYİLEŞTİRME ADIMI", "YILLIK DEĞERLENDİRME"] },
{ main: "OTOMATİK KAPI", forbidden: ["SENSÖR HAREKETİ", "FOTOSELLİ GEÇİŞ", "KENDİLİĞİNDEN AÇILMA", "GİRİŞ PANELİ", "GÜVENLİK KONTROLÜ"] },
{ main: "KALABALIK MEYDAN", forbidden: ["TOPLANTI NOKTASI", "AÇIK HAVA ALANI", "KUŞ BESLEMEK", "GÖSTERİ SAHNESİ", "BULUŞMA MERKEZİ"] },
{ main: "KİTAP AYRACI", forbidden: ["SAYFA ARASI", "RENKLİ ŞERİT", "UNUTMAMA ARACI", "KÖŞE BELİRLEYİCİ", "HEDİYELİK NESNE"] },
{ main: "KURUMSAL MAİL", forbidden: ["RESMİ ADRES", "İMZA ŞABLONU", "DAĞITIM LİSTESİ", "EK DOSYA", "KONU SATIRI"] },
{ main: "ZİYARETÇİ KARTI", forbidden: ["GEÇİCİ GİRİŞ", "GÜVENLİK DEFTERİ", "TESLİM EDERKEN", "İMZA SATIRI", "KAPI KONTROLÜ"] },
{ main: "FERMUARLI ÇANTA", forbidden: ["AĞIZ BÖLÜMÜ", "KAPAMA DİŞLERİ", "İÇ CEP", "ASKI KEMERİ", "GÜNLÜK TAŞIMA"] },
{ main: "DENİZ FENERİ", forbidden: ["KIYI KAYALIĞI", "DÖNEN IŞIK", "GECE SEYRİ", "GÜÇLÜ LAMBA", "GEMİ UYARISI"] },
{ main: "GÜNDÜZ RÜYASI", forbidden: ["DALIP GİTMEK", "HAYAL DÜNYASI", "AKILDA CANLANMA", "GERÇEKLE KARIŞMAK", "İÇ SES"] },
{ main: "KULAKLIK AMFİSİ", forbidden: ["SES GÜÇLENDİRME", "ÇIKIŞ DENGESİ", "SES TONU AYARI", "MİX MASASI", "DİNLENME KALİTESİ"] },
{ main: "BAĞIMSIZ FİLM", forbidden: ["KISITLI BÜTÇE", "FESTİVAL GÖSTERİMİ", "YÖNETMEN PROJESİ", "SANATSAL ANLATIM", "ALTERNATİF SALON"] },
{ main: "TARLA YOLU", forbidden: ["TOPRAK PATİKA", "YAN TARAF EKİN", "GÜNEŞTE TOZ", "KÖY TRAKTÖRÜ", "UZAK EVLER"] },
{ main: "BİLİM KURGU ROMANI", forbidden: ["GELECEK TASVİRİ", "UZAY MEKANI", "TEKNOLOJİK ÖĞE", "KAHRAMAN YOLCULUĞU", "ALTERNATİF EVREN"] },
{ main: "TARİH ÖZETİ", forbidden: ["KRONOLOJİK SIRA", "OLAY BAŞLIĞI", "KISA NOT", "DÖNEM BÖLÜMÜ", "SINAV ÖNCESİ"] },
{ main: "BULUŞÇU", forbidden: ["YENİ FİKİR", "DENEY YAPMAK", "MODEL ÜRETMEK", "PATENT BAŞVURUSU", "ÇÖZÜM ARAYIŞI"] },
{ main: "KAMU SPOTU", forbidden: ["KISA VİDEO", "UYARI MESAJI", "TOPLUMSAL FAYDA", "TELEVİZYON YAYINI", "SES EFEKTİ"] },
{ main: "GÖNÜL KÖPRÜSÜ", forbidden: ["İLİŞKİ KURMAK", "MESAFEYE RAĞMEN", "ANLAYIŞ GELİŞTİRME", "SÖZSÜZ BAĞ", "DESTEK OLMAK"] },
{ main: "KARDEŞ ŞEHİR", forbidden: ["PROTOKOL İMZASI", "KÜLTÜR ALIŞVERİŞİ", "HEYET ZİYARETİ", "ORTAK PROJE", "KARDEŞLİK LEVHASı"] },
{ main: "PROVA SALONU", forbidden: ["TEKRAR ÇALIŞMASI", "AYNA KARŞISI", "MÜZİK EKİPMANI", "SES DÜZENİ", "GÖSTERİ ÖNCESİ"] },
{ main: "GÜN BATIMI TERASI", forbidden: ["UFUK ÇİZGİSİ", "RENKLİ GÖKYÜZÜ", "SEYİR KÖŞESİ", "FOTOĞRAF ANİ", "OTURMA ALANI"] },
{ main: "DİKİŞ MAKİNESİ", forbidden: ["PEDAL HANI", "İĞNE HAREKETİ", "İPLİK GERGİSİ", "MASA ÜSTÜ", "KUMAŞ YÖNLENDİRME"] },
{ main: "E-OKUL", forbidden: ["NOT SİSTEMİ", "DEVAMSIZLIK SATIRI", "VELİ GİRİŞİ", "DERS PROGRAMI", "DUYURU EKRANI"] },
{ main: "SİBER GÜVENLİK", forbidden: ["GÜÇLÜ ŞİFRE", "DUVAR KORUMASI", "VERİ SIZINTISI", "SALDIRI ÖNLEME", "AĞ İZLEME"] },
{ main: "DİJİTAL CÜZDAN", forbidden: ["TEMASSIZ ÖDEME", "QR KOD OKUTMA", "KART EKLEME", "BAKİYE TAKİBİ", "HESAP HAREKETİ"] },
{ main: "PENCERE ÖNÜ", forbidden: ["SAXSIDA BİTKİ", "PERDE KENARI", "GÜNEŞ GİRİŞİ", "KEDİ OTURMASI", "DIŞARIYI İZLEMEK"] },
{ main: "KOL DAYAMA", forbidden: ["OTURMA KENARI", "ARABA İÇİ", "YÜKSEKLİK AYARI", "RAHATLIK UNSURU", "SÜRÜŞ DESTEK"] },
{ main: "YEMEK ABONESİ", forbidden: ["AYLIK SİPARİŞ", "SEPET OLUŞTURMA", "TESLİMAT SAATİ", "MENÜ SEÇİMİ", "OTOMATİK ÖDEME"] },
{ main: "BİLİM ŞENLİĞİ", forbidden: ["PROJE STANDI", "ÖĞRENCİ SUNUMU", "DENEY GÖSTERİSİ", "MADALYA TÖRENİ", "ZİYARETÇİ KALABALIĞI"] },
{ main: "E-SPOR TAKIMI", forbidden: ["OYUN STRATEJİSİ", "ANTRENMAN SAATİ", "TURNUVA SUNUCUSU", "CANLI YAYIN", "SPONSOR ANLAŞMASI"] },
{ main: "SANAL FUAR", forbidden: ["ÇEVRİMİÇİ STAND", "DİJİTAL KATALOĞ", "CANLI SOHBET", "KATILIMCI LİSTESİ", "OTURUM PROGRAMI"] },
{ main: "TEZ SUNUMU", forbidden: ["SLA YF GÖSTERİMİ", "JÜRİ KARŞISI", "SORU CEVAP", "SÜRE SINIRI", "DEĞERLENDİRME FORMU"] },
{ main: "UZAKTAN ÇALIŞMA", forbidden: ["EV OFİS DÜZENİ", "ÇEVRİMİÇİ TOPLANTI", "ESNEK SAAT", "İNTERNET BAĞLANTISI", "GÖREV LİSTESİ"] },
{ main: "ZİHİN HARİTASI", forbidden: ["MERKEZ KAVRAM", "DALLANAN BAŞLIK", "RENKLİ KOL", "NOT ALIŞI", "FİKİR DÜZENİ"] },
{ main: "TATİL KÖYÜ", forbidden: ["AÇIK BÜFE", "AKTİVİTE PROGRAMI", "HAVUZ BAŞI", "BİLEKLİK SİSTEMİ", "KONAKLAMA BLOĞU"] },
{ main: "SES KİTABI", forbidden: ["ANLATAN SES", "KULAKLIKLA DİNLEME", "UYGULAMA ARAYÜZÜ", "BÖLÜM SEÇİMİ", "HİKÂYE AKIŞI"] },
{ main: "TARİH KANALI", forbidden: ["BELGESEL DİZİSİ", "ESKİ KAYIT", "ARŞİV GÖRÜNTÜSÜ", "UZMAN YORUMU", "PROGRAM AKIŞI"] },
{ main: "GÖLGE OYUNU", forbidden: ["PERDE ARKASI", "EL HAREKETİ", "LAMBAYLA OLUŞMAK", "FİGÜR KARAKTER", "ÇOCUK EĞLENCESİ"] },
{ main: "KENT ORMANI", forbidden: ["YÜRÜYÜŞ YOLU", "PİKNİK ALANI", "SEYİR KULESİ", "BELİRLİ GÜZERGÂH", "TABİAT İZİ"] },
{ main: "KAYIT FORMU", forbidden: ["AD SOYAD SATIRI", "ONAY KUTUSU", "TESLİM TARİHİ", "İMZA BÖLÜMÜ", "BİLGİ GİRİŞİ"] },
{ main: "İŞ GÖRÜŞMESİ", forbidden: ["SORU LİSTESİ", "ÖZGEÇMİŞ İNCELEME", "RESMİ KIYAFET", "KENDİNİ TANITMA", "TEKLİF SÜRECİ"] },
{ main: "GÜNEŞ SAATİ", forbidden: ["GÖLGE ÇİZGİSİ", "MERKEZ ÇUBUK", "ZEMİN İŞARETİ", "GÜNEŞ KONUMU", "ZAMAN OKUMA"] },
{ main: "YÜRÜYÜŞ UYGULAMASI", forbidden: ["ADIM SAYIMI", "KALORİ HESABI", "HARİTA TAKİBİ", "GÜNLÜK HEDEF", "BİLDİRİM MOTİVASYONU"] },
{ main: "KAYAK MERKEZİ", forbidden: ["TELESİYEJ", "PİST HARİTASI", "KAR KASKI", "DAĞ EVİ", "SEZON AÇILIŞI"] },
{ main: "LAVANTA TARLASI", forbidden: ["MOR ŞERİT", "KOKU BULUTU", "FOTOĞRAF TURU", "HASAT DEMETİ", "AROMA ŞİŞESİ"] },
{ main: "E-KİTAP OKUYUCU", forbidden: ["EKRAN MÜREKKEBİ", "KAPAK KILIFI", "KİTAP ARŞİVİ", "SAYFA ÇEVİRME", "PARLAKLIK AYARI"] },
{ main: "ÇAY SERPMESİ", forbidden: ["İNCE DEMLİK", "BARDAK DİZİMİ", "İKRAM TEPSİSİ", "SOHBET HALKASI", "ŞEKER KÂSESİ"] },
{ main: "KUM HEYKELİ", forbidden: ["KOVA KALIBI", "ISLAK ZEMİN", "DALGA YAKINI", "YARIŞMA JÜRİSİ", "FOTOĞRAF POZU"] },
{ main: "RÜZGAR ÇANI", forbidden: ["BALKON KÖŞESİ", "TİN TİN SES", "İP DİZİSİ", "TAHTA PARÇA", "ESİNTİ HAREKETİ"] },
{ main: "BİSİKLET KASKI", forbidden: ["ÇENE TOKASI", "HAVALANDIRMA DELİĞİ", "PEDAL ÇEVİRME", "YOL TURU", "REFLEKTÖR ŞERİT"] },
{ main: "SALINCAK", forbidden: ["ZİNCİR YANI", "ARKA İTİŞ", "PARK KÖŞESİ", "SIRT DAYAMA", "DENGE NOKTASI"] },
{ main: "KUM KALASI", forbidden: ["PLAJ OYUNU", "EL KÜREĞİ", "SU SERPMEK", "ÇÖKME TEHLİKESİ", "KÜÇÜK BAYRAK"] },
{ main: "LİMAN KAHVESİ", forbidden: ["RIZALET KOKUSU", "AHŞAP MASA", "DENİZ YANSIMASI", "MARTI SESİ", "GÜN DOĞUMU"] },
{ main: "DANTEL MASA ÖRTÜSÜ", forbidden: ["EL İŞİ", "ORTA SEHPA", "NARİN DESEN", "NİKAH FOTOĞRAFI", "ÇEYİZ SANDIĞI"] },
{ main: "KİL MASKESİ", forbidden: ["YÜZ BAKIMI", "KURUMA ÇATLAĞI", "BANYO AYNASI", "KARIŞTIRMA KABI", "DURULAMA ZAMANI"] },
{ main: "AKUSTİK DUVAR SAATİ", forbidden: ["TİK TAK SESİ", "YUVARLAK ÇERÇEVE", "SARKAÇ HAREKETİ", "SALON DUVARI", "KANCAYA ASMAK"] },
{ main: "ÇOCUK OYUN HALISI", forbidden: ["YOL DESENİ", "ARABA FİGÜRÜ", "ODANIN ORTASI", "YUMUŞAK DOKU", "OYUN KASETİ"] },
{ main: "GÖKKUŞAĞI PARÇASI", forbidden: ["YAĞMUR SONRASI", "RENK KEMERİ", "UFUK ÇİZGİSİ", "BULUT ARASI", "FOTOĞRAF MERAKLISI"] },
{ main: "KAYISI BAHÇESİ", forbidden: ["MEYVE KASASI", "AĞAÇ SIRASI", "SABAH SERİNLİĞİ", "KIRIK DAL", "SEPET DOLDURMA"] },
{ main: "CAM SÜRAHİ", forbidden: ["SOFRA ORTASI", "İNCE KULP", "ŞEFFAF GÖVDE", "İÇECEK DOLDURMA", "BUHAR DAMLASI"] },
{ main: "FENER ALAYI", forbidden: ["GECE YÜRÜYÜŞÜ", "EL MEŞALESİ", "MARŞ SESİ", "KALABALIK CADDE", "BAYRAK AKIŞI"] },
{ main: "GÖRSEL SUNUM", forbidden: ["SLAYT GEÇİŞİ", "BAŞLIK ŞABLONU", "İŞARETLEYİCİ KALEM", "SALON PROJESİ", "EKRAN YANSITMA"] },
{ main: "SAKSI STANDI", forbidden: ["KATLI RAFTIR", "BİTKİ DİZİMİ", "BALKON KÖŞESİ", "METAL GÖVDE", "SULAMA KABINI"] },
{ main: "KUMANDA RAFI", forbidden: ["KANEPENİN YANI", "TV KARŞISI", "DAR BÖLME", "DÜZEN SEVER", "KAYBOLMAYAN EŞYA"] },
{ main: "NOT DEFTERİ", forbidden: ["SPİRAL BAĞLANTI", "KARIŞIK KARALAMA", "TARİH BAŞLIĞI", "TOPLANTI NOTU", "KAPAK DESENİ"] },
{ main: "DAĞ EVİ", forbidden: ["AHŞAP CEPHE", "SOBALI ODA", "KAR MANZARASI", "DAR PATİKA", "GECELİK KONAKLAMA"] },
{ main: "RENKLİ TOPLU İĞNE", forbidden: ["KUMAŞ ÜSTÜ", "MANTAR TABLO", "KÜÇÜK KUTU", "DİZİLİ BAŞLIK", "ELBİSE DENEMESİ"] },
{ main: "ÇİZGİLİ PİJAMA", forbidden: ["EV KIYAFETİ", "GECE DÜZENİ", "LASTİKLİ BEL", "YUMUŞAK KUMAŞ", "UYKU SAATİ"] },
{ main: "MİNİ SERA KUTUSU", forbidden: ["PENCERE ÖNÜ", "FİDAN DENEMESİ", "NEMLİ ORTAM", "ŞEFFAF KAPAK", "DAMLALIK SU"] },
{ main: "BİTKİ SULAMA SAATİ", forbidden: ["CAM ŞİŞE", "TOPRAKTA BAŞ AŞAĞI", "YAVAŞ DAMLAMA", "UNUTKAN SAHİP", "KÖK SEVİYESİ"] },
{ main: "BAMBU PERDE", forbidden: ["İNCE ÇUBUK", "PENCERE ÖNÜ", "HAFİF SES", "GÜNEŞ KIRMAK", "İP BAĞLANTI"] },
{ main: "TAŞ BİLEKLİK", forbidden: ["DOĞAL RENK", "EL YAPIMI", "İP GEVŞEMESİ", "BİLEK ÖLÇÜSÜ", "KÜÇÜK BONCUK"] },
{ main: "SUSAMLI SİMİT", forbidden: ["SOKAK ARABASI", "KAĞIT KESİMİ", "SICAK FIRIN", "KALIN HALKA", "KAHVALTI YOLDA"] },
{ main: "AHŞAP KAŞIK", forbidden: ["DERİN TENCERE", "EL İŞÇİLİĞİ", "YEMEK ÇEVİRME", "ÇEKMECE KÖŞESİ", "ESKİ TAT"] },
{ main: "PİLAV TENCERESİ", forbidden: ["CAM KAPAK", "BUHAR ÇIKIŞI", "TAHTA ALTI", "SICAK TUTMAK", "TAHTA KAŞIK"] },
{ main: "ÇAKIL KOLEKSİYONU", forbidden: ["DENİZ KENARI", "KÜÇÜK KAVANOZ", "RENK SEÇMEK", "DİZİLİM DESENİ", "HATIRA TAŞ"] },
{ main: "UFUK ÇİZGİSİ", forbidden: ["GÖKYÜZÜ GEÇİŞİ", "DENİZ BİRLEŞİMİ", "GÜN BATIMI", "UZAK GEMİ", "GÖZ HİZASI"] },
{ main: "YEL DEĞİRMENİ MODELİ", forbidden: ["MAKET KANAT", "AHŞAP GÖVDE", "MASA ÜSTÜ", "ELLE ÇEVİRME", "KİTAPLIK RAFI"] },
{ main: "KUMBARA HAYVAN", forbidden: ["BOŞ ALT KAPAK", "BOŞALTMA VİDASI", "BOZUK PARA", "RAF ÜSTÜ", "HEDİYELİK NESNE"] },
{ main: "KURUTMALIK İP", forbidden: ["ÇORAP DİZİSİ", "MANDAL SESİ", "BALKON ÇİZGİSİ", "RÜZGAR DALGALANIŞI", "ISLANMIŞ ÇAMAŞIR"] },
{ main: "KULAK TIKIYICI", forbidden: ["YUMUŞAK SÜNGER", "UÇAK YOLCULUĞU", "UYKU YARDIMI", "KUTU KAPAĞI", "GÜRÜLTÜ AZALTMA"] },
{ main: "BAHARİYELİ MONT", forbidden: ["İNCE ASTAR", "SABAH SERİNLİĞİ", "RÜZGAR GEÇİRME", "ASKI UCU", "CEP FERMUARI"] },
{ main: "FİGÜRLÜ HALKA", forbidden: ["ANAHTAR TAKIMI", "METAL AYRINTI", "ASKI KANCASI", "ÇANTA YANI", "CEPLİK SESİ"] },
{ main: "METAL KARTVİZİT KUTUSU", forbidden: ["ÇANTADA DURMAK", "TOPLANTI MASASI", "İSİM KARTI", "KAPAK MEKANİZMASI", "İNCE TASARIM"] },
{ main: "KUMAŞ KAPLI DEFTER", forbidden: ["EL DİKİŞİ", "KAPAK DESENİ", "RUHBAN ÇİZGİSİ", "İMZA SAYFASI", "HEDİYE PAKETİ"] },
{ main: "SAĞLIK YASTIĞI", forbidden: ["BOYUN DESTEK", "YATAK ORTASI", "FERMUARLI KILIF", "UYKU DÜZENİ", "ORTOPEDİK FORM"] },
{ main: "KAPI DÜRBÜNÜ", forbidden: ["BİNA GİRİŞİ", "KÜÇÜK CAM", "CHİZİK HALKASI", "KİM GELDİ MERAKI", "KAPI ORTASI"] },
{ main: "ŞEMSİYELİK", forbidden: ["GİRİŞ HOLÜ", "DAMLA LEKESİ", "METAL STAND", "EV KAPISI", "ISLAK KUMAŞ"] },
{ main: "KABLO SARMA APARATI", forbidden: ["DÜZENLİ MASA", "KARMAŞA AZALTMA", "KÜÇÜK KLİPS", "ÇANTA İÇİ", "ESNEK HAT"] },
{ main: "KOLYE ASKISI", forbidden: ["AĞAÇ STAND", "DALLI TASARIM", "MÜCEVHER ODASI", "TAM AYNA", "DÜĞÜN HEDİYESİ"] },
{ main: "HATIRA KAVANOZU", forbidden: ["NOT KÂĞIDI", "BİLET PARÇASI", "KÜÇÜK NESNE", "KAPAK TARİHİ", "RAFA KOYMAK"] },
{ main: "RENKLİ POST-İT", forbidden: ["YAPIŞKAN KENAR", "MONİTÖR ÇERÇEVESİ", "HATIRLATMA NOTU", "PLAN DEFTERİ", "KOD İŞARETİ"] },
{ main: "BULMACA KİTABI", forbidden: ["KARE KARE", "KALEM KARALAMA", "YOLCULUK ARKADAŞI", "CEPLİK BOYUTU", "ÇÖZÜM ANAHTARI"] },
{ main: "CAM KAR TANELİ KÜRE", forbidden: ["SALLAMA ALIŞKANLIĞI", "İÇ SAHNE", "BEYAZ PARÇA", "RAF DEKORU", "HEDİYELİK MAĞAZA"] },
{ main: "TAŞLI KOL SAATİ", forbidden: ["METAL KORDON", "ZARİF ÇERÇEVE", "KADRAN PARILTISI", "DAVET AKŞAMI", "KUTU İÇİ"] },
{ main: "MİNİL MASA VENTİLATÖRÜ", forbidden: ["USB UCU", "KÜÇÜK PERGEL", "YAZ OFİSİ", "RÜZGAR HİSSİ", "DÜĞME AYARI"] },
{ main: "KAPAKLI TERMOS BARDAK", forbidden: ["SIZDIRMAZ LASTİK", "ÇANTA YANI", "SICAK TUTMA", "KAYAR MEKANİZMA", "SABAH YOLU"] },
{ main: "ÇİZGİLİ HALI", forbidden: ["KORİDOR ORTASI", "RENK BLOĞU", "KAYMAZ TABAN", "EV DEKORU", "MAKİNE YIKAMA"] },
{ main: "KEDİ TIRMALAMA TAHTASI", forbidden: ["YÜKSEK SUTUN", "İP SARIMI", "OYUN TOPU", "EVİN KÖŞESİ", "PENCERE ÖNÜ"] },
{ main: "MUMLU FANUS", forbidden: ["CAM KABUK", "GECE IŞIĞI", "MASA ORTASI", "RÜZGAR KORUMASI", "ROMANTİK ATMOSFER"] },
{ main: "AHŞAP SERVİS TABAĞI", forbidden: ["ATİSTİRLİK", "ORTA SUNUM", "KALIN PLAKA", "RESTORAN DETAYI", "ŞIK GÖRÜNÜM"] },
{ main: "KİTAP DESTEKLİĞİ", forbidden: ["RAF UCU", "METAL FORM", "DEVRİLME ÖNLEME", "KİTAP SIRASI", "OFİS SALONU"] },
{ main: "ŞAL ASKISI", forbidden: ["GARDIROP İÇİ", "DAİRE HALKA", "KUMAŞ DİZİMİ", "AKŞAM SOĞUĞU", "EV ÇIKIŞI"] },
{ main: "CAM KURABİYE KUTUSU", forbidden: ["MUTFAK TEZGAHI", "ŞEKERLİ TAT", "KAPAK AÇMA SESİ", "ÇOCUK MERAKI", "İKRAM ANI"] },
{ main: "ÇİZİM DEFTERİ", forbidden: ["KALIN SAYFA", "KURU BOYA", "KARALAMA KÖŞESİ", "KAPAK İLÜSTRASYONU", "ÇANTA ARKADAŞI"] },
{ main: "RENKLİ LİMONATA", forbidden: ["BARDAK KENARI", "BUZ PARÇASI", "MEYVE DİLİMİ", "YAZ BAHÇESİ", "SOĞUK SERVİS"] },
{ main: "KİLİTLİ GÜNLÜK", forbidden: ["KÜÇÜK ANAHTAR", "ÖZEL SAYFA", "GİZLİ CÜMLE", "YATAK BAŞI", "ERGENLİK HATIRASI"] },
{ main: "YAPRAK İŞARETLİK", forbidden: ["KİTAP ARASI", "METAL ŞEKİL", "HEDİYE SETİ", "ALINTI SATIRI", "ÇİZGİLİ ROMAN"] },
{ main: "PENCERE YASTIĞI", forbidden: ["UZUN FORM", "OTURMA KENARI", "GÜNEŞ IŞIĞI", "KEDİ UYKUSU", "KAHVE SAATİ"] },
{ main: "MARTI ÇİĞLİĞİ", forbidden: ["KIYI SESİ", "SABAH SAATİ", "BALIKÇI TEKNESİ", "FAZLA ECO", "ŞEHİR HAVASI"] },
{ main: "SAAT KULESİ", forbidden: ["MEYDAN ORTASI", "ÇAN SESİ", "YÜKSEK YAPI", "ŞEHİR BULUŞMASI", "ESKİ TARİH"] },
{ main: "KİREMİT ÇATI", forbidden: ["YAĞMUR TIKIRTISI", "EĞİMLİ YÜZEY", "KÖY MANZARASI", "KUZGUN OTURMASI", "SABAH GÜNEŞİ"] },
{ main: "SİS KORNASI", forbidden: ["KALIN SES", "GÖRÜŞ AZLIĞI", "UZAKTAN UYARI", "SU YÜZÜ", "SOĞUK HAVA"] },
{ main: "KİREMİT SAKSI", forbidden: ["PENCERE DIŞI", "KÜÇÜK ÇİÇEK", "TOPRAK KOKUSU", "YAĞMUR DAMLASI", "BALKON DEMİRİ"] },
{ main: "DOKUMA SEPET", forbidden: ["EL ÖRGÜSÜ", "PİKNİK FİKRİ", "KUMAŞ KULP", "MEYVE DİZİMİ", "RAFLA BERABER"] },
{ main: "HATIRA FOTOĞRAF DUVARI", forbidden: ["İPLİ DİZİLİM", "MANDAL ASMAK", "POLAROID KARE", "ODANIN KÖŞESİ", "ARKA FON"] },
{ main: "AHŞAP NOT PANOSU", forbidden: ["MANYETİK TUTUCU", "KÜÇÜK ÇİZİM", "HAFTALIK PLAN", "MUTFAK DUVARI", "EV PROGRAMI"] },
{ main: "SÜSLÜ KAPI TOKMAĞI", forbidden: ["METAL ŞEKİL", "EŞİK SESİ", "ESKİ TARZ", "İTME HAREKETİ", "GİRİŞ ALANI"] },
{ main: "ÇİÇEK DESENLİ KUPA", forbidden: ["SICAK İÇECEK", "RAF DİZİMİ", "KULP TUTUŞU", "BULAŞIK SEPETİ", "PAZAR SABAHI"] },
{ main: "PEDALLI ÇÖP KUTUSU", forbidden: ["AYAKLA BASMA", "KAPAK MEKANİZMASI", "MUTFAK KENARI", "TORBA DEĞİŞİMİ", "KOKU ÖNLEME"] },
{ main: "GECE PROJEKSİYONU", forbidden: ["TAVAN GÖRÜNTÜSÜ", "YILDIZ DESENİ", "ÇOCUK ODASI", "LOŞ ORTAM", "UYKU ÖNCESİ"] },
{ main: "HAFTA PLANI", forbidden: ["GÜNLÜK KUTUCUK", "RUTİN TAKİBİ", "RENKLİ KALEM", "BUZDOLABI KAPAĞI", "YAPIŞAN KAĞIT"] },
{ main: "NOSTALJİ RADYOSU", forbidden: ["BÜYÜK DÜĞME", "AHŞAP GÖRÜNÜM", "FON MÜZİĞİ", "ESKİ HAVA", "ANTRE MASASI"] },
{ main: "TREN MAKETİ", forbidden: ["RAY OYUNU", "VAGON DİZİMİ", "MASA ÜSTÜ", "KOLEKSİYON PARÇASI", "ÇOCUK ODASI"] },
{ main: "GÜNEŞ FENERİ", forbidden: ["GÜNDÜZ ŞARJ", "GECE AYDINLATMA", "BAHÇE YOLU", "TOPRAK DİREK", "LED IŞIK"] },
{ main: "MİNİ PERVANELİ KALEM", forbidden: ["OYUNCAK UCU", "YAZI YAZMAK", "SERİN HAVA", "GÜLME SEBEBİ", "MASA ARKADAŞI"] },
{ main: "SANDALYE MİNDERİ", forbidden: ["KUMAŞ KAPAK", "BAĞCIK DETAYI", "OTURMA RAHATLIĞI", "YEMEK MASASI", "RENKLİ KARE"] },
{ main: "İSİM ETİKETLİ KUPA", forbidden: ["OFİS MASASI", "KİMSE KARIŞMASIN", "HEDİYE SEPETİ", "BASKI YAZI", "SICAK İÇECEK"] },
{ main: "ÇAY DEMLEME SÜZGECİ", forbidden: ["METAL SİNEK", "BARDAK İÇİ", "YAPRAK TUTMAK", "KAŞIKLA ÇIKARMAK", "KÜÇÜK KANCALI"] },
{ main: "KÜÇÜK EL FENERİ", forbidden: ["PİL YUVASI", "GECE ÇEKMECESİ", "KAMPTA KULLANMAK", "DÜĞME BASTI", "ZAYIF IŞIK"] },
{ main: "RENKLİ TOZ TEBEŞİR", forbidden: ["KALDIRIM DESENİ", "ÇOCUK OYUNU", "ELDE LEKE", "YAĞMURDA SİLİNME", "KUTU İÇİ"] },
{ main: "CAM KUPA ALTLIĞI", forbidden: ["MASA KORUMAK", "ISLAK HALKA", "SÜSLÜ DESEN", "KUTU SETİ", "MİSAFİR GELİŞİ"] },
{ main: "MANYETİK KUM SAATİ", forbidden: ["METAL TOZ", "TANECİK DANSI", "ZAMAN GÖSTERGESİ", "OFİS HEDİYESİ", "MASA OYUNCAĞI"] }


 ];