        // Kelime havuzu
        const wordPool = [
{ main: "ABAJUR", forbidden: ["LAMBA", "IŞIK", "MASA", "ŞAPKA", "ELEKTRİK"] },
{ main: "ACUN ILICALI", forbidden: ["TELEVİZYON", "YARIŞMA", "SURVIVOR", "SUNUCU", "KANAL"] },
{ main: "ADEM ELMASI", forbidden: ["BOĞAZ", "ERKEK", "ÇIKINTI", "GIRTLAK", "SES"] },
{ main: "AĞAÇ", forbidden: ["ORMAN", "DAL", "YAPRAK", "GÖVDE", "MEYVE"] },
{ main: "AĞDA", forbidden: ["KIL", "TÜY", "ACIMAK", "ŞEKER", "TEMİZLİK"] },
{ main: "AĞLAMAK", forbidden: ["GÖZYAŞI", "ÜZÜLMEK", "HÜZÜN", "DUYGU", "AĞİT"] },
{ main: "AHİZE", forbidden: ["TELEFON", "KULAK", "SES", "KABLO", "ARAMA"] },
{ main: "AHMET KAYA", forbidden: ["ŞARKI", "SANATÇI", "MÜZİK", "ALBÜM", "TÜRKÜ"] },
{ main: "AHŞAP KAŞIK", forbidden: ["TAHTA", "MUTFAK", "YEMEK", "KARIŞTIRMAK", "TENCERE"] },
{ main: "AHTAPOT", forbidden: ["DENİZ", "KOLLAR", "MÜREKKEP", "OKYANUS", "BALIK"] },
{ main: "AIRFRYER", forbidden: ["KIZARTMA", "YAĞ", "MUTFAK", "ELEKTRİKLİ", "YEMEK"] },
{ main: "AJANDA", forbidden: ["NOT", "TAKVİM", "PLAN", "YAZMAK", "DEFTER"] },
{ main: "AJDA PEKKAN", forbidden: ["ŞARKICI", "SÜPERSTAR", "POP", "SAHNE", "MÜZİK"] },
{ main: "AKILLI SAAT", forbidden: ["SAAT", "BİLEK", "TEKNOLOJİ", "ADIM", "BİLDİRİM"] },
{ main: "AKILLI TAHTA", forbidden: ["OKUL", "SINIF", "DERS", "EKRAN", "ÖĞRETMEN"] },
{ main: "AKILLI TAHTA KALEMİ", forbidden: ["YAZMAK", "TAHTA", "OKUL", "DERS", "KALEM"] },
{ main: "AKORDİYON", forbidden: ["MÜZİK", "ENSTRÜMAN", "KÖRÜK", "ÇALMAK", "NOTA"] },
{ main: "AKREP", forbidden: ["BURÇ", "ZEHİR", "KISKANÇLIK", "SOKMAK", "HAYVAN"] },
{ main: "AKROBAT", forbidden: ["DENGE", "GÖSTERİ", "ESNEK", "SİRK", "TAKLA"] },
{ main: "AKUSTİK GİTAR", forbidden: ["TEL", "MÜZİK", "ÇALMAK", "ENSTRÜMAN", "ŞARKI"] },
{ main: "AKVARYUM", forbidden: ["BALIK", "SU", "CAM", "YEM", "EV"] },
{ main: "ALAFRANGA", forbidden: ["TUVALET", "BANYO", "OTURMAK", "KLOZET", "EV"] },
{ main: "ALİ BİÇİM", forbidden: ["YOUTUBER", "VİDEO", "SOSYAL MEDYA", "ÇEKİLİŞ", "İNTERNET"] },
{ main: "ALPER RENDE", forbidden: ["YOUTUBER", "VLOG", "VİDEO", "İNTERNET", "SOSYAL MEDYA"] },
{ main: "ALTIN", forbidden: ["TAKI", "SARI", "DEĞERLİ", "GRAM", "KUYUMCU"] },
{ main: "ALYANS", forbidden: ["EVLİLİK", "YÜZÜK", "NİKAH", "PARMAK", "ÇİFT"] },
{ main: "AMBULANS", forbidden: ["HASTANE", "SİREN", "ACİL", "112", "SAĞLIK"] },
{ main: "ANAHTAR", forbidden: ["KAPI", "KİLİT", "AÇMAK", "CEBİMDE", "METAL"] },
{ main: "ANAL PLUG", forbidden: ["YETİŞKİN", "AKSESUAR", "ÖZEL", "OYUNCAK", "MAHREM"] },
{ main: "ANNE", forbidden: ["BABA", "EVLAT", "AİLE", "ŞEFKAT", "DOĞURMAK"] },
{ main: "ANTİBİYOTİK", forbidden: ["İLAÇ", "ENFEKSİYON", "HASTALIK", "DOKTOR", "REÇETE"] },
{ main: "ANTİFRİZ", forbidden: ["ARABA", "MOTOR", "SOĞUTMA", "KIŞ", "RADYATÖR"] },
{ main: "ANTİKA", forbidden: ["ESKİ", "DEĞERLİ", "KOLEKSİYON", "TARİH", "EŞYA"] },
{ main: "APARTMAN", forbidden: ["BİNA", "DAİRE", "KAT", "ASANSÖR", "KOMŞU"] },
{ main: "APSE", forbidden: ["İLTİHAP", "ŞİŞLİK", "AĞRI", "DOKTOR", "ENFEKSİYON"] },
{ main: "ARABA", forbidden: ["TEKERLEK", "DİREKSİYON", "MOTOR", "YOL", "SÜRMEK"] },
{ main: "ARAS BULUT İYNEMLİ", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "ROL"] },
{ main: "ARI", forbidden: ["BAL", "SOKMAK", "KOVAN", "UÇMAK", "BÖCEK"] },
{ main: "ASANSÖR", forbidden: ["KAT", "BİNA", "İNMEK", "ÇIKMAK", "DÜĞME"] },
{ main: "ASETON", forbidden: ["OJE", "TEMİZLEMEK", "KOKU", "TIRNAK", "SİLMEK"] },
{ main: "ASTRONOT", forbidden: ["UZAY", "ROKET", "AY", "KIYAFET", "NASA"] },
{ main: "AŞÇI", forbidden: ["YEMEK", "MUTFAK", "PİŞİRMEK", "ŞEF", "TENCERE"] },
{ main: "AŞK", forbidden: ["SEVGİ", "DUYGU", "KALP", "ROMANTİK", "İLİŞKİ"] },
{ main: "ATA DEMİRER", forbidden: ["KOMEDYEN", "OYUNCU", "FİLM", "SAHNE", "ESPRİ"] },
{ main: "AVOKADO", forbidden: ["MEYVE", "YEŞİL", "SALATA", "ÇEKİRDEK", "SAĞLIK"] },
{ main: "AVRUPA YAKASI", forbidden: ["DİZİ", "SİTELER", "KOMEDİ", "TELEVİZYON", "KARAKTER"] },
{ main: "AYÇİÇEK YAĞI", forbidden: ["YEMEK", "KIZARTMA", "MUTFAK", "ŞİŞE", "YAĞ"] },
{ main: "AYI", forbidden: ["HAYVAN", "ORMAN", "KIŞ UYKUSU", "BAL", "BÜYÜK"] },
{ main: "AYRILMAK", forbidden: ["İLİŞKİ", "BİTMEK", "VEDA", "SEVGİLİ", "KOPMAK"] },
{ main: "BABA", forbidden: ["ANNE", "EVLAT", "AİLE", "OTORİTE", "KORUMAK"] },
{ main: "BABAFİNGO", forbidden: ["OYUN", "KART", "AİLE", "EĞLENCE", "MASA"] },
{ main: "BABAM VE OĞLUM", forbidden: ["FİLM", "AİLE", "DRAM", "GÖZYAŞI", "YÖNETMEN"] },
{ main: "BAĞLAMA", forbidden: ["SAZ", "TEL", "TÜRKÜ", "MÜZİK", "ÇALMAK"] },
{ main: "BALDIR", forbidden: ["BACAK", "DİZ", "KAS", "VÜCUT", "ALT"] },
{ main: "BALIK", forbidden: ["DENİZ", "SU", "PUL", "YÜZMEK", "OLTA"] },
{ main: "BALİNA", forbidden: ["DENİZ", "OKYANUS", "BÜYÜK", "MEMELİ", "SU"] },
{ main: "BALON", forbidden: ["ŞİŞİRMEK", "HAVA", "PARTİ", "UÇMAK", "RENKLİ"] },
{ main: "BAMYA", forbidden: ["SEBZE", "YEMEK", "TENCERE", "SALYA", "PİŞİRMEK"] },
{ main: "BANK", forbidden: ["OTURMAK", "PARK", "AHŞAP", "DIŞARISI", "KOLTUK"] },
{ main: "BARAJ", forbidden: ["SU", "ELEKTRİK", "NEHİR", "BETON", "ENERJİ"] },
{ main: "BARBEKÜ", forbidden: ["MANGAL", "ET", "ATEŞ", "DIŞARIDA", "IZGARA"] },
{ main: "BARDAK", forbidden: ["SU", "CAM", "İÇMEK", "MUTFAK", "KUPA"] },
{ main: "BARIŞ MANÇO", forbidden: ["ŞARKICI", "MÜZİK", "HAL HAL", "SANATÇI", "EFSANE"] },
{ main: "BARON", forbidden: ["MAFYA", "LİDER", "ZENGİN", "GÜÇ", "UNVAN"] },
{ main: "BATERİ", forbidden: ["DAVUL", "RİTİM", "MÜZİK", "ÇALMAK", "ENSTRÜMAN"] },
{ main: "BAVUL", forbidden: ["SEYAHAT", "EŞYA", "VALİZ", "TAŞIMAK", "YOLCULUK"] },
{ main: "BEBE BİSKÜVİSİ", forbidden: ["MAMA", "ÇOCUK", "YEMEK", "BEBEK", "PÜRE"] },
{ main: "BEBEK", forbidden: ["ANNE", "BABA", "KÜÇÜK", "DOĞUM", "ÇOCUK"] },
{ main: "BENSU SORAL", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "ROL"] },
{ main: "BEYAZIT ÖZTÜRK", forbidden: ["BEYAZ", "ŞOV", "SUNUCU", "TELEVİZYON", "KOMEDİ"] },
{ main: "BİBER GAZI", forbidden: ["SAVUNMA", "SPREY", "YAKICI", "POLİS", "GÖZ"] },
{ main: "BİBERİYE", forbidden: ["BAHARAT", "OT", "YEMEK", "KOKU", "AKDENİZ"] },
{ main: "BİLGİSAYAR", forbidden: ["KLAVYE", "EKRAN", "İNTERNET", "FARE", "TEKNOLOJİ"] },
{ main: "BİLİM KURGU ROMANI", forbidden: ["UZAY", "GELECEK", "KİTAP", "HAYAL", "TEKNOLOJİ"] },
{ main: "BILL GATES", forbidden: ["MICROSOFT", "ZENGİN", "YAZILIM", "WINDOWS", "GİRİŞİMCİ"] },
{ main: "BİSİKLET", forbidden: ["PEDAL", "TEKERLEK", "SÜRMEK", "ZİNCİR", "YOL"] },
{ main: "BİSİKLET YOLU", forbidden: ["ŞERİT", "SÜRMEK", "ASFALT", "TRAFİK", "GÜVENLİK"] },
{ main: "BIYIK", forbidden: ["SAKAL", "BURUN", "YÜZ", "KIL", "KESMEK"] },
{ main: "BLENDER", forbidden: ["MUTFAK", "KARIŞTIRMAK", "ELEKTRİKLİ", "ÇORBA", "MEYVE"] },
{ main: "BLOG", forbidden: ["YAZI", "İNTERNET", "SİTE", "PAYLAŞIM", "İÇERİK"] },
{ main: "BLOK3", forbidden: ["RAP", "ŞARKI", "MÜZİK", "SANATÇI", "GENÇ"] },
{ main: "BORSA", forbidden: ["HİSSE", "PARA", "YATIRIM", "ALIM", "SATIM"] },
{ main: "BOYNUZ", forbidden: ["HAYVAN", "KEÇİ", "İNEK", "SERT", "KAFA"] },
{ main: "BÖCEK", forbidden: ["KÜÇÜK", "HAYVAN", "UÇMAK", "SÜRÜNMEK", "KORKU"] },
{ main: "BÖREK", forbidden: ["HAMUR", "FIRIN", "PEYNİR", "YUFKA", "YEMEK"] },
{ main: "BULDOZER", forbidden: ["İNŞAAT", "TOPRAK", "MAKİNE", "İTMEK", "AĞIR"] },
{ main: "BULMACA", forbidden: ["ZEKÂ", "SORU", "KELİME", "ÇÖZMEK", "DERGİ"] },
{ main: "BULUT", forbidden: ["GÖKYÜZÜ", "BEYAZ", "YAĞMUR", "HAVA", "UÇAK"] },
{ main: "BURAK OYUNDA", forbidden: ["YOUTUBER", "OYUN", "VİDEO", "İNTERNET", "KANAL"] },
{ main: "BURAK ÖZÇİVİT", forbidden: ["OYUNCU", "DİZİ", "FİLM", "KARA SEVDA", "TELEVİZYON"] },
{ main: "BÜLENT ERSOY", forbidden: ["SANATÇI", "DİVA", "MÜZİK", "SAHNE", "ŞARKI"] },
{ main: "CAMİ", forbidden: ["İBADET", "NAMAZ", "MİNARE", "EZAN", "MÜSLÜMAN"] },
{ main: "CAN YAMAN", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "POPÜLER"] },
{ main: "CANKURTARAN", forbidden: ["DENİZ", "HAVUZ", "KURTARMAK", "YÜZMEK", "TEHLİKE"] },
{ main: "CELAL ŞENGÖR", forbidden: ["PROFESÖR", "JEOLOJİ", "BİLİM", "AKADEMİSYEN", "DEPREM"] },
{ main: "CEM ADRIAN", forbidden: ["ŞARKICI", "SES", "MÜZİK", "ALTERNATİF", "SAHNE"] },
{ main: "CEM YILMAZ", forbidden: ["KOMEDYEN", "ESPRİ", "STAND-UP", "FİLM", "GORA"] },
{ main: "CESET", forbidden: ["ÖLÜ", "CİNAYET", "OTOPSİ", "SUÇ", "POLİS"] },
{ main: "CETVEL", forbidden: ["ÖLÇMEK", "ÇİZGİ", "OKUL", "DÜZ", "PLASTİK"] },
{ main: "CUMHURİYET", forbidden: ["DEVLET", "BAYRAM", "ATATÜRK", "YÖNETİM", "DEMOKRASİ"] },
{ main: "CÜPPE", forbidden: ["HAKİM", "AVUKAT", "MAHKEME", "SİYAH", "GİYMEK"] },
{ main: "ÇADIR", forbidden: ["KAMP", "DOĞA", "UYUMAK", "TATİL", "KURMAK"] },
{ main: "ÇAKMAK", forbidden: ["ATEŞ", "YAKMAK", "SİGARA", "GAZ", "KIVILCIM"] },
{ main: "ÇALIŞMA LAMBASI", forbidden: ["IŞIK", "MASA", "OKUMAK", "ELEKTRİK", "AYDINLATMA"] },
{ main: "ÇALMAK", forbidden: ["HIRSIZLIK", "İZİNSİZ", "ALMAK", "SUÇ", "EŞYA"] },
{ main: "ÇAMAŞIR SEPETİ", forbidden: ["KİRLİ", "ELBİSE", "BANYO", "TOPLAMAK", "YIKAMAK"] },
{ main: "ÇANTA", forbidden: ["TAŞIMAK", "EŞYA", "OMUZ", "OKUL", "ÇANTA ASKISI"] },
{ main: "ÇAYDANLIK", forbidden: ["ÇAY", "SU", "KAYNATMAK", "OCAK", "DEMLİK"] },
{ main: "ÇEKİÇ", forbidden: ["ÇİVİ", "VURMAK", "ALETLER", "İNŞAAT", "EL"] },
{ main: "ÇEKİRDEK", forbidden: ["AYÇEKİRDEĞİ", "ÇİTLEMEK", "KABUK", "ATMAK", "AĞIZ"] },
{ main: "ÇELENK", forbidden: ["ÇİÇEK", "TÖREN", "CENAZE", "SUNMAK", "ANMA"] },
{ main: "ÇERÇEVE", forbidden: ["RESİM", "FOTOĞRAF", "DUVAR", "ASMAK", "KENAR"] },
{ main: "ÇEVRE RAPORU", forbidden: ["DOĞA", "ANALİZ", "ETKİ", "KİRLİLİK", "DEĞERLENDİRME"] },
{ main: "ÇİZGİ ROMAN", forbidden: ["KARE", "RESİM", "HİKAYE", "KİTAP", "BALON"] },
{ main: "ÇİZGİLİ PİJAMA", forbidden: ["UYKU", "GECE", "GİYMEK", "EV", "RAHAT"] },
{ main: "ÇORAP", forbidden: ["AYAK", "GİYMEK", "ÇİFT", "KOKU", "KUMAŞ"] },
{ main: "ÇÖP POŞETİ", forbidden: ["ÇÖP", "ATMAK", "SİYAH", "KOVA", "TEMİZLİK"] },
{ main: "DAĞ EVİ", forbidden: ["DOĞA", "TATİL", "SOBA", "UZAK", "SESSİZ"] },
{ main: "DAKTİLO", forbidden: ["YAZMAK", "TUŞ", "KAĞIT", "ESKİ", "MAKİNE"] },
{ main: "DAMBIL", forbidden: ["SPOR", "AĞIRLIK", "KAS", "SALON", "KALDIRMAK"] },
{ main: "DAVA", forbidden: ["MAHKEME", "HAKİM", "AVUKAT", "HUKUK", "DOSYA"] },
{ main: "DAVLUMBAZ", forbidden: ["MUTFAK", "KOKU", "OCAK", "ASPİRATÖR", "YEMEK"] },
{ main: "DAVUL", forbidden: ["RİTİM", "MÜZİK", "ÇALMAK", "TOKMAK", "SES"] },
{ main: "DELGEÇ", forbidden: ["KAĞIT", "DELİK", "OFİS", "ZIMBA", "DOSYA"] },
{ main: "DEMET AKALIN", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "ALBÜM"] },
{ main: "DEMET ÖZDEMİR", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "ROL"] },
{ main: "DEMİRBAŞ", forbidden: ["SABİT", "EŞYA", "ENVANTER", "KAYIT", "OFİS"] },
{ main: "DENİZ", forbidden: ["SU", "DALGA", "KUM", "SAHİL", "TUZLU"] },
{ main: "DENİZ FENERİ", forbidden: ["IŞIK", "KULE", "GEMİ", "KIYI", "UYARI"] },
{ main: "DİGİTÜRK", forbidden: ["TELEVİZYON", "KANAL", "YAYIN", "ABONELİK", "SPOR"] },
{ main: "DİKİŞ MAKİNESİ", forbidden: ["İĞNE", "İPLİK", "KUMAŞ", "DİKMEK", "TERZİ"] },
{ main: "DILDO", forbidden: ["YETİŞKİN", "AKSESUAR", "ÖZEL", "OYUNCAK", "MAHREM"] },
{ main: "DİPSİZ KUYU", forbidden: ["DERİN", "SONSUZ", "DÜŞMEK", "KARANLIK", "METAFOR"] },
{ main: "DİREK", forbidden: ["ELEKTRİK", "BAYRAK", "DİK", "BETON", "YOL"] },
{ main: "DİŞ", forbidden: ["AĞIZ", "ÇİĞNEMEK", "BEYAZ", "DOKTOR", "AĞRI"] },
{ main: "DİŞ MACUNU", forbidden: ["FIRÇALAMAK", "MİNT", "TEMİZLİK", "BANYO", "DİŞ"] },
{ main: "DİŞ TİCARET", forbidden: ["SİYASET", "ÇIKAR", "MENFAAT", "İLİŞKİ", "AL-VER"] },
{ main: "DOĞUMGÜNÜ", forbidden: ["PASTA", "KUTLAMA", "YAŞ", "HEDİYE", "MUM"] },
{ main: "DOKTOR", forbidden: ["HASTANE", "MUAYENE", "HASTA", "İLAÇ", "BEYAZ ÖNLÜK"] },
{ main: "DOLAP", forbidden: ["KIYAFET", "KAPAK", "RAF", "ODA", "SAKLAMAK"] },
{ main: "DONDURMA", forbidden: ["SOĞUK", "YAZ", "KÜLAH", "TOP", "ERİMEK"] },
{ main: "DOST", forbidden: ["ARKADAŞ", "GÜVEN", "SAMİMİ", "DESTEK", "YAKIN"] },
{ main: "DRONE", forbidden: ["UÇMAK", "KAMERA", "HAVADAN", "KUMANDA", "GÖRÜNTÜ"] },
{ main: "DUYGU ÖZASLAN", forbidden: ["FENOMEN", "SOSYAL MEDYA", "YOUTUBE", "VİDEO", "İÇERİK"] },
{ main: "DÜBEL", forbidden: ["DUVAR", "VİDA", "MATKAP", "SABİTLEMEK", "PLASTİK"] },
{ main: "DÜDÜK", forbidden: ["SES", "ÜFLEMEK", "HAKEM", "SPOR", "UYARI"] },
{ main: "DÜNYA TURU", forbidden: ["GEZMEK", "ÜLKE", "SEYAHAT", "PASAPORT", "UÇAK"] },
{ main: "DÜRBÜN", forbidden: ["UZAK", "BAKMAK", "GÖRMEK", "BÜYÜTMEK", "GÖZ"] },
{ main: "DÜRÜM", forbidden: ["LAVAŞ", "ET", "SARMAK", "YEMEK", "FAST FOOD"] },
{ main: "DVD", forbidden: ["FİLM", "CD", "OYNATICI", "DİSK", "İZLEMEK"] },
{ main: "E-OKUL", forbidden: ["ÖĞRENCİ", "NOT", "VELİ", "SİSTEM", "OKUL"] },
{ main: "E-SPOR TAKIMI", forbidden: ["OYUN", "TURNUVA", "PROFESYONEL", "TAKIM", "BİLGİSAYAR"] },
{ main: "EBE", forbidden: ["DOĞUM", "HASTANE", "BEBEK", "ANNE", "SAĞLIK"] },
{ main: "ECZANE", forbidden: ["İLAÇ", "REÇETE", "ECZACI", "SAĞLIK", "SATMAK"] },
{ main: "EKMEK MAKİNESİ", forbidden: ["HAMUR", "PİŞİRMEK", "MUTFAK", "ELEKTRİKLİ", "EKMEK"] },
{ main: "EKSEN EĞİKLİĞİ", forbidden: ["DÜNYA", "MEVSİM", "DÖNMEK", "COĞRAFYA", "UZAY"] },
{ main: "ELEKTRONİK İMZA", forbidden: ["DİJİTAL", "ONAY", "BELGE", "KİMLİK", "SİSTEM"] },
{ main: "ELMA", forbidden: ["MEYVE", "KIRMIZI", "AĞAÇ", "ISIRMAK", "ÇEKİRDEK"] },
{ main: "EMİR CAN İĞREK", forbidden: ["ŞARKICI", "MÜZİK", "POP", "SAHNE", "ŞARKI"] },
{ main: "EMZİK", forbidden: ["BEBEK", "AĞIZ", "SUSMAK", "PLASTİK", "ANNE"] },
{ main: "ENERJİ", forbidden: ["GÜÇ", "ELEKTRİK", "KUVVET", "HAREKET", "KAYNAK"] },
{ main: "ENES BATUR", forbidden: ["YOUTUBER", "VİDEO", "İNTERNET", "SOSYAL MEDYA", "KANAL"] },
{ main: "ENİS KİRAZOĞLU", forbidden: ["YOUTUBER", "OYUN", "VİDEO", "İNCELEME", "İNTERNET"] },
{ main: "ERTESİ GÜN HAPI", forbidden: ["KORUNMA", "GEBELİK", "İLAÇ", "ACİL", "KADIN"] },
{ main: "ESPRİ", forbidden: ["KOMİK", "GÜLDÜRMEK", "ŞAKA", "MİZAH", "KAHKAHA"] },
{ main: "ETEK", forbidden: ["GİYİM", "KADIN", "KIYAFET", "BEL", "MODA"] },
{ main: "EV", forbidden: ["ODA", "ÇATI", "YAŞAMAK", "AİLE", "KONUT"] },
{ main: "EVLİLİK", forbidden: ["NİKAH", "KARI", "KOCA", "AİLE", "RESMİ"] },
{ main: "EXCEL", forbidden: ["TABLO", "HÜCRE", "FORMÜL", "OFİS", "HESAPLAMA"] },
{ main: "EZGİ MOLA", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "ROL"] },
{ main: "FATİH PORTAKAL", forbidden: ["HABER", "SPİKER", "TELEVİZYON", "GAZETECİ", "ANA HABER"] },
{ main: "FATİH SULTAN MEHMET", forbidden: ["OSMANLI", "İSTANBUL", "PADİŞAH", "FETİH", "TARİH"] },
{ main: "FATURA", forbidden: ["ÖDEMEK", "BORÇ", "ELEKTRİK", "SU", "GELEN"] },
{ main: "FAYANS", forbidden: ["BANYO", "SERAMİK", "DUVAR", "ZEMİN", "DÖŞEME"] },
{ main: "FERMUAR", forbidden: ["KIYAFET", "AÇMAK", "KAPATMAK", "CEKET", "PANTOLON"] },
{ main: "FİLOLOJİ", forbidden: ["DİL", "EDEBİYAT", "BİLİM", "KELİME", "METİN"] },
{ main: "FİLTRE KAHVE", forbidden: ["KAHVE", "SÜZME", "SICAK", "İÇECEK", "KAFEİN"] },
{ main: "FİNCAN", forbidden: ["KAHVE", "KÜÇÜK", "PORSELEN", "İÇMEK", "KULP"] },
{ main: "FIRÇA", forbidden: ["BOYA", "SAÇ", "DİŞ", "TEMİZLEMEK", "KIL"] },
{ main: "FLAŞ", forbidden: ["IŞIK", "KAMERA", "PATLAMAK", "FOTOĞRAF", "ANI"] },
{ main: "FOSFOR", forbidden: ["PARLAMAK", "KİMYA", "IŞIK", "MADDE", "REAKSİYON"] },
{ main: "FOTOĞRAF", forbidden: ["RESİM", "KAMERA", "ÇEKMEK", "ANI", "KARE"] },
{ main: "FOTOĞRAF MAKİNESİ", forbidden: ["KAMERA", "LENS", "ÇEKMEK", "FOTOĞRAF", "TEKNOLOJİ"] },
{ main: "FOTOKOPİ", forbidden: ["ÇEKMEK", "KÂĞIT", "MAKİNE", "ÇOĞALTMAK", "OFİS"] },
{ main: "FUTBOL", forbidden: ["TOP", "MAÇ", "KALE", "GOL", "SAHA"] },
{ main: "GAGA", forbidden: ["KUŞ", "AĞIZ", "YEMEK", "SERT", "HAYVAN"] },
{ main: "GALAKSİ", forbidden: ["UZAY", "YILDIZ", "SAMANYOLU", "EVREN", "GEZEGEN"] },
{ main: "GEBE", forbidden: ["HAMİLE", "BEBEK", "DOĞUM", "ANNE", "KARIN"] },
{ main: "GECE LAMBASI", forbidden: ["IŞIK", "UYKU", "ODASI", "KARANLIK", "PRİZ"] },
{ main: "GELİNLİK", forbidden: ["DÜĞÜN", "BEYAZ", "EVLİLİK", "KADIN", "NİKAH"] },
{ main: "GEMİ", forbidden: ["DENİZ", "LİMAN", "YÜZMEK", "BÜYÜK", "TAŞIMA"] },
{ main: "GERDEK GECESİ", forbidden: ["EVLİLİK", "DÜĞÜN", "İLK", "ÖZEL", "GECE"] },
{ main: "GİRDAP", forbidden: ["SU", "DÖNMEK", "ÇEKMEK", "DENİZ", "TEHLİKE"] },
{ main: "GOOGLE", forbidden: ["ARAMA", "İNTERNET", "TARAYICI", "WEB", "ŞİRKET"] },
{ main: "GÖBEK BAĞI", forbidden: ["BEBEK", "DOĞUM", "ANNE", "KESMEK", "HASTANE"] },
{ main: "GÖKDELEN", forbidden: ["BİNA", "YÜKSEK", "KAT", "ŞEHİR", "ASANSÖR"] },
{ main: "GÖKHAN TÜRKMEN", forbidden: ["ŞARKICI", "MÜZİK", "POP", "SAHNE", "ŞARKI"] },
{ main: "GÖKTAŞI", forbidden: ["UZAY", "DÜŞMEK", "METEOR", "DÜNYA", "TAŞ"] },
{ main: "GÖLGE OYUNU", forbidden: ["KARAGÖZ", "HACİVAT", "PERDE", "IŞIK", "GELENEK"] },
{ main: "GÖNÜL YARASI", forbidden: ["ACİ", "KALP", "AŞK", "ÜZÜNTÜ", "DUYGU"] },
{ main: "GÖZ BANDI", forbidden: ["UYKU", "KAPATMAK", "GÖZ", "IŞIK", "MASKE"] },
{ main: "GÖZLÜK", forbidden: ["CAM", "GÖZ", "GÖRMEK", "ÇERÇEVE", "TAKMAK"] },
{ main: "GÖZLÜK KABI", forbidden: ["KORUMAK", "GÖZLÜK", "KUTU", "SERT", "TAŞIMAK"] },
{ main: "GÖZYAŞI", forbidden: ["AĞLAMAK", "DUYGU", "ISLAK", "ÜZÜNTÜ", "GÖZ"] },
{ main: "GÜBRE", forbidden: ["TOPRAK", "TARIM", "BİTKİ", "VERİM", "KOKU"] },
{ main: "GÜLBEN ERGEN", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "SANATÇI"] },
{ main: "GÜMRÜK", forbidden: ["SINIR", "VERGİ", "İTHALAT", "İHRACAT", "KONTROL"] },
{ main: "GÜNEŞ", forbidden: ["IŞIK", "SICAK", "GÜNDÜZ", "GÖKYÜZÜ", "YILDIZ"] },
{ main: "GÜNEŞ FENERİ", forbidden: ["ENERJİ", "IŞIK", "ŞARJ", "PANEL", "ELEKTRİK"] },
{ main: "GÜNEŞ GÖZLÜĞÜ", forbidden: ["CAM", "YAZ", "IŞIK", "TAKMAK", "KORUMA"] },
{ main: "GÜNEŞ KREMİ", forbidden: ["CİLT", "KORUMA", "YAZ", "PLAJ", "YANIK"] },
{ main: "GÜNEŞ PANELİ", forbidden: ["ENERJİ", "ELEKTRİK", "ÇATI", "GÜNEŞ", "YENİLENEBİLİR"] },
{ main: "HAC", forbidden: ["MEKKE", "İBADET", "KABE", "İSLAM", "YOLCULUK"] },
{ main: "HADİSE", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "JÜRİ"] },
{ main: "HAKİM", forbidden: ["MAHKEME", "DAVA", "KARAR", "HUKUK", "CÜPPE"] },
{ main: "HALI", forbidden: ["YER", "SERMEK", "EV", "DESEN", "DOKUMA"] },
{ main: "HALUK BİLGİNER", forbidden: ["OYUNCU", "FİLM", "DİZİ", "TİYATRO", "SANATÇI"] },
{ main: "HAMAM", forbidden: ["BUHAR", "KESE", "SICAK", "YIKANMAK", "GELENEK"] },
{ main: "HAMAM BÖCEĞİ", forbidden: ["BÖCEK", "PİS", "GECE", "EV", "KORKU"] },
{ main: "HARDAL", forbidden: ["SOS", "SARI", "YEMEK", "ACİ", "BAHARAT"] },
{ main: "HARRY POTTER", forbidden: ["BÜYÜ", "HOGWARTS", "ASA", "FANTASTİK", "ROMAN"] },
{ main: "HASTALIK", forbidden: ["ATEŞ", "AĞRI", "DOKTOR", "İLAÇ", "HASTA"] },
{ main: "HAVAALANI", forbidden: ["UÇAK", "UÇUŞ", "PASAPORT", "TERMINAL", "SEYAHAT"] },
{ main: "HEDİYE PAKETİ", forbidden: ["SÜRPRİZ", "KUTU", "KURDELE", "VERMEK", "ÖZEL"] },
{ main: "HEYELAN", forbidden: ["TOPRAK", "KAYMAK", "YAĞMUR", "DOĞA", "AFET"] },
{ main: "HEYEKEL", forbidden: ["TAŞ", "SANAT", "YONTMAK", "ANIT", "FİGÜR"] },
{ main: "HİNDİSTAN", forbidden: ["ÜLKE", "ASYA", "NÜFUS", "TAJ MAHAL", "KÜLTÜR"] },
{ main: "HİPODROM", forbidden: ["AT", "YARIŞ", "PIST", "BAHİS", "TRİBÜN"] },
{ main: "HOKKABAZ", forbidden: ["GÖSTERİ", "SİRK", "NUMARA", "EL ÇABUKLUĞU", "ŞAŞIRTMAK"] },
{ main: "HOLLANDA", forbidden: ["ÜLKE", "AVRUPA", "LALE", "KANAL", "AMSTERDAM"] },
{ main: "HOPARLÖR", forbidden: ["SES", "MÜZİK", "YÜKSEK", "ÇIKTI", "ELEKTRONİK"] },
{ main: "HÖRGÜÇ", forbidden: ["DEVE", "SIRT", "ŞİŞLİK", "ÇÖL", "YAĞ"] },
{ main: "HÜLYA AVŞAR", forbidden: ["OYUNCU", "ŞARKICI", "SANATÇI", "FİLM", "SAHNE"] },
{ main: "ISLAK", forbidden: ["SU", "KURU", "NEM", "YAĞMUR", "DOKUNMAK"] },
{ main: "İBRAHİM TATLISES", forbidden: ["ŞARKICI", "TÜRKÜ", "URFA", "MÜZİK", "SANATÇI"] },
{ main: "İKTİDAR", forbidden: ["YÖNETİM", "SİYASET", "GÜÇ", "DEVLET", "YETKİ"] },
{ main: "İMLA KILAVUZU", forbidden: ["YAZIM", "KURALLAR", "NOKTALAMA", "TÜRKÇE", "KİTAP"] },
{ main: "İNTERNET", forbidden: ["BAĞLANTI", "WEB", "SİTE", "ONLINE", "AĞ"] },
{ main: "İREM DERİCİ", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "SANATÇI"] },
{ main: "İSKELE", forbidden: ["LİMAN", "GEMİ", "DENİZ", "YANAŞMAK", "TAHTA"] },
{ main: "İSMAİL YK", forbidden: ["ŞARKICI", "POP", "HAREKETLİ", "MÜZİK", "SAHNE"] },
{ main: "İŞ GÖRÜŞMESİ", forbidden: ["MÜLAKAT", "İŞ", "CV", "SORU", "ŞİRKET"] },
{ main: "JAPON BALIĞI", forbidden: ["AKVARYUM", "TURUNCU", "BALIK", "SU", "CAM"] },
{ main: "JÖLE", forbidden: ["SAÇ", "ŞEKİL", "SÜRMEK", "PARLAK", "KOZMETİK"] },
{ main: "JÜPİTER", forbidden: ["GEZEGEN", "UZAY", "BÜYÜK", "GAZ", "GÜNEŞ SİSTEMİ"] },
{ main: "KABARTMA TOZU", forbidden: ["HAMUR", "KABARMAK", "YEMEK", "PASTA", "FIRIN"] },
{ main: "KABLOSUZ ŞARJ", forbidden: ["TELEFON", "PİL", "ELEKTRİK", "CIHAZ", "ŞARJ"] },
{ main: "KABUS", forbidden: ["RÜYA", "KORKU", "GECE", "UYKU", "KARANLIK"] },
{ main: "KAFATASI", forbidden: ["KEMİK", "BAŞ", "İNSAN", "İSKELET", "BEYİN"] },
{ main: "KAHVE", forbidden: ["İÇECEK", "KAFEİN", "SICAK", "FİNCAN", "SABAH"] },
{ main: "KALDIRIM", forbidden: ["YAYA", "YOL", "TAŞ", "KENAR", "YÜRÜMEK"] },
{ main: "KALECİ", forbidden: ["FUTBOL", "KALE", "TOP", "KURTARMAK", "MAÇ"] },
{ main: "KALEM", forbidden: ["YAZMAK", "SİLGİ", "KAĞIT", "OKUL", "DEFTER"] },
{ main: "KALIP SABUN", forbidden: ["TEMİZLİK", "EL", "KÖPÜK", "BANYO", "KATI"] },
{ main: "KALP", forbidden: ["AŞK", "DUYGU", "GÖĞÜS", "ATMAK", "ORGAN"] },
{ main: "KAMU SPOTU", forbidden: ["BİLİNÇLENDİRME", "REKLAM", "TELEVİZYON", "TOPLUM", "MESAJ"] },
{ main: "KANAT", forbidden: ["UÇMAK", "KUŞ", "TAVUK", "YAN", "AÇMAK"] },
{ main: "KANDİL", forbidden: ["DİNİ", "GECE", "İBADET", "ÖZEL", "MÜBAREK"] },
{ main: "KANO", forbidden: ["KÜREK", "SU", "NEHİR", "SPOR", "TEKNE"] },
{ main: "KAPADOKYA", forbidden: ["PERİ BACALARI", "BALON", "NEVŞEHİR", "TURİZM", "BÖLGE"] },
{ main: "KAPAK AÇACAĞI", forbidden: ["ŞİŞE", "METAL", "AÇMAK", "MUTFAK", "ALETLER"] },
{ main: "KAPI DÜRBÜNÜ", forbidden: ["GÖZ", "BAKMAK", "KAPI", "DELİK", "GÜVENLİK"] },
{ main: "KAPI ZİLİ", forbidden: ["BASMAK", "SES", "KAPI", "EV", "ÇALMAK"] },
{ main: "KARA KUTU", forbidden: ["UÇAK", "KAZA", "KAYIT", "BİLGİ", "BULMAK"] },
{ main: "KARABİBER", forbidden: ["BAHARAT", "ACİ", "YEMEK", "SERPMEK", "TANE"] },
{ main: "KARANLIK ODA", forbidden: ["FOTOĞRAF", "IŞIK", "BANYO", "NEGATİF", "GELİŞTİRME"] },
{ main: "KARAOKE", forbidden: ["ŞARKI", "SÖZ", "MİKROFON", "SÖYLEMEK", "EĞLENCE"] },
{ main: "KARBONAT", forbidden: ["KABARMAK", "HAMUR", "TEMİZLİK", "TOZ", "MUTFAK"] },
{ main: "KARDEŞ PAYI", forbidden: ["DİZİ", "AİLE", "KOMEDİ", "TELEVİZYON", "KARDEŞ"] },
{ main: "KARE KOD", forbidden: ["TELEFON", "OKUTMAK", "KAMERA", "SİYAH", "BEYAZ"] },
{ main: "KARGO ŞUBESİ", forbidden: ["PAKET", "GÖNDERİ", "TESLİMAT", "ŞİRKET", "KUTU"] },
{ main: "KARİDES", forbidden: ["DENİZ", "KABUKLU", "YEMEK", "TAVA", "DENİZ ÜRÜNÜ"] },
{ main: "KARPUZ", forbidden: ["MEYVE", "YAZ", "KIRMIZI", "ÇEKİRDEK", "DİLİM"] },
{ main: "KARTAL", forbidden: ["KUŞ", "UÇMAK", "YIRTICI", "KANAT", "PENÇE"] },
{ main: "KARTON KUTU", forbidden: ["KOLİ", "TAŞIMA", "PAKET", "MUKAVVA", "DEPOLAMA"] },
{ main: "KARTPOSTAL", forbidden: ["POSTA", "RESİM", "YAZI", "GÖNDERMEK", "TATİL"] },
{ main: "KARTUŞ", forbidden: ["YAZICI", "MÜREKKEP", "BASKI", "RENK", "TONER"] },
{ main: "KARYOLA", forbidden: ["YATAK", "UYUMAK", "ODA", "BAŞLIK", "MOBİLYA"] },
{ main: "KÂSE", forbidden: ["YEMEK", "ÇORBA", "KÜÇÜK", "KAP", "MUTFAK"] },
{ main: "KASET", forbidden: ["MÜZİK", "BANT", "ÇALAR", "ESKİ", "KAYIT"] },
{ main: "KASIMPATI", forbidden: ["ÇİÇEK", "SARI", "BAHÇE", "BAHAR", "BİTKİ"] },
{ main: "KATEGORİ", forbidden: ["SINIF", "GRUP", "AYIRMAK", "BAŞLIK", "TÜR"] },
{ main: "KAVGA", forbidden: ["TARTIŞMA", "DÖVÜŞ", "BAĞIRMAK", "ŞİDDET", "GERİLİM"] },
{ main: "KAYDIRAK", forbidden: ["ÇOCUK", "PARK", "KAYMAK", "OYUN", "PLASTİK"] },
{ main: "KAYIK", forbidden: ["TEKNE", "KÜREK", "DENİZ", "GÖL", "SU"] },
{ main: "KAYISI BAHÇESİ", forbidden: ["AĞAÇ", "MEYVE", "MALATYA", "TARIM", "HASAT"] },
{ main: "KAYKAY", forbidden: ["TEKERLEK", "SPOR", "SÜRMEK", "TAHTA", "GENÇ"] },
{ main: "KAYMAK", forbidden: ["SÜT", "KAHVALTI", "BAL", "KREMAMSİ", "SÜRMEK"] },
{ main: "KAZAK", forbidden: ["KIYAFET", "KIŞ", "YÜN", "GİYMEK", "SICAK"] },
{ main: "KAZIK", forbidden: ["SERT", "TOPRAK", "ÇAKMAK", "TAHTA", "DİK"] },
{ main: "KEÇE", forbidden: ["KUMAŞ", "YUMUŞAK", "KEÇİ", "EL SANATI", "MALZEME"] },
{ main: "KEDİ", forbidden: ["HAYVAN", "MİYAV", "PATİ", "TÜYLÜ", "EVCİL"] },
{ main: "KEDİ TIRMALAMA TAHTASI", forbidden: ["KEDİ", "TIRNAK", "TAHTA", "EV", "OYUNCAK"] },
{ main: "KEK", forbidden: ["PASTA", "FIRIN", "HAMUR", "TATLI", "KABARMAK"] },
{ main: "KELEBEK", forbidden: ["BÖCEK", "KANAT", "UÇMAK", "RENKLİ", "KOZA"] },
{ main: "KEMAL KILIÇDAROĞLU", forbidden: ["SİYASET", "CHP", "GENEL BAŞKAN", "SEÇİM", "PARTİ"] },
{ main: "KEMAL SUNAL", forbidden: ["KOMEDİ", "FİLM", "OYUNCU", "ŞABAN", "YEŞİLÇAM"] },
{ main: "KEMAN", forbidden: ["MÜZİK", "YAY", "TEL", "ENSTRÜMAN", "ÇALMAK"] },
{ main: "KENAN SOFUOĞLU", forbidden: ["MOTOSİKLET", "YARIŞ", "SPORCU", "HIZ", "ŞAMPİYON"] },
{ main: "KENT ORMANI", forbidden: ["AĞAÇ", "ŞEHİR", "DOĞA", "PİKNİK", "YEŞİL"] },
{ main: "KEŞ", forbidden: ["PEYNİR", "SÜT", "KURUTULMUŞ", "TUZLU", "YEMEK"] },
{ main: "KETÇAP", forbidden: ["SOS", "DOMATES", "KIRMIZI", "PATATES", "SÜRMEK"] },
{ main: "KIL", forbidden: ["TÜY", "VÜCUT", "KESMEK", "İNSAN", "İNCE"] },
{ main: "KİBRİT", forbidden: ["ATEŞ", "YAKMAK", "ÇÖP", "KUTU", "ÇAKMAK"] },
{ main: "KİL MASKESİ", forbidden: ["CİLT", "YÜZ", "BAKIM", "KOZMETİK", "SÜRMEK"] },
{ main: "KİLİM", forbidden: ["HALI", "DOKUMA", "YER", "DESEN", "SERMEK"] },
{ main: "KİLİT", forbidden: ["ANAHTAR", "KAPI", "GÜVENLİK", "AÇMAK", "KAPATMAK"] },
{ main: "KIRBAÇ", forbidden: ["VURMAK", "DERİ", "UZUN", "SES", "CEZA"] },
{ main: "KIRMIZI", forbidden: ["RENK", "KAN", "AL", "DUR", "PARLAK"] },
{ main: "KIRMIZI GÜL", forbidden: ["ÇİÇEK", "AŞK", "ROMANTİK", "DİKEN", "SEVGİ"] },
{ main: "KİTAP", forbidden: ["OKUMAK", "SAYFA", "YAZAR", "ROMAN", "KAPAK"] },
{ main: "KİTAP AYRACI", forbidden: ["SAYFA", "KİTAP", "İŞARET", "ARADA", "OKUMA"] },
{ main: "KİTAPLIK", forbidden: ["RAF", "KİTAP", "ODA", "DÜZEN", "MOBİLYA"] },
{ main: "KİVİ", forbidden: ["MEYVE", "YEŞİL", "TÜYLÜ", "EKŞİ", "DİLİM"] },
{ main: "KIZ KULESİ", forbidden: ["İSTANBUL", "BOĞAZ", "DENİZ", "TARİH", "MANZARA"] },
{ main: "KLARNET", forbidden: ["MÜZİK", "ÜFLEME", "ENSTRÜMAN", "NOTA", "ÇALMAK"] },
{ main: "KLAVYE", forbidden: ["BİLGİSAYAR", "TUŞ", "YAZMAK", "Q", "HARF"] },
{ main: "KLİMA", forbidden: ["SOĞUTMA", "SICAK", "SERİN", "EV", "ELEKTRİK"] },
{ main: "KLOZET", forbidden: ["TUVALET", "BANYO", "OTURMAK", "SU", "TEMİZLİK"] },
{ main: "KOBRA", forbidden: ["YILAN", "ZEHİR", "UZUN", "SÜRÜNGEN", "ISIRMAK"] },
{ main: "KOLTUK", forbidden: ["OTURMAK", "SALON", "MOBİLYA", "RAHAT", "YER"] },
{ main: "KOLYE", forbidden: ["TAKI", "BOYUN", "ZİNCİR", "ALTIN", "GÜMÜŞ"] },
{ main: "KOMBİ", forbidden: ["ISINMA", "DOĞALGAZ", "PETEK", "SU", "EV"] },
{ main: "KONDOM", forbidden: ["KORUNMA", "GEBELİK", "İLİŞKİ", "SAĞLIK", "LATEKS"] },
{ main: "KONSER BİLETİ", forbidden: ["MÜZİK", "SAHNE", "GİRİŞ", "ETKİNLİK", "SANATÇI"] },
{ main: "KORİDOR", forbidden: ["GEÇİŞ", "UZUN", "ODA", "EV", "YOL"] },
{ main: "KÖLE", forbidden: ["ESARET", "ÖZGÜRLÜK", "ZİNCİR", "ÇALIŞTIRMAK", "TARİH"] },
{ main: "KÖSTEBEK", forbidden: ["TOPRAK", "KAZMAK", "HAYVAN", "KÖR", "YUVA"] },
{ main: "KÖYLÜ", forbidden: ["KÖY", "TARIM", "ÇİFTÇİ", "KIRSAL", "YAŞAM"] },
{ main: "KRAL", forbidden: ["TAHT", "TAÇ", "HÜKÜMDAR", "SARAY", "YÖNETMEK"] },
{ main: "KRAL ŞAKİR", forbidden: ["ÇİZGİ FİLM", "ASLAN", "ÇOCUK", "KANAL", "KARAKTER"] },
{ main: "KRAVAT", forbidden: ["GÖMLEK", "TAKMAK", "RESMİ", "BOYUN", "KIYAFET"] },
{ main: "KREM", forbidden: ["CİLT", "SÜRMEK", "NEM", "BAKIM", "KOZMETİK"] },
{ main: "KRİKO", forbidden: ["ARABA", "KALDIRMAK", "LASTİK", "TAMİR", "ALET"] },
{ main: "KRONOMETRE", forbidden: ["ZAMAN", "ÖLÇMEK", "SPOR", "SAYAÇ", "SÜRE"] },
{ main: "KUKLA", forbidden: ["OYUNCAK", "İP", "SAHNE", "EL", "GÖSTERİ"] },
{ main: "KULAK MEMESİ", forbidden: ["KULAK", "TAKİ", "DELİK", "YUMUŞAK", "VÜCUT"] },
{ main: "KULİS", forbidden: ["SAHNE", "ARKA", "OYUNCU", "HAZIRLIK", "TİYATRO"] },
{ main: "KULUÇKA", forbidden: ["YUMURTA", "CİVCİV", "SICAKLIK", "TAVUK", "ÇIKMAK"] },
{ main: "KULÜBE", forbidden: ["KÜÇÜK", "EV", "TAHTA", "BAHÇE", "BARINAK"] },
{ main: "KUM SAATİ", forbidden: ["ZAMAN", "KUM", "AKMAK", "ÖLÇMEK", "CAM"] },
{ main: "KUMANDA", forbidden: ["TELEVİZYON", "TUŞ", "KANAL", "UZAKTAN", "BASMAK"] },
{ main: "KUMBARA", forbidden: ["PARA", "BİRİKTİRMEK", "ÇOCUK", "METAL", "ATMAK"] },
{ main: "KUPON", forbidden: ["İNDİRİM", "KAMPANYA", "BİLET", "KOD", "KAZANÇ"] },
{ main: "KURBAN", forbidden: ["BAYRAM", "KESMEK", "HAYVAN", "İBADET", "PAYLAŞMAK"] },
{ main: "KURU", forbidden: ["ISLAK", "NEM", "SU", "SERT", "ÇÖL"] },
{ main: "KURUTMA MAKİNESİ", forbidden: ["ÇAMAŞIR", "ISLAK", "ELEKTRİK", "BEYAZ EŞYA", "DÖNMEK"] },
{ main: "KURYE", forbidden: ["TESLİMAT", "PAKET", "MOTOSİKLET", "HIZLI", "GÖNDERİ"] },
{ main: "KÜF", forbidden: ["NEM", "KOKU", "MANTAR", "YEŞİL", "BOZULMA"] },
{ main: "KÜLLÜK", forbidden: ["SİGARA", "İZMARİT", "KÜL", "MASA", "CAM"] },
{ main: "KÜNEFE", forbidden: ["TATLI", "PEYNİR", "ŞERBET", "SICAK", "ANTEP"] },
{ main: "KÜPE", forbidden: ["TAKI", "KULAK", "DELİK", "ALTIN", "GÜMÜŞ"] },
{ main: "LADY GAGA", forbidden: ["ŞARKICI", "POP", "SAHNE", "KOSTÜM", "MÜZİK"] },
{ main: "LATİFE", forbidden: ["ŞAKA", "İRONİ", "ESPRİ", "SÖZ", "ANLAM"] },
{ main: "LAVANTA TARLASI", forbidden: ["MOR", "KOKU", "ÇİÇEK", "PROVENCE", "DOĞA"] },
{ main: "LEVENT KIRCA", forbidden: ["KOMEDYEN", "OYUNCU", "TİYATRO", "SANATÇI", "HİCİV"] },
{ main: "LEYLEK", forbidden: ["KUŞ", "GÖÇ", "UZUN", "GAGA", "BAHAR"] },
{ main: "LUNAPARK", forbidden: ["EĞLENCE", "OYUNCAK", "DÖNME DOLAP", "ADRENALİN", "BİLET"] },
{ main: "LVBELC5", forbidden: ["RAP", "ŞARKI", "MÜZİK", "SANATÇI", "GENÇ"] },
{ main: "MAGAZİN", forbidden: ["ÜNLÜ", "HABER", "DEKOLTE", "GÜNDEM", "BASIN"] },
{ main: "MAİL", forbidden: ["E-POSTA", "İNTERNET", "GÖNDERMEK", "MESAJ", "KUTU"] },
{ main: "MAKARON", forbidden: ["HAMUR", "RENKLİ", "TATLI", "FRANSA", "KREMA"] },
{ main: "MAKAS", forbidden: ["KESMEK", "KAĞIT", "METAL", "EL", "AÇMAK"] },
{ main: "MANDAL", forbidden: ["ÇAMAŞIR", "ASMAK", "İP", "PLASTİK", "SABİT"] },
{ main: "MANGAL KÖMÜRÜ", forbidden: ["ATEŞ", "IZGARA", "ET", "SİYAH", "YAKMAK"] },
{ main: "MANTAR", forbidden: ["ORMAN", "YEMEK", "ŞAPKA", "DOĞA", "TOPLAMAK"] },
{ main: "MASKARA", forbidden: ["KİRPİK", "GÖZ", "MAKYAJ", "SÜRMEK", "KOZMETİK"] },
{ main: "MATKAP", forbidden: ["DELMEK", "DUVAR", "VİDA", "ELEKTRİKLİ", "ALETLER"] },
{ main: "MAYMUN", forbidden: ["HAYVAN", "ORMAN", "MUZ", "AĞAÇ", "ZEKİ"] },
{ main: "MAYO", forbidden: ["DENİZ", "HAVUZ", "YÜZMEK", "YAZ", "GİYMEK"] },
{ main: "MEGALOMAN", forbidden: ["EGO", "KENDİNİ BEĞENMEK", "BÜYÜKLÜK", "KİBİR", "KARAKTER"] },
{ main: "MEHMET ALİ ERBİL", forbidden: ["SUNUCU", "TELEVİZYON", "ŞOV", "OYUNCU", "MAGAZİN"] },
{ main: "MENTOL", forbidden: ["FERAH", "NANE", "KOKU", "SERİN", "AROMA"] },
{ main: "MERMER", forbidden: ["TAŞ", "ZEMİN", "PARLAK", "DOĞAL", "DÖŞEME"] },
{ main: "MERVE BOLUĞUR", forbidden: ["OYUNCU", "DİZİ", "TELEVİZYON", "ROL", "SANATÇI"] },
{ main: "MEŞALE", forbidden: ["ATEŞ", "IŞIK", "YAKMAK", "ELDE", "ALEV"] },
{ main: "METEOR", forbidden: ["UZAY", "DÜŞMEK", "TAŞ", "ATMOSFER", "GÖK"] },
{ main: "METEOROLOJİ", forbidden: ["HAVA", "TAHMİN", "YAĞMUR", "RÜZGAR", "SICAKLIK"] },
{ main: "METRO İSTASYONU", forbidden: ["TREN", "YER ALTI", "ULAŞIM", "PERON", "HAT"] },
{ main: "MICHAEL JACKSON", forbidden: ["POP", "ŞARKICI", "DANS", "MOONWALK", "MÜZİK"] },
{ main: "MİKRO DALGA", forbidden: ["ISITMAK", "YEMEK", "MUTFAK", "ELEKTRİK", "FIRIN"] },
{ main: "MİKROBİK", forbidden: ["BAKTERİ", "HASTALIK", "KÜÇÜK", "GÖZLE GÖRÜNMEZ", "BULAŞ"] },
{ main: "MİLLETVEKİLİ", forbidden: ["MECLİS", "SİYASET", "SEÇİM", "KANUN", "PARTİ"] },
{ main: "MİNARE", forbidden: ["CAMİ", "EZAN", "UZUN", "KULE", "İBADET"] },
{ main: "MİNYATÜR", forbidden: ["KÜÇÜK", "SANAT", "DETAY", "MAKET", "RESİM"] },
{ main: "MODEM", forbidden: ["İNTERNET", "BAĞLANTI", "WİFİ", "IŞIK", "AĞ"] },
{ main: "MOTOR", forbidden: ["ARAÇ", "ÇALIŞMAK", "BENZİN", "MEKANİK", "HAREKET"] },
{ main: "MOTOR YAĞI", forbidden: ["ARABA", "YAĞLAMA", "MOTOR", "BAKIM", "SIVI"] },
{ main: "MOTOSİKLET KASKI", forbidden: ["KORUMA", "KAFA", "SÜRÜŞ", "GÜVENLİK", "MOTOR"] },
{ main: "MOUSE", forbidden: ["BİLGİSAYAR", "TIKLAMAK", "İMLEÇ", "USB", "EL"] },
{ main: "MP3", forbidden: ["MÜZİK", "DOSYA", "SES", "DİNLEMEK", "FORMAT"] },
{ main: "MUM", forbidden: ["ATEŞ", "IŞIK", "ERİMEK", "KOKU", "WAX"] },
{ main: "MUMLU FANUS", forbidden: ["CAM", "DEKOR", "IŞIK", "MUM", "SÜS"] },
{ main: "MURAT BOZ", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "JÜRİ"] },
{ main: "MUSLUK", forbidden: ["SU", "AÇMAK", "KAPATMAK", "LAVABO", "AKMAK"] },
{ main: "MUSTAFA SANDAL", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "90LAR"] },
{ main: "MUTFAK", forbidden: ["YEMEK", "PİŞİRMEK", "OCAK", "DOLAP", "EV"] },
{ main: "MÜCEVHER", forbidden: ["TAKI", "DEĞERLİ", "ELMAS", "ALTIN", "PARLAK"] },
{ main: "MÜHÜR", forbidden: ["RESMİ", "BASMAK", "BELGE", "ONAY", "DAMGA"] },
{ main: "MÜREKKEP", forbidden: ["KALEM", "YAZI", "RENK", "DOLDURMAK", "SIVI"] },
{ main: "MÜSLÜM GÜRSES", forbidden: ["ARABESK", "ŞARKICI", "BABA", "MÜZİK", "DUYGU"] },
{ main: "MÜVEKKİL", forbidden: ["AVUKAT", "DAVA", "HUKUK", "VEKİL", "DOSYA"] },
{ main: "MÜZİK KUTUSU", forbidden: ["MELODİ", "ÇALMAK", "KUTU", "KURMALI", "SES"] },
{ main: "NAFAKA", forbidden: ["BOŞANMA", "MAHKEME", "ÖDEMEK", "HUKUK", "GEÇİM"] },
{ main: "NAMIK KEMAL", forbidden: ["ŞAİR", "YAZAR", "VATAN", "EDEBİYAT", "OSMANLI"] },
{ main: "NAR", forbidden: ["MEYVE", "KIRMIZI", "TANE", "EKŞİ", "KABUK"] },
{ main: "NARGİLE", forbidden: ["TÜTÜN", "DUMAN", "KAFE", "SU", "KÖMÜR"] },
{ main: "NASIR", forbidden: ["AYAK", "EL", "SERT", "DERİ", "AĞRI"] },
{ main: "NAZAR BONCUĞU", forbidden: ["MAVİ", "GÖZ", "KORUMA", "UĞUR", "TAKI"] },
{ main: "NEDİME", forbidden: ["DÜĞÜN", "GELİN", "ARKADAŞ", "YARDIMCI", "ELBİSE"] },
{ main: "NEŞET ERTAŞ", forbidden: ["BOZLAK", "HALK MÜZİĞİ", "SAZ", "USTA", "TÜRKÜ"] },
{ main: "NEVRESİM", forbidden: ["YATAK", "ÇARŞAF", "YASTIK", "UYKU", "TAKIM"] },
{ main: "NEVŞEHİR", forbidden: ["KAPADOKYA", "PERİ BACALARI", "TURİZM", "İL", "BALON"] },
{ main: "NEW YORK", forbidden: ["AMERİKA", "ŞEHİR", "ÖZGÜRLÜK", "MANHATTAN", "METROPOL"] },
{ main: "NİLÜFER", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SAHNE", "SANATÇI"] },
{ main: "NOT DEFTERİ", forbidden: ["YAZMAK", "KAĞIT", "NOT", "OKUL", "KAPAK"] },
{ main: "NOTA", forbidden: ["MÜZİK", "SES", "PORTRE", "ÇALMAK", "KAĞIT"] },
{ main: "OFİS", forbidden: ["ÇALIŞMAK", "MASA", "BİLGİSAYAR", "İŞ", "ŞİRKET"] },
{ main: "OJE", forbidden: ["TIRNAK", "RENK", "SÜRMEK", "KOZMETİK", "MANİKÜR"] },
{ main: "OKAN BAYÜLGEN", forbidden: ["SUNUCU", "TELEVİZYON", "PROGRAM", "ŞOV", "TİYATRO"] },
{ main: "OKUL", forbidden: ["ÖĞRENCİ", "ÖĞRETMEN", "DERS", "SINIF", "EĞİTİM"] },
{ main: "ORGANİZE İŞLER", forbidden: ["FİLM", "MAFYA", "KOMEDİ", "YILMAZ ERDOĞAN", "SOYGUN"] },
{ main: "ORHAN GENCEBAY", forbidden: ["ARABESK", "ŞARKICI", "BAĞLAMA", "BESTE", "MÜZİK"] },
{ main: "ORTALAMA", forbidden: ["TOPLAM", "BÖLMEK", "SAYI", "HESAP", "MATEMATİK"] },
{ main: "ORUÇ", forbidden: ["RAMAZAN", "AÇ", "İBADET", "SAHUR", "İFTAR"] },
{ main: "OTEL", forbidden: ["KONAKLAMA", "TATİL", "ODA", "REZERVASYON", "MÜŞTERİ"] },
{ main: "OTOMOBİL", forbidden: ["ARABA", "MOTOR", "TEKERLEK", "SÜRMEK", "ARAÇ"] },
{ main: "OTOPARK", forbidden: ["ARABA", "PARK ETMEK", "ALAN", "BİNA", "KAT"] },
{ main: "OYUN PARKI", forbidden: ["ÇOCUK", "SALINCAK", "KAYDIRAK", "EĞLENCE", "DIŞARISI"] },
{ main: "OZON TABAKASI", forbidden: ["ATMOSFER", "GÜNEŞ", "KORUMA", "DELİK", "DÜNYA"] },
{ main: "ÖDEV", forbidden: ["OKUL", "DERS", "ÖĞRETMEN", "YAPMAK", "NOT"] },
{ main: "ÖKÜZ", forbidden: ["HAYVAN", "BOYNUZ", "ÇİFTLİK", "BÜYÜK", "TARIM"] },
{ main: "ÖRGÜ", forbidden: ["ŞİŞ", "YÜN", "KAZAK", "ÖRMEK", "EL İŞİ"] },
{ main: "ÖRÜMCEK", forbidden: ["AĞ", "BÖCEK", "SEKİZ", "KORKU", "TIRMANMAK"] },
{ main: "ÖZGEÇMİŞ", forbidden: ["CV", "İŞ", "DENEYİM", "BAŞVURU", "BİLGİ"] },
{ main: "ÖZGÜRLÜK HEYKELİ", forbidden: ["AMERİKA", "NEW YORK", "ANIT", "MEŞALE", "SİMGE"] },
{ main: "PALET", forbidden: ["BOYA", "RENK", "AHŞAP", "TAŞIMA", "SANAT"] },
{ main: "PANİK ATAK", forbidden: ["KORKU", "NEFES", "KALP", "ANKSİYETE", "STRES"] },
{ main: "PANSİYON", forbidden: ["KONAKLAMA", "OTEL", "ODA", "TATİL", "UCUZ"] },
{ main: "PANTOLON", forbidden: ["KIYAFET", "BEL", "PAÇA", "GİYMEK", "JEAN"] },
{ main: "PAPYON", forbidden: ["KRAVAT", "RESMİ", "BOYUN", "TAKMAK", "SMOKİN"] },
{ main: "PARA", forbidden: ["BANKNOT", "KAZANMAK", "HARCAMAK", "CÜZDAN", "DEĞER"] },
{ main: "PARAŞÜT", forbidden: ["ATLAMAK", "UÇAK", "AÇILMAK", "HAVA", "SPOR"] },
{ main: "PARAZİT", forbidden: ["ASALAK", "VÜCUT", "BESLENMEK", "ZARAR", "CANLI"] },
{ main: "PARDESÜ", forbidden: ["KIYAFET", "DIŞ GİYİM", "UZUN", "MONT", "GİYMEK"] },
{ main: "PARFÜM", forbidden: ["KOKU", "SÜRMEK", "ŞİŞE", "ESANS", "TEN"] },
{ main: "PASAPORT", forbidden: ["YURTDIŞI", "KİMLİK", "SEYAHAT", "VİZE", "BELGE"] },
{ main: "PATEN PİSTİ", forbidden: ["BUZ", "KAYMAK", "SPOR", "AYAK", "SALON"] },
{ main: "PENÇE", forbidden: ["TIRNAK", "HAYVAN", "YIRTICI", "TUTMAK", "KESKİN"] },
{ main: "PENGUEN", forbidden: ["KUŞ", "SOĞUK", "ANTARKTİKA", "SİYAH BEYAZ", "YÜRÜMEK"] },
{ main: "PERDE", forbidden: ["PENCERE", "ASMAK", "KUMAŞ", "EV", "IŞIK"] },
{ main: "PERGEL", forbidden: ["ÇİZMEK", "DAİRE", "MATEMATİK", "OKUL", "UÇ"] },
{ main: "PET ŞİŞE", forbidden: ["PLASTİK", "SU", "İÇECEK", "KAPAK", "ŞİŞE"] },
{ main: "PİJAMA TAKIMI", forbidden: ["UYKU", "GECE", "GİYMEK", "RAHAT", "EV"] },
{ main: "PİKAP", forbidden: ["PLAK", "MÜZİK", "ÇALMAK", "İĞNE", "ESKİ"] },
{ main: "PİKAP İĞNESİ", forbidden: ["PLAK", "SES", "DÖNMEK", "MÜZİK", "UÇ"] },
{ main: "PİKNİK SEPETİ", forbidden: ["DOĞA", "YEMEK", "TAŞIMAK", "DIŞARISI", "ÖRTÜ"] },
{ main: "PİKSEL", forbidden: ["EKRAN", "GÖRÜNTÜ", "NOKTA", "ÇÖZÜNÜRLÜK", "RENK"] },
{ main: "PİL", forbidden: ["ENERJİ", "ELEKTRİK", "AKÜ", "ŞARJ", "CİHAZ"] },
{ main: "PİLATES TOPU", forbidden: ["SPOR", "EGZERSİZ", "DENGE", "YUVARLAK", "SALON"] },
{ main: "PİRAMİT", forbidden: ["MISIR", "FİRAVUN", "ÜÇGEN", "ANTİK", "TARİH"] },
{ main: "PİRİNÇ", forbidden: ["PİLAV", "TAHIL", "BEYAZ", "YEMEK", "TENCERE"] },
{ main: "PİŞMANİYE", forbidden: ["TATLI", "ŞEKER", "TEL", "KANDIRA", "YUMUŞAK"] },
{ main: "PİYANO", forbidden: ["TUŞ", "MÜZİK", "ÇALMAK", "ENSTRÜMAN", "NOTA"] },
{ main: "PLAY STATION", forbidden: ["OYUN", "KONSOL", "KUMANDA", "TELEVİZYON", "EĞLENCE"] },
{ main: "PODCAST", forbidden: ["SES", "DİNLEMEK", "İNTERNET", "KONUŞMA", "YAYIN"] },
{ main: "PODYUM", forbidden: ["DEFİLE", "MODA", "YÜRÜMEK", "SAHNE", "MODEL"] },
{ main: "POKER", forbidden: ["KART", "BAHİS", "OYUN", "MASA", "FİŞ"] },
{ main: "PRİZ", forbidden: ["ELEKTRİK", "FİŞ", "DUVAR", "AKIM", "ENERJİ"] },
{ main: "PROJE", forbidden: ["PLAN", "ÇALIŞMA", "SUNUM", "GÖREV", "EKİP"] },
{ main: "PROVA SALONU", forbidden: ["TİYATRO", "OYUNCU", "HAZIRLIK", "SAHNE", "TEKRAR"] },
{ main: "PUDRA ŞEKERİ", forbidden: ["TATLI", "BEYAZ", "PASTA", "SERPMEK", "ŞEKER"] },
{ main: "PUSULA", forbidden: ["YÖN", "KUZEY", "BULMAK", "HARİTA", "SEYAHAT"] },
{ main: "PUZZLE", forbidden: ["PARÇA", "BİRLEŞTİRMEK", "RESİM", "OYUN", "SABIR"] },
{ main: "RADYO", forbidden: ["SES", "KANAL", "DİNLEMEK", "FREKANS", "YAYIN"] },
{ main: "RAFTİNG", forbidden: ["NEHİR", "BOT", "SPOR", "AKINTI", "KASK"] },
{ main: "RAKI", forbidden: ["ALKOL", "ANASON", "MEZE", "İÇKİ", "SOFRA"] },
{ main: "RANZA", forbidden: ["YATAK", "ÜST", "ALT", "ODA", "ÇOCUK"] },
{ main: "REÇETE", forbidden: ["DOKTOR", "İLAÇ", "ECZANE", "YAZMAK", "HASTA"] },
{ main: "RENKLİ POST-İT", forbidden: ["NOT", "YAPIŞKAN", "KAĞIT", "MASA", "HATIRLATMA"] },
{ main: "RESİM SERGİSİ", forbidden: ["TABLO", "SANAT", "GALERİ", "RESSAM", "GÖSTERİM"] },
{ main: "ROBOT", forbidden: ["MAKİNE", "YAPAY ZEKA", "OTOMATİK", "TEKNOLOJİ", "METAL"] },
{ main: "ROKET", forbidden: ["UZAY", "FIRLATMAK", "HIZ", "YAKIT", "NASA"] },
{ main: "RÖNTGEN", forbidden: ["HASTANE", "IŞIN", "KEMİK", "GÖRÜNTÜ", "DOKTOR"] },
{ main: "RUHİ ÇENET", forbidden: ["YOUTUBER", "BELGESEL", "VİDEO", "İNTERNET", "İÇERİK"] },
{ main: "RÜZGAR ÇANI", forbidden: ["SES", "ASMAK", "BALKON", "DEKOR", "ESİNTİ"] },
{ main: "SAAT", forbidden: ["ZAMAN", "BİLEK", "AKREP", "YELKOVAN", "ÖLÇMEK"] },
{ main: "SAAT KULESİ", forbidden: ["MEYDAN", "ŞEHİR", "ZAMAN", "YAPI", "TARİH"] },
{ main: "SABAHLIK", forbidden: ["EV", "GİYMEK", "UYKU", "RAHAT", "KIYAFET"] },
{ main: "SAÇ", forbidden: ["KIL", "KESMEK", "BAŞ", "KUAFÖR", "TARAMAK"] },
{ main: "SAĞDIÇ", forbidden: ["DÜĞÜN", "DAMAT", "ARKADAŞ", "DESTEK", "NİKAH"] },
{ main: "SALINCAK", forbidden: ["PARK", "ÇOCUK", "İLERİ GERİ", "OTURMAK", "OYUN"] },
{ main: "SANDAL", forbidden: ["TEKNE", "DENİZ", "KÜREK", "KÜÇÜK", "SU"] },
{ main: "SANDIK", forbidden: ["EŞYA", "SAKLAMAK", "AHŞAP", "KAPAK", "ESKİ"] },
{ main: "SANDVİÇ", forbidden: ["EKMEK", "ARASI", "YEMEK", "PEYNİR", "HIZLI"] },
{ main: "SARMAŞIK", forbidden: ["BİTKİ", "TIRMANMAK", "YEŞİL", "DUVAR", "DOĞA"] },
{ main: "SATRANÇ", forbidden: ["ZEKA", "TAŞ", "ŞAH", "MAT", "OYUN"] },
{ main: "SEDA SAYAN", forbidden: ["SUNUCU", "ŞARKICI", "TELEVİZYON", "PROGRAM", "MAGAZİN"] },
{ main: "SEL", forbidden: ["SU", "AFET", "YAĞMUR", "TAŞKIN", "DOĞA"] },
{ main: "SELDA BAĞCAN", forbidden: ["HALK MÜZİĞİ", "ŞARKICI", "PROTEST", "TÜRKÜ", "SANATÇI"] },
{ main: "SELFIE ÇUBUĞU", forbidden: ["TELEFON", "FOTOĞRAF", "ÇEKMEK", "UZATMAK", "KAMERA"] },
{ main: "SELİN CİĞERCİ", forbidden: ["FENOMEN", "MAGAZİN", "SOSYAL MEDYA", "ÜNLÜ", "TELEVİZYON"] },
{ main: "SERA", forbidden: ["BİTKİ", "CAM", "ISITMA", "TARIM", "YETİŞTİRMEK"] },
{ main: "SERENAY SARIKAYA", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "SANATÇI"] },
{ main: "SERVİS ARACI", forbidden: ["OKUL", "TAŞIMA", "MİNİBÜS", "GÜZERGAH", "ÖĞRENCİ"] },
{ main: "SES YALITIMI", forbidden: ["GÜRÜLTÜ", "İZOLASYON", "DUVAR", "AKUSTİK", "ENGELLEME"] },
{ main: "SEVGİLİLER GÜNÜ", forbidden: ["14 ŞUBAT", "AŞK", "HEDİYE", "ÇİÇEK", "ROMANTİK"] },
{ main: "SEZEN AKSU", forbidden: ["ŞARKICI", "POP", "MÜZİK", "MİNİK SERÇE", "BESTE"] },
{ main: "SİBER GÜVENLİK", forbidden: ["İNTERNET", "BİLGİ", "KORUMA", "HACKER", "SİSTEM"] },
{ main: "SIFIR", forbidden: ["SAYI", "YOK", "BAŞLANGIÇ", "MATEMATİK", "DEĞER"] },
{ main: "SİGARA", forbidden: ["TÜTÜN", "DUMAN", "İÇMEK", "PAKET", "ZARAR"] },
{ main: "SİLAH", forbidden: ["TABANCA", "ATEŞ", "KURŞUN", "TEHLİKE", "POLİS"] },
{ main: "SİLİKON", forbidden: ["ESNEK", "MALZEME", "YAPIŞKAN", "KALIP", "PLASTİK"] },
{ main: "SİLİNDİR", forbidden: ["ŞEKİL", "GEOMETRİ", "YUVARLAK", "YAN", "YÜZEY"] },
{ main: "SİNAN ENGİN", forbidden: ["FUTBOL", "YORUMCU", "BEŞİKTAŞ", "TELEVİZYON", "SPOR"] },
{ main: "SİNEM KOBAL", forbidden: ["OYUNCU", "DİZİ", "FİLM", "TELEVİZYON", "SANATÇI"] },
{ main: "SİNEMA", forbidden: ["FİLM", "SALON", "PERDE", "BİLET", "İZLEMEK"] },
{ main: "SIR", forbidden: ["GİZLİ", "SAKLAMAK", "BİLİNMEYEN", "AÇIKLAMAMAK", "ÖZEL"] },
{ main: "SİVRİSİNEK", forbidden: ["ISIRMAK", "KAN", "UÇMAK", "BÖCEK", "KAŞINTI"] },
{ main: "SODA", forbidden: ["İÇECEK", "GAZLI", "ŞİŞE", "MADEN", "SERİN"] },
{ main: "SOKAK LAMBASI", forbidden: ["IŞIK", "GECE", "YOL", "AYDINLATMA", "DİREK"] },
{ main: "SOMON", forbidden: ["BALIK", "PEMBE", "DENİZ", "IZGARA", "OMEGA"] },
{ main: "SONBAHAR", forbidden: ["MEVSİM", "YAPRAK", "SARI", "SERİN", "EYLÜL"] },
{ main: "SÖZLÜK", forbidden: ["KELİME", "ANLAM", "AÇIKLAMA", "KİTAP", "BAKMAK"] },
{ main: "SPREY BOYA", forbidden: ["BOYAMAK", "DUVAR", "GRAFFİTİ", "RENK", "BASINÇ"] },
{ main: "STETESKOP", forbidden: ["DOKTOR", "KALP", "DİNLEMEK", "HASTANE", "MUAYENE"] },
{ main: "SUCUK", forbidden: ["ET", "KAHVALTI", "BAHARAT", "KIZARTMA", "SUCİUK"] },
{ main: "SURVIVOR", forbidden: ["YARIŞMA", "ADA", "AÇLIK", "DOKUNULMAZLIK", "TELEVİZYON"] },
{ main: "SUSAMLI SİMİT", forbidden: ["SİMİT", "SUSAM", "SOKAK", "KAHVALTI", "YUVARLAK"] },
{ main: "SÜPERMAN", forbidden: ["KAHRAMAN", "UÇMAK", "PELERİN", "GÜÇ", "ÇİZGİ ROMAN"] },
{ main: "SÜPÜRGE", forbidden: ["TEMİZLİK", "EV", "ELEKTRİK", "TOZ", "ÇEKMEK"] },
{ main: "SÜRAHİ", forbidden: ["SU", "CAM", "DÖKMEK", "MASA", "KAP"] },
{ main: "SÜTLAÇ", forbidden: ["TATLI", "SÜT", "PİRİNÇ", "FIRIN", "ŞEKER"] },
{ main: "SÜZGEÇ", forbidden: ["SU", "MAKARNA", "DELİK", "MUTFAK", "SÜZMEK"] },
{ main: "ŞALTER", forbidden: ["ELEKTRİK", "AÇMAK", "KAPATMAK", "SİGORTA", "AKIM"] },
{ main: "ŞAPKACI", forbidden: ["ŞAPKA", "DÜKKAN", "SATMAK", "AKSESUAR", "BAŞ"] },
{ main: "ŞARAP MAHZENİ", forbidden: ["ŞARAP", "BODRUM", "FİÇI", "SOĞUK", "SAKLAMAK"] },
{ main: "ŞARJ İSTASYONU", forbidden: ["ELEKTRİK", "TELEFON", "PİL", "DOLDURMAK", "ENERJİ"] },
{ main: "ŞEHVET", forbidden: ["ARZU", "İSTEK", "TUTKU", "DUYGU", "NEFS"] },
{ main: "ŞEKER", forbidden: ["TATLI", "KÜP", "ÇAY", "BEYAZ", "ŞEKERLEME"] },
{ main: "ŞEKERLEME", forbidden: ["TATLI", "RENKLİ", "PAKET", "ÇOCUK", "YEMEK"] },
{ main: "ŞELALE", forbidden: ["SU", "AKMAK", "DOĞA", "YÜKSEK", "GÜRÜLTÜ"] },
{ main: "ŞEMPANZE", forbidden: ["MAYMUN", "HAYVAN", "ZEKA", "ORMAN", "AFRİKA"] },
{ main: "ŞEMSİYE", forbidden: ["YAĞMUR", "AÇMAK", "ISLANMAK", "SAP", "KORUMA"] },
{ main: "ŞEMSİYELİK", forbidden: ["ŞEMSİYE", "KAPI", "KONMAK", "METAL", "EV"] },
{ main: "ŞENER ŞEN", forbidden: ["OYUNCU", "YEŞİLÇAM", "FİLM", "KOMEDİ", "SANATÇI"] },
{ main: "ŞEYTAN", forbidden: ["KÖTÜ", "GÜNAH", "DİN", "İBLİS", "AYARTMAK"] },
{ main: "ŞİFONYER", forbidden: ["MOBİLYA", "ÇEKMECE", "ODA", "KIYAFET", "DOLAP"] },
{ main: "ŞİFRE", forbidden: ["GÜVENLİK", "KOD", "GİRİŞ", "GİZLİ", "PAROLA"] },
{ main: "ŞÖMİNE", forbidden: ["ATEŞ", "ISINMA", "ODUN", "SALON", "DUMAN"] },
{ main: "TABU", forbidden: ["OYUN", "ANLATMAK", "KELİME", "YASAK", "TAKIM"] },
{ main: "TABUT", forbidden: ["CENAZE", "ÖLÜM", "TAŞIMAK", "AHŞAP", "GÖMÜLMEK"] },
{ main: "TAKVİM", forbidden: ["GÜN", "AY", "YIL", "TARİH", "YAPRAK"] },
{ main: "TANGO", forbidden: ["DANS", "ARJANTİN", "MÜZİK", "ÇİFT", "RİTİM"] },
{ main: "TANRI", forbidden: ["İNANÇ", "YARATAN", "DİN", "İLAH", "KUTSAL"] },
{ main: "TARIK AKAN", forbidden: ["OYUNCU", "YEŞİLÇAM", "FİLM", "SANATÇI", "SİNEMA"] },
{ main: "TARİH ÖZETİ", forbidden: ["GEÇMİŞ", "KISA", "OLAY", "KRONOLOJİ", "KONU"] },
{ main: "TAŞ FIRIN", forbidden: ["EKMEK", "PİZZA", "ODUN", "SICAK", "PİŞİRMEK"] },
{ main: "TATİL KÖYÜ", forbidden: ["OTEL", "DENİZ", "KONAKLAMA", "HAVUZ", "EĞLENCE"] },
{ main: "TAVLA", forbidden: ["ZAR", "OYUN", "PUL", "TAHTA", "ATMAK"] },
{ main: "TAVŞAN", forbidden: ["HAYVAN", "KULAK", "HIZLI", "HAVUÇ", "ZIPLAMAK"] },
{ main: "TEHLİKE", forbidden: ["RİSK", "UYARI", "ZARAR", "KORKU", "DİKKAT"] },
{ main: "TEKERLEK", forbidden: ["YUVARLAK", "ARAÇ", "DÖNMEK", "LASTİK", "HAREKET"] },
{ main: "TELEFON", forbidden: ["ARAMAK", "KONUŞMAK", "CEP", "EKRAN", "NUMARA"] },
{ main: "TELEFON KILIFI", forbidden: ["KORUMAK", "CEP", "PLASTİK", "KAPAK", "AKSESUAR"] },
{ main: "TENİS", forbidden: ["RAKET", "TOP", "SAHA", "SERVİS", "SPOR"] },
{ main: "TEOMAN", forbidden: ["ŞARKICI", "ROCK", "MÜZİK", "SAHNE", "ŞARKI"] },
{ main: "TERAZİ", forbidden: ["TARTMAK", "DENGE", "AĞIRLIK", "ÖLÇMEK", "KEFE"] },
{ main: "TERLİK", forbidden: ["AYAK", "EV", "RAHAT", "GİYMEK", "TABAN"] },
{ main: "TERMİNAL", forbidden: ["OTOBÜS", "UÇAK", "YOLCU", "BİNA", "ULAŞIM"] },
{ main: "TERMOMETRE", forbidden: ["SICAKLIK", "ÖLÇMEK", "DERECE", "ATEŞ", "CİHAZ"] },
{ main: "TERMOS", forbidden: ["SICAK", "SOĞUK", "İÇECEK", "ÇELİK", "TUTMAK"] },
{ main: "TIRNAK", forbidden: ["EL", "KESMEK", "PARMAK", "OJE", "UZAMAK"] },
{ main: "TIRAŞ KÖPÜĞÜ", forbidden: ["SAKAL", "KÖPÜK", "YÜZ", "TRAŞ", "SÜRMEK"] },
{ main: "TIRAŞ MAKİNESİ", forbidden: ["SAKAL", "KESMEK", "ELEKTRİKLİ", "BAŞLIK", "ERKEK"] },
{ main: "TİYATRO", forbidden: ["SAHNE", "OYUNCU", "PERDE", "OYNAMA", "SEYİRCİ"] },
{ main: "TOLGA ÇEVİK", forbidden: ["KOMEDYEN", "OYUNCU", "TİYATRO", "DOĞAÇLAMA", "SAHNE"] },
{ main: "TOST MAKİNESİ", forbidden: ["EKMEK", "PEYNİR", "ISITMAK", "MUTFAK", "ELEKTRİK"] },
{ main: "TRAFİK IŞIĞI", forbidden: ["KIRMIZI", "SARI", "YEŞİL", "YOL", "DURMAK"] },
{ main: "TRAMBOLİN", forbidden: ["ZIPLAMAK", "SPOR", "ÇOCUK", "ESNEK", "ZEMİN"] },
{ main: "TREN RAYI", forbidden: ["TREN", "DEMİR", "YOL", "UÇ", "ULAŞIM"] },
{ main: "TURİZM", forbidden: ["GEZİ", "TATİL", "YABANCI", "SEYAHAT", "EKONOMİ"] },
{ main: "TUVAL", forbidden: ["RESİM", "BOYA", "SANAT", "ÇİZMEK", "TABLO"] },
{ main: "TUZLUK", forbidden: ["TUZ", "MASA", "SERPMEK", "YEMEK", "KÜÇÜK"] },
{ main: "TÜRBAN", forbidden: ["BAŞ", "ÖRTÜ", "KIYAFET", "BAĞLAMAK", "KADIN"] },
{ main: "TÜRKİYE", forbidden: ["ÜLKE", "ANKARA", "İSTANBUL", "BAYRAK", "CUMHURİYET"] },
{ main: "UÇAK", forbidden: ["UÇMAK", "KANAT", "HAVAALANI", "PİLOT", "YOLCU"] },
{ main: "UÇURTMA", forbidden: ["RÜZGAR", "İP", "UÇMAK", "GÖKYÜZÜ", "ÇOCUK"] },
{ main: "UFUK ÇİZGİSİ", forbidden: ["DENİZ", "GÖKYÜZÜ", "UZA K", "ÇİZGİ", "BAKIŞ"] },
{ main: "UĞUR BÖCEĞİ", forbidden: ["BÖCEK", "KIRMIZI", "BENEK", "UĞUR", "UÇMAK"] },
{ main: "UYDU", forbidden: ["UZAY", "YÖRÜNGE", "SİNYAL", "TELEVİZYON", "HABERLEŞME"] },
{ main: "UYKU TULUMU", forbidden: ["KAMP", "SOĞUK", "UYUMAK", "DOĞA", "GECE"] },
{ main: "UZAY GEMİSİ", forbidden: ["UZAY", "ROKET", "ASTRONOT", "UÇMAK", "TEKNOLOJİ"] },
{ main: "UZAY İSTASYONU", forbidden: ["UZAY", "ASTRONOT", "YÖRÜNGE", "DÜNYA", "ARAŞTIRMA"] },
{ main: "UZLAŞMAK", forbidden: ["ANLAŞMAK", "ORTA YOL", "BARIŞ", "KABUL", "SORUN"] },
{ main: "ÜMİT ÖZDAĞ", forbidden: ["SİYASET", "PARTİ", "GENEL BAŞKAN", "MECLİS", "GÜNDEM"] },
{ main: "ÜNİVERSİTE", forbidden: ["ÖĞRENCİ", "FAKÜLTE", "KAMPÜS", "EĞİTİM", "DERS"] },
{ main: "VAGON", forbidden: ["TREN", "RAY", "TAŞIMA", "YOLCU", "DEMİR"] },
{ main: "VANTİLATÖR", forbidden: ["SERİN", "HAVA", "DÖNMEK", "YAZ", "ELEKTRİK"] },
{ main: "VAZO", forbidden: ["ÇİÇEK", "CAM", "SÜS", "MASA", "DEKOR"] },
{ main: "VEHBİ KOÇ", forbidden: ["İŞ İNSANI", "KOÇ HOLDİNG", "SANAYİ", "GİRİŞİMCİ", "VAKIF"] },
{ main: "VENEDİK", forbidden: ["İTALYA", "KANAL", "GONDOL", "ŞEHİR", "SU"] },
{ main: "VİAGRA", forbidden: ["İLAÇ", "EREKSİYON", "MAVİ", "DOKTOR", "HAP"] },
{ main: "VİTRİN MANKENİ", forbidden: ["MAĞAZA", "KIYAFET", "CAM", "SERGİ", "DURMAK"] },
{ main: "VOLKAN KONAK", forbidden: ["ŞARKICI", "KARADENİZ", "MÜZİK", "TÜRKÜ", "SAHNE"] },
{ main: "YALAKA", forbidden: ["YAĞCI", "MENFAAT", "ABARTI", "ÖVGÜ", "İKİYÜZLÜ"] },
{ main: "YANGIN MERDİVENİ", forbidden: ["ACİL", "BİNA", "KAÇIŞ", "GÜVENLİK", "MERDİVEN"] },
{ main: "YANGIN SÖNDÜRME TÜPÜ", forbidden: ["ATEŞ", "KÖPÜK", "ACİL", "GÜVENLİK", "KIRMIZI"] },
{ main: "YAPAY ZEKA ASİSTANI", forbidden: ["TEKNOLOJİ", "SOHBET", "OTOMATİK", "YAZILIM", "DİJİTAL"] },
{ main: "YASTIK", forbidden: ["UYKU", "YATAK", "BAŞ", "YUMUŞAK", "KILIF"] },
{ main: "YAZI", forbidden: ["KALEM", "KAĞIT", "HARF", "OKUMAK", "METİN"] },
{ main: "YELKENLİ", forbidden: ["DENİZ", "RÜZGAR", "TEKNE", "YELKEN", "SEYİR"] },
{ main: "YELKOVAN", forbidden: ["SAAT", "ZAMAN", "DÖNMEK", "AKREP", "GÖSTERGE"] },
{ main: "YELPAZE", forbidden: ["SERİNLEMEK", "EL", "AÇMAK", "YAZ", "HAVA"] },
{ main: "YENGEÇ", forbidden: ["DENİZ", "KABUK", "YAN YÜRÜMEK", "MAKAS", "BURÇ"] },
{ main: "YENİÇERİ", forbidden: ["OSMANLI", "ASKER", "ORDU", "TARİH", "KAPIKULU"] },
{ main: "YILMAZ ERDOĞAN", forbidden: ["OYUNCU", "SENARİST", "TİYATRO", "FİLM", "BKM"] },
{ main: "YOL HARİTASI", forbidden: ["PLAN", "STRATEJİ", "ROTA", "HEDEF", "ADIM"] },
{ main: "YUMURTA", forbidden: ["TAVUK", "KABUK", "KAHVALTI", "BEYAZ", "SARI"] },
{ main: "YUMUŞAK", forbidden: ["SERT", "DOKU", "HAFİF", "ESNEK", "RAHAT"] },
{ main: "YÜKSEK LİSANS", forbidden: ["ÜNİVERSİTE", "EĞİTİM", "TEZ", "AKADEMİK", "MEZUNİYET"] },
{ main: "YÜRÜYEN MERDİVEN", forbidden: ["AVM", "İNMEK", "ÇIKMAK", "BASAMAK", "ELEKTRİK"] },
{ main: "YÜZÜK", forbidden: ["TAKI", "PARMAK", "EVLİLİK", "ALTIN", "ALYANS"] },
{ main: "ZAMAN KAPSÜLÜ", forbidden: ["GELECEK", "SAKLAMAK", "HATIRA", "GÖMMEK", "AÇMAK"] },
{ main: "ZARF", forbidden: ["MEKTUP", "KAĞIT", "İÇİNE KOYMAK", "POSTA", "KAPALI"] },
{ main: "ZEKİ MÜREN", forbidden: ["SANAT GÜNEŞİ", "ŞARKICI", "KLASİK", "MÜZİK", "SAHNE"] },
{ main: "ZENCEFİL", forbidden: ["BAHARAT", "KÖK", "ACIMSI", "ÇAY", "AROMA"] },
{ main: "ZEYNEP BASTIK", forbidden: ["ŞARKICI", "POP", "MÜZİK", "SOSYAL MEDYA", "SAHNE"] },
{ main: "ZİL", forbidden: ["ÇALMAK", "SES", "KAPI", "OKUL", "UYARI"] },
{ main: "ZIMBA", forbidden: ["KAĞIT", "TEL", "TUTTURMAK", "OFİS", "DELMEK"] },
{ main: "ZİNA", forbidden: ["EVLİLİK", "ALDATMA", "İLİŞKİ", "GÜNAH", "YASAK"] },
{ main: "ZİRVE", forbidden: ["DAĞ", "EN YÜKSEK", "TEPE", "BAŞARI", "TIRMANMAK"] },
{ main: "ZUHAL TOPAL", forbidden: ["SUNUCU", "PROGRAM", "TELEVİZYON", "EVLİLİK", "YARIŞMA"] },
{ main: "GÜVENLİK KAMERASI", forbidden: ["KAMERA", "GÜVENLİK", "KAYIT", "İZLEME", "MONİTÖR"] },
{ main: "ŞİMŞEK", forbidden: ["YILDIRIM", "GÖKYÜZÜ", "FIRTINA", "GÜRÜLTÜ", "YAĞMUR"] },
{ main: "TUTKAL", forbidden: ["YAPIŞKAN", "YAPIŞTIRMAK", "ZAMK", "KAĞIT", "BANT"] },
{ main: "OTOBAN", forbidden: ["YOL", "ARAÇ", "HIZ", "TRAFİK", "ASFALT"] },
{ main: "KÜRE", forbidden: ["YUVARLAK", "TOP", "DÜNYA", "GEOMETRİ", "ŞEKİL"] },
{ main: "GÖK GÜRÜLTÜSÜ", forbidden: ["ŞİMŞEK", "SES", "FIRTINA", "YAĞMUR", "BULUT"] },
{ main: "PİZZA KUTUSU", forbidden: ["PİZZA", "KUTU", "KARTON", "YEMEK", "SERVİS"] },
{ main: "TARAK", forbidden: ["SAÇ", "DİŞ", "DÜZELTMEK", "KUAFÖR", "SAÇ TARAĞI"] },
{ main: "KABARTMA", forbidden: ["HAMUR", "KABARMAK", "MAYA", "PİŞİRME", "FIRIN"] },
{ main: "TANKER", forbidden: ["ARAÇ", "AKARYAKIT", "TAŞIMA", "KAMYON", "PETROL"] },
{ main: "BALKON", forbidden: ["EV", "DIŞARI", "CAM", "DAİRE", "MANZARA"] },
{ main: "SİS", forbidden: ["BULUT", "GÖRÜŞ", "HAVA", "PUS", "YOĞUN"] },
{ main: "KUM TORBASI", forbidden: ["KUM", "TORBA", "SEL", "AĞIRLIK", "KORUMA"] },
{ main: "KAVŞAK", forbidden: ["YOL", "TRAFİK", "DÖNÜŞ", "IŞIK", "ARAÇ"] },
{ main: "ŞARJ ALETİ", forbidden: ["ELEKTRİK", "TELEFON", "KABLO", "PRİZ", "BATARYA"] },
{ main: "HAMAK", forbidden: ["UYUMAK", "AĞAÇ", "SALLANMAK", "TATİL", "BAHÇE"] },
{ main: "KANALİZASYON", forbidden: ["ATIK", "SU", "BORU", "ALT", "ŞEHİR"] },
{ main: "VİTRİN", forbidden: ["MAĞAZA", "CAM", "SERGİ", "ÜRÜN", "DÜKKAN"] },
{ main: "UÇAK BİLETİ", forbidden: ["UÇAK", "SEYAHAT", "HAVAALANI", "YOLCU", "REZERVASYON"] },
{ main: "MOLOZ", forbidden: ["İNŞAAT", "ATIK", "YIKINTI", "TAŞ", "BETON"] },
{ main: "ÜTÜ MASASI", forbidden: ["ÜTÜ", "KIYAFET", "DÜZ", "EV", "KUMAŞ"] },
{ main: "MÜHENDİS", forbidden: ["MESLEK", "PROJE", "HESAP", "TEKNİK", "İNŞAAT"] },
{ main: "GÜMÜŞ", forbidden: ["METAL", "TAKI", "RENK", "ALTIN", "PARLAK"] },
{ main: "SİGARA TABLASI", forbidden: ["SİGARA", "KÜL", "DUMAN", "MASA", "İZMARİT"] },
{ main: "RULET", forbidden: ["KUMAR", "ÇARK", "TOP", "CASİNO", "BAHİS"] },
{ main: "RÜZGAR GÜLÜ", forbidden: ["RÜZGAR", "YÖN", "ENERJİ", "DÖNMEK", "KANAT"] },
{ main: "ZİGON", forbidden: ["MASA", "SEHPA", "ÜST ÜSTE", "SALON", "MOBİLYA"] },
{ main: "LİMAN", forbidden: ["GEMİ", "DENİZ", "YÜK", "İSKELE", "KARGO"] },
{ main: "DİNOZOR", forbidden: ["TARİH", "FOSİL", "DEV", "ESKİ", "HAYVAN"] },
{ main: "YANGIN DEDEKTÖRÜ", forbidden: ["DUMAN", "ALARM", "YANGIN", "SES", "GÜVENLİK"] },
{ main: "YOLCU KABİNİ", forbidden: ["UÇAK", "OTOBÜS", "KOLTUK", "SEYAHAT", "İÇ"] },
{ main: "FIRTINA", forbidden: ["RÜZGAR", "YAĞMUR", "DALGA", "ŞİMŞEK", "HAVA"] },
{ main: "OKSİJEN TÜPÜ", forbidden: ["NEFES", "HASTANE", "GAZ", "MASKE", "SOLUNUM"] },
{ main: "ÇANAK", forbidden: ["TOPRAK", "KASE", "SERAMİK", "TABAK", "KAP"] },
{ main: "ENKAZ", forbidden: ["YIKINTI", "DEPREM", "MOLOZ", "BİNA", "KALINTI"] },
{ main: "ELEKTRİK SAYACI", forbidden: ["ELEKTRİK", "TÜKETİM", "FATURA", "KWH", "ÖLÇÜM"] },
{ main: "AMBAR", forbidden: ["DEPO", "YÜK", "SAKLAMA", "GEMİ", "ÜRÜN"] },
{ main: "İNŞAAT", forbidden: ["BİNA", "ŞANTİYE", "BETON", "USTA", "YAPI"] },
{ main: "UZAY MEKİĞİ", forbidden: ["UZAY", "ROKET", "NASA", "ASTRONOT", "GÖREV"] },
{ main: "BÖLME", forbidden: ["AYIRMAK", "DUVAR", "PARÇA", "ODA", "AYRAÇ"] },
{ main: "AT NALI", forbidden: ["AT", "ŞANS", "DEMİR", "NAL", "UĞUR"] },
{ main: "PEÇETE", forbidden: ["KAĞIT", "SİLMEK", "MASA", "YEMEK", "TEMİZ"] },
{ main: "ARNAVUT KALDIRIMI", forbidden: ["TAŞ", "YOL", "ESKİ", "SOKAK", "ZEMİN"] },
{ main: "BOYA FIRÇASI", forbidden: ["BOYA", "RESİM", "KIL", "SAP", "DUVAR"] },
{ main: "DENİZANASI", forbidden: ["DENİZ", "ŞEFFAF", "CANLI", "YAKAR", "SU"] },
{ main: "TÜNEL", forbidden: ["YOL", "ALT", "DAĞ", "GEÇİT", "KARANLIK"] },
{ main: "TENCERE KAPAĞI", forbidden: ["TENCERE", "MUTFAK", "KAPAK", "PİŞİRME", "CAM"] },
{ main: "MASA TENİSİ", forbidden: ["PINGPONG", "TOP", "RAKET", "MASA", "SPOR"] },
{ main: "VANTUZ", forbidden: ["EMMEK", "CAM", "LASTİK", "YAPIŞMA", "TUTMAK"] },
{ main: "DALGAKIRAN", forbidden: ["DENİZ", "DALGA", "LİMAN", "TAŞ", "KORUMA"] },
{ main: "ÇALI", forbidden: ["BİTKİ", "DİKEN", "AĞAÇ", "YEŞİL", "DOĞA"] },
{ main: "İZOLASYON", forbidden: ["YALITIM", "SES", "ISI", "KORUMA", "AYIRMA"] },
{ main: "YILDIZ HARİTASI", forbidden: ["UZAY", "YILDIZ", "GÖKYÜZÜ", "ASTRONOMİ", "TAKIMYILDIZ"] },
{ main: "AFİŞ", forbidden: ["POSTER", "DUYURU", "DUVAR", "REKLAM", "KAĞIT"] },
{ main: "GEZEGEN", forbidden: ["UZAY", "DÜNYA", "GÜNEŞ", "YÖRÜNGE", "ASTRONOMİ"] },
{ main: "SAKIZ", forbidden: ["ÇİĞNEMEK", "AĞIZ", "TATLI", "BALON", "YAPIŞKAN"] },
{ main: "KARINCA", forbidden: ["BÖCEK", "KÜÇÜK", "ÇALIŞKAN", "YUVA", "TOPRAK"] },
{ main: "YOL ÇİZGİSİ", forbidden: ["ASFALT", "ŞERİT", "TRAFİK", "BEYAZ", "YOL"] },
{ main: "GÜVERTE", forbidden: ["GEMİ", "TEKNE", "ÜST", "DENİZ", "ZEMİN"] },
{ main: "SAÇ KURUTMA MAKİNESİ", forbidden: ["SAÇ", "HAVA", "ELEKTRİK", "BANYO", "KURUTMA"] },
{ main: "TORNAVİDA", forbidden: ["VİDA", "ALET", "ÇEVİRMEK", "TAMİR", "EL"] },
{ main: "KÖPRÜ", forbidden: ["YOL", "GEÇİŞ", "IRMAK", "BAĞLAMAK", "ÜST"] },
{ main: "ÇEKİRDEK", forbidden: ["KABUK", "ATIŞTIRMAK", "AYÇEKİRDEĞİ", "TUZLU", "AĞIZ"] },
{ main: "BOT", forbidden: ["TEKNE", "DENİZ", "KÜÇÜK", "MOTOR", "SU"] },
{ main: "ŞNORKEL", forbidden: ["DENİZ", "DALMAK", "MASKE", "SU", "NEFES"] },
{ main: "BEŞİK", forbidden: ["BEBEK", "UYUMAK", "SALLANMAK", "AHŞAP", "YATAK"] },
{ main: "İSKELET", forbidden: ["KEMİK", "VÜCUT", "İNSAN", "YAPI", "ANATOMİ"] },
{ main: "SİFON", forbidden: ["TUVALET", "SU", "ÇEKMEK", "BANYO", "TEMİZ"] },
{ main: "KAPI TOKMAĞI", forbidden: ["KAPI", "METAL", "VURMAK", "GİRİŞ", "TOK"] },
{ main: "DOLU", forbidden: ["YAĞIŞ", "BUZ", "FIRTINA", "GÖKYÜZÜ", "HAVA"] },
{ main: "ÇİVİ", forbidden: ["ÇAKMAK", "DEMİR", "TAHTA", "ÇEKİÇ", "METAL"] },
{ main: "FOSİL", forbidden: ["TARİH", "TAŞ", "DİNOZOR", "KALINTI", "TOPRAK"] },
{ main: "DENİZ YILDIZI", forbidden: ["DENİZ", "CANLI", "BEŞ KOL", "SU", "HAYVAN"] },
{ main: "SAĞANAK", forbidden: ["YAĞMUR", "ŞİDDETLİ", "HAVA", "ISLANMAK", "BULUT"] },
{ main: "SU TERAZİSİ", forbidden: ["DÜZ", "ÖLÇÜ", "İNŞAAT", "HAVA", "ALETLER"] },
{ main: "SU KAYDIRAĞI", forbidden: ["HAVUZ", "KAYMAK", "EĞLENCE", "PARK", "ISLAK"] },
{ main: "MASAÜSTÜ", forbidden: ["BİLGİSAYAR", "EKRAN", "KLAVYE", "PC", "ÇALIŞMA"] },
{ main: "ÇİĞ", forbidden: ["KAR", "DAĞ", "KAYMA", "SOĞUK", "DOĞA"] },
{ main: "KATIR", forbidden: ["HAYVAN", "YÜK", "AT", "EŞEK", "TAŞIMAK"] },
{ main: "AYNA", forbidden: ["YANSIMA", "CAM", "BAKMAK", "GÖRÜNTÜ", "DUVAR"] },
{ main: "KÜREK", forbidden: ["TOPRAK", "KAZMAK", "EL", "BAHÇE", "KAR"] },
{ main: "GÖKKUŞAĞI", forbidden: ["RENK", "YAĞMUR", "GÜNEŞ", "GÖKYÜZÜ", "YAY"] },
{ main: "MONİTÖR", forbidden: ["EKRAN", "BİLGİSAYAR", "GÖRÜNTÜ", "MASAÜSTÜ", "LCD"] },
{ main: "TELESKOP", forbidden: ["UZAY", "YILDIZ", "GÖKYÜZÜ", "BAKMAK", "ASTRONOMİ"] },
{ main: "YAPIŞKAN", forbidden: ["TUTKAL", "ZAMK", "BANT", "YAPIŞTIRMAK", "MADDE"] },
{ main: "YANARDAĞ", forbidden: ["LAVA", "PATLAMA", "DAĞ", "ATEŞ", "MAGMA"] },
{ main: "MUMYA", forbidden: ["MISIR", "SARGI", "ÖLÜ", "TARİH", "PİRAMİT"] },
{ main: "VİNÇ", forbidden: ["İNŞAAT", "KALDIRMAK", "AĞIR", "MAKİNE", "ŞANTİYE"] },
{ main: "VİRAJ", forbidden: ["YOL", "DÖNÜŞ", "ARABA", "KESKİN", "TRAFİK"] },
{ main: "FERİBOT", forbidden: ["DENİZ", "ARAÇ", "GEMİ", "YOLCU", "İSKELE"] },
{ main: "YAYA GEÇİDİ", forbidden: ["YOL", "TRAFİK", "İNSAN", "ÇİZGİ", "GEÇMEK"] },
{ main: "HEYKELTIRAŞ", forbidden: ["SANAT", "TAŞ", "YONTMAK", "HEYKEL", "SANATÇI"] },
{ main: "KLİŞE", forbidden: ["BASMAK", "TEKRAR", "SÖZ", "KALIP", "BASMA"] },
{ main: "ŞİŞE", forbidden: ["CAM", "SU", "İÇECEK", "KAP", "KAPAK"] },
{ main: "TABAK ÇANAK", forbidden: ["MUTFAK", "YEMEK", "BULAŞIK", "KAP", "SOFRA"] },
{ main: "ŞANTİYE", forbidden: ["İNŞAAT", "BİNA", "USTA", "ÇALIŞMA", "ALAN"] },
{ main: "KUANTUM", forbidden: ["FİZİK", "BİLİM", "ATOM", "TEORİ", "ENERJİ"] },
{ main: "FİYONK", forbidden: ["KURDELE", "SÜS", "BAĞLAMAK", "HEDİYE", "ŞERİT"] },
{ main: "BUZDOLABI POŞETİ", forbidden: ["POŞET", "BUZDOLABI", "SAKLAMAK", "YİYECEK", "NAYLON"] },
{ main: "ANAHTARLIK", forbidden: ["ANAHTAR", "METAL", "TAKMAK", "CEP", "HALKA"] },
{ main: "PENSE", forbidden: ["ALET", "TUTMAK", "SÖKMEK", "EL", "TAMİR"] },
{ main: "RADYATÖR", forbidden: ["ISITMA", "PETEK", "KALORİFER", "EV", "SICAK"] },
{ main: "GÖLGE", forbidden: ["IŞIK", "GÜNEŞ", "KARANLIK", "ŞEKİL", "YANSIMA"] },
{ main: "SİREN", forbidden: ["SES", "ALARM", "POLİS", "AMBULANS", "UYARI"] }
 ];
